### ISSUE TITLE
TwilioVideo's main thread use rate is large.

### ISSUE THREAD

**Issue by kboy-silvergym** [twilio/twilio-video-ios#10]
Hello! Thank you for resolving the issue https://github.com/twilio/twilio-video-ios/issues/9 before this!

This time, I am facing with the problem. Not reporting a bug.

### About

As you can see the below image, TwilioVideo SDK's Main thread use rate has a large percentage.

<img width="438" alt="2018-05-18 19 05 13" src="https://user-images.githubusercontent.com/17683316/40230009-04f4303e-5ad1-11e8-89f3-14ab49c06b4d.png">

### Description

Especially when I used the device which performance is not so good such as iPhone7Plus, The frame rate falls instantly on my app.😱

I thought that is because something use Main thread too much, so I researched about it using [Timer Profiler In Instrument](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/Instrument-TimeProfiler.html ).

Then, I found the TwilioVideo SDK uses Main thread so much. 

If I called Twilio API in background thread (like below code), the situation did not change..

```swift
let captureQueue = DispatchQueue(label: "hogehoge.twilio-capture")
let sendQueue = DispatchQueue(label: "hogehoge.twilio-send")
let delegateQueue = DispatchQueue(label: "hogehoge.twilio-delegate")

func connect() {
    captureQueue.async {
        let block = { [weak self] (_ builder: TVIConnectOptionsBuilder) in
            builder.delegateQueue = wSelf.delegateQueue
        }
        let options = TVIConnectOptions(token: self.accessToken, block: { (_ builder: TVIConnectOptionsBuilder) -> Void in
            block(builder)
        })
        self.tviRoom = TwilioVideo.connect(with: options, delegate: self)
    }
}

func send(data: Data){
    guard let dataTrack = dataTrack else { return }
    sendQueue.async {
        dataTrack.send(data)
    }
}
```

If there's something I can do for resolving this, give me some advice! And If this SDK has room for improvement for this, I hope updating! 👍 

By the way, my app is sending SceneView's capture using TwilioVideo. But, SceneView is not related to this issue, I think.

### Steps to Reproduce

Just connect TwilioVideo with some devices.

#### Expected Behavior

TwilioVideo's Main thread use rate will be small.

#### Actual Behavior

TwilioVideo's Main thread use rate is large.

#### Reproduces How Often

Everytime.

#### Video iOS SDK

TwilioVideo 2.0.1 via CocoaPods

#### Xcode

9.3

#### iOS Version

iOS 11.2.5

#### iOS Device

Especially iPhone7Plus.

I test using iPhone8, iPhone7Plus, iPhoneSE, iPhoneX

The performance rank is like below(My feeling). It is sorted by good Performance

`iPhone8 > iPhoneX > iPhoneSE > iPhone7Plus`

Thank you. 

Kei

**Comment by piyushtank** [comment]
@kboy-silvergym  Thanks for reaching out.

On iPhone 7 Plus, I ran our sample app [Quickstart](https://github.com/twilio/video-quickstart-swift/tree/master/VideoQuickStart) on time profiler. I ran bidirectional audio + video call for about 2 to 3 minutes. The main thread usage is around 5%. See the image below -

<img width="1438" alt="screen shot 2018-05-18 at 5 51 19 pm" src="https://user-images.githubusercontent.com/17037593/40263301-0d26f40a-5ac5-11e8-8648-47ba7c659e1a.png">

I would recommend taking a look at the [Quickstart](https://github.com/twilio/video-quickstart-swift/tree/master/VideoQuickStart) for the base performance.

Let me know if you have any questions.

**Comment by kboy-silvergym** [comment]
@piyushtank  Thanks! 

I will try to compare my app with the sample app. Then, I will tell you the result of comparison.

**Comment by kboy-silvergym** [comment]
@piyushtank 

I have figured out why my app's main thread is occupied by TwilioVideo!

In my code, `SceneView` (ARSCNView)  is passed into `TVIScreenCapturer`. 
Like this→ `let capture = TVIScreenCapturer(view: sceneView)` 

**This is the reason.** 

If I delete this code & stop to pass the capture into videoTrack, the main thread is not occupied so much 👍 

I'll share my code below.

```swift
    private var videoTrack: TVILocalVideoTrack?
    private var audioTrack: TVILocalAudioTrack?

    private let delegateQueue = DispatchQueue(label: "something")
    
    func connect() {
        let capture = TVIScreenCapturer(view: sceneView)
        let constraintsBuilderBlock = {(builder: TVIVideoConstraintsBuilder) -> Void in
            builder.maxFrameRate = 8
            builder.maxSize = CMVideoDimensions(width: 320, height: 240)
        }
        let constraints = TVIVideoConstraints(block: constraintsBuilderBlock)
        videoTrack = TVILocalVideoTrack(capturer: capture!, enabled: true, constraints: constraints, name: room.name)
        self.audioTrack = TVILocalAudioTrack()
        
        let block = { [weak self] (_ builder: TVIConnectOptionsBuilder) in
            guard let wSelf = self else {
                return
            }
            builder.videoTracks = [wSelf.videoTrack!]
            builder.audioTracks = [wSelf.audioTrack!]
            builder.roomName = wSelf.room.name
            builder.preferredVideoCodecs = [TVIH264Codec()]
            builder.delegateQueue = wSelf.delegateQueue
        }
        let options = TVIConnectOptions(token: room.accessToken, block: { (_ builder: TVIConnectOptionsBuilder) -> Void in
            block(builder)
        })
        
        tviRoom = TwilioVideo.connect(with: options, delegate: self)
    }
```

I want to make the SceneView's capture into videoTrack & share to the room,
but this code seems to be bad because the main thread is occupied.

So, could you give me some advice about how to capture the sceneView the best.

Thank you.

**Comment by piyushtank** [comment]
@kboy-silvergym Thanks for reaching out. Using screen capture for video is definitely not efficient.  Have you got a chance to take a look at our [ARKitExample](https://github.com/twilio/video-quickstart-swift/tree/master/ARKitExample)? It implements custom capturer which receives frames from `ARSCNView` and provides frame to SDK.  You should see some improvement with `ARKitExample` however, please note that `ARKitExample` is not optimized [[known issue](https://github.com/twilio/video-quickstart-swift/tree/master/ARKitExample#known-issues)]. We are planning to improve `ARKitExample` sample app's  performance in future by capturing pixel buffer(frames) using metal texture before the buffer is supplied to GPU.

Please let me know if you have any question.

**Comment by kboy-silvergym** [comment]
@piyushtank

 I have just used [ARKitExample](https://github.com/twilio/video-quickstart-swift/tree/master/ARKitExample) as a reference & tried to fix my issue.

**In conclusion, the performance has been better!**

But, because `CADisplayLink` for capturing should be repeated in the main thread, it still occupied the main thread. But I has tuned the CADisplayLink's fps & it has became better.

By using `TVIVideoCapturer` protocol, I can control the capturing process, so I will continue to optimize the capturing sceneView's capture on my app 💪

Thank you so much for the advices. This issue can be closed.

**Comment by ceaglest** [comment]
Awesome, I'm glad to hear things are working well! 

Closing the issue.
