### ISSUE TITLE
NSInternalInconsistencyException Invalid parameter not satisfying: device

### ISSUE THREAD

**Issue by wmonk** [twilio/twilio-video-ios#104]
> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x).
> 
> If this is an issue with the QuickStart itself, file it here. If this is an issue with the SDK or how to do something with the SDK please use [twilio-video-ios](https://github.com/twilio/twilio-video-ios/issues) instead.
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

Sentry is reporting exception:
```
NSInternalInconsistencyException
Invalid parameter not satisfying: device
```

We're running a few hundred to a thousand video calls per day, and this is popping up on average 2-3 times per day. The weird thing is, it's reporting calls to `TVICaptureOrientationMetadataForVideoOrientationAndCameraPosition`, which we aren't using directly in our codebase. I'm also unable to see an references to this on docs or even through google, apart from https://github.com/twilio/video-quickstart-ios/issues/303. Is there some underlying call, that in turn calls this method? We are using objc, not swift, for our integration.

### Steps to Reproduce

1. Unsure

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

Video works

#### Actual Behavior

App crashes

#### Reproduces How Often

~1%

#### Logs

No logs available

### Versions

All relevant version information for the issue.

#### Video iOS SDK

TwilioVideo (~> 3.2.3) via Cocoapods

#### Xcode

11.4.1

#### iOS Version

12.*
13.*

#### iOS Device

iPhone 7 
iPhone 8 
iPhone 11 
iPhone XR
iPhone 7 Plus
iPhone 11 Pro Max
iPhone XS Max
iPhone X
iPhone 6s
iPad mini

**Comment by wmonk** [comment]
To add, the only places I can see in our integration the calls with argument `device` are:

`TVICameraSource startCaptureWithDevice:device` (we always check device is not nil)
`TVICameraSource selectCaptureDevice:device` (we always check device is not nil)

**Comment by wmonk** [comment]
Is this something to take up with Twilio support?

**Comment by wmonk** [comment]
@piyushtank any updates on this?

**Comment by piyushtank** [comment]
@wmonk Apologies for the delayed response. We do not throw NSInternalInconsistencyException, its probably coming from iOS as a result of incorrect API calls. Can you provide more information on stack trace or logs? If you are not comfortable posting logs here, please open a support ticket or send it to me directly at ptank@twilio.com

**Comment by piyushtank** [comment]
Closing an old ticket. Feel free to reopen or create a new ticket if you are still having an issue.
