### ISSUE TITLE
how to share share screen content in app or other apps also bellow iOS 12.0 

### ISSUE THREAD

**Issue by dsngeu** [twilio/twilio-video-ios#105]
we are using RPSystemBroadcastPickerView its working fine, but problem is that it does have support bellow iOS 12.0.
and in our app we support iOS version 10.0 and above. 

so how can I share in app or other apps screen content bellow iOS 12.0.?

Currently we are using pod 'TwilioVideo', '~> 3.2' and Broadcast Extension for sharing.

**Comment by ceaglest** [comment]
Hi @dsngeu,

> so how can I share in app or other apps screen content bellow iOS 12.0.?

RPScreenRecorder works in iOS < 12.0 but it can only share in-app content. It's demonstrated in our ReplayKitExample.

> we are using RPSystemBroadcastPickerView its working fine, but problem is that it does have support bellow iOS 12.0.

In iOS 11.0 your users can start sharing the screen from control center and select your extension.

Best,
Chris

**Comment by ceaglest** [comment]
Please let me know if you need any more help with screen sharing.
