### ISSUE TITLE
TwilioVideo asks for microphone when there is no LocalAudioTrack

### ISSUE THREAD

**Issue by nikolausWest** [twilio/twilio-video-ios#110]
### Description

TwilioVideo seems to try to use microphone when we have only set up a `LocalVideoTrack` and no `LocalAudioTrack`. For us this crashes the app for some users (seems to be related to corporate managed configuration) because we haven't asked permission to use the microphone. 

### Steps to Reproduce

1. iOS app that only publishes a `LocalVideoTrack` by implementing the `VideoSource` protocol.
2. App only asks for camera permissions via info.plist
3. Run app and try to connect to a peer-to-peer room on a phone with a corporate managed configuration

#### Code

```swift
let options = ConnectOptions(token: accessToken, block: { (builder) in
            if self.videoTrack != nil {
                builder.videoTracks = [self.videoTrack!]
            }
            builder.audioTracks = []
            builder.roomName = self.roomName
        })
```

#### Expected Behavior
I expect not to have to ask permission to use the microphone when I'm not publishing any audio.

#### Actual Behavior
App crashes (on some phones) with `__CRASHING_DUE_TO_PRIVACY_VIOLATION__` and message:
"TCC, This app has crashed because it attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data."

#### Reproduces How Often
This happens repeatedly for about 5% of our users.

#### Logs
The crashes have only happened on users devices so I don't know what to put here

### Versions

All relevant version information for the issue.

#### Video iOS SDK

TwilioVideo 3.2.5 via cocoapods

#### Xcode

11.5

#### iOS Version

13.5

#### iOS Device

iPhone 11 Pro

**Comment by nikolausWest** [comment]
@piyushtank I still keep getting this crash. Any idea if it's possible to force the sdk not to create an AVAudioSession?

**Comment by piyushtank** [comment]
@nikolausWest Apologies for the late response.

Our current implementation of DefaultAudioDevice initializes AudioUnit for record+playout by default. Unfortunately its current implementation doesn't allow configure DefaultAudioDevice for playout only use case. We plan to provide such APIs in future on DefaultAudioDevice.

In the meantime, I recommend writing your own custom audio device. Here are the [examples](https://github.com/twilio/video-quickstart-ios/tree/master/AudioDeviceExample) of custom audio device. If your app will not have a need for microphone at all in a live call, we have a [playout only audio device example](https://github.com/twilio/video-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleCoreAudioDevice.m) which you can use as is in your app.

Let me know if you have any questions.

**Comment by nikolausWest** [comment]
Thanks alot @piyushtank ! Will give the "playout only audio device" a try!

**Comment by deadmanIsARabbit** [comment]
@nikolausWest  i came across the same issue.
In my case i had disabled the audio track in the iOS App but requested the local audio track in a browser with the JS client. Which caused a crash in the iOS App.
What helped was to disable the local audio track in the browser.

Maybe this information can help you somehow.

**Comment by nikolausWest** [comment]
Apologies, forgot to let you know how it went. The  "playout only audio device" fixed the issue for me. Thanks for the help!
