### ISSUE TITLE
How can we disabled audio/video track while connecting?

### ISSUE THREAD

**Issue by Balasnest** [twilio/twilio-video-ios#111]
1. How can we disabled audio/video track while connecting?

Step to reproduce:
1. Connect to room
2. Disable video track immediately after connect
3. In web twilio js, track for video event is coming but disabled one is not trigged for other opponent.

Do we have anything similar to web in native SDK which can disable track while connecting?
```
Video.connect(videoAccessToken, {
        name: videoRoomId,
        audio: false,
        video: false,
        ...
      })
}
```

How can I disabled video track at the creation time, then later create video track and set with builder if user wants to enable?
```
builder.videoTracks = disableVideo ? @[ ] ; @[ self.localVideoTrack ] ;
// Now how should we assign the video tracks later while in call ?
```

**Comment by Balasnest** [comment]
@paynerc Can you help me here.

**Comment by PPacie** [comment]
Hi @Balasnest,

Just avoid setting the `builder.videoTracks` and `builder.audioTracks` at the moment of creating the `ConnectOptions`. 
Later, once your user is connected to the Twilio room, you can use your `room` object to add your local audio/video tracks. (You don't need to use the builder/ConnectOptions anymore).

Something like that:

```
room.localParticipant?.publishAudioTrack(yourLocalAudioTrack)
room.localParticipant?.publishVideoTrack(yourLocalVideoTrack)
```

Hope it can help you.

**Comment by paynerc** [comment]
@Balasnest,

As @PPacie stated above, you can publish audio and video tracks after connecting via the `LocalParticipant.publish[Audio|Video]Track` methods.

This was also asked in https://github.com/twilio/video-quickstart-ios/issues/518 and has been marked as closed, so I will close this issue as well.

Ryan
