### ISSUE TITLE
Get Audio Level of Participants

### ISSUE THREAD

**Issue by devin-garg** [twilio/twilio-video-ios#120]
Hello,

How do you get the audio level of participants on a video call (how loud someone is) as I have a RemoteAudioTrack? On web sdk for Twilio video you can get the audio tag itself and check the audio level from there using an analyzer.

**Comment by ceaglest** [comment]
Hey @devin-garg,

We don't have a Track API for volume but one way to accomplish the same thing is to call `-[Room getStats:]` and then inspect each [RemoteAudioTrackStats](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIRemoteAudioTrackStats.html) object's [audioLevel](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIRemoteAudioTrackStats.html#//api/name/audioLevel) property.

Best,
Chris

**Comment by devin-garg** [comment]
Sounds good @ceaglest will do that in the meantime. I would support a feature request of this. Thanks for your help.

**Comment by devin-garg** [comment]
@ceaglest this give stats for remouteaudio, could I get audiolevel for localparticipant?

**Comment by ceaglest** [comment]
Yes you can using [LocalAudioTrackStats.audioLevel](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVILocalAudioTrackStats.html#//api/name/audioLevel). It will be part of the same stats reports as remote tracks.

**Comment by devin-garg** [comment]
Sounds good @ceaglest , how do I match from the stats report to remoteparticipants as I can get the audio level but do not know how to match audiolevel to a remoteparticipant? I do have participant.identity assigned to each remote participant.

**Comment by ceaglest** [comment]
You can match based upon the Track SIDs with [BaseTrackStats.trackSid](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIBaseTrackStats.html#//api/name/trackSid).

**Comment by devin-garg** [comment]
Gotcha, will cross-reference trackSid with participants in the room. Thanks.

**Comment by shai-caazam** [comment]
Hi @ceaglest,

We were expecting the `audioLevel` in the stats reports to be gain of audio channel - between 0 to 1 - like in WebRTC [stats definition](https://www.w3.org/TR/webrtc-stats/#dom-rtcaudiosourcestats) - or volume in AVCaptureAudioChannel in iOS SDK.
The actual values we are receiving are all over the place (78, 10285, 23524, 12, 923) and we are unsure what the units and ranges for these values are.

**Comment by ceaglest** [comment]
Hi @shai-caazam,

The range is the amplitude of a signed 16-bit number, so between 0 and 32,767 instead of 0 to 1.

Best,
Chris

**Comment by marcato15** [comment]
How expensive is the `getStats` operation? We are wanting to show an audio indicator for a VOIP app and so will need to run it probably every 500 ms. Is there a potential for this to introduce a significant amount of lag?

**Comment by marcato15** [comment]
Is that call to `getStats` on the room expensive? We'd like to show an audio indicator to show when someone is speaking, but I'm worried that running that every 500 ms will introduce lag.

**Comment by ceaglest** [comment]
Hi @marcato15,

The call can be expensive because it requires synchronization with components of the media pipeline in order to gather stats. I wouldn't recommend calling it more often than every second at this point. Future releases will improve performance of stats gathering since they will use the W3C standardized stats APIs internally.

Best,
Chris

**Comment by marilynnElHossry** [comment]
Hi @ceaglest  ! I want to track the local participant's audio level and send it via DataTrack to sort users based on who is speaking the longest. Can you explain the approach described here better? Is there a listener that can be added to the local participant's audio track?
and please what the range of the audio level because when using room.getStats the value is increasing to 3000 sometimes
