### ISSUE TITLE
Simulcast with custom camera source

### ISSUE THREAD

**Issue by simbara** [twilio/twilio-video-ios#125]
### Description

We use a custom camera source instead of the default TVICameraSource. Everything works well but it seems that simulcast isn't working. If the default camera is used we can see lower resolution dimensions on the stats view. But using the custom camera the dimensions don't change even in very bad network conditions. 

The documentation and sample code show that codec/simulcast settings created with connectoptions builder are applied at Room-connect time. So it is not clear which if any of the codec/simulcast settings need to be applied during camera setup.

Is it possible to enable simulcast with a custom camera source. Is there a particular format or setting that needs to be done at setup?

### Versions

All relevant version information for the issue.

#### Video iOS SDK

3.4.1 via CocoaPods

#### Xcode

11.6

#### iOS Version

13.6

#### iOS Device

iPhone 8, iPhone 11

**Comment by ceaglest** [comment]
Hi @simbara,

> The documentation and sample code show that codec/simulcast settings created with connectoptions builder are applied at Room-connect time. So it is not clear which if any of the codec/simulcast settings need to be applied during camera setup.

The codec settings provided at connect time are used for all video tracks that you publish.

> Is it possible to enable simulcast with a custom camera source. Is there a particular format or setting that needs to be done at setup?

Yes, you can choose wether to treat your custom VideoSource content as either screen or regular video content using `-[TVIVideoSource isScreencast]`. As of 4.0.0 our SDK supports simulcasting of either screen or normal video content using VP8.

- [TVIVideoSource.screencast](https://twilio.github.io/twilio-video-ios/docs/latest/Protocols/TVIVideoSource.html#//api/name/screencast)

Best,
Chris
