### ISSUE TITLE
Controlling volume of individual participants?

### ISSUE THREAD

**Issue by farzaa** [twilio/twilio-video-ios#129]
Hello! I'm building an app where one person will be "on stage" and everyone will hear this person at 100% volume. But, people in the "audience" would not be muted, rather, the volume everyone hears them at would just be set to 20%.

But, if needed, the person on stage can can increase any audience members volume at will so that if they set an audience member to 100%, everyone hears that audience member at 100% volume.

I don't see a way to control individual incoming audio tracks on iOS! What's the simplest way to achieve this?

**Comment by piyushtank** [comment]
@farzaa - Thanks for reaching out.

There is no direct way to set volume of each participant on play out side as the all participant's audio is mixed prior to delivering it to the play out, however at the audio capturing side you may be able to achieve this by configuring the microphone volume on AudioUnit - I personally haven't tried this but it should be possible. You will have to write your own custom audio device to achieve this.

Next is when you have a call going changing volume for one participant on the fly - I am not sure if AudioUnit supports this out of the box, but there might be API to do this.

Our custom audio device example - https://github.com/twilio/video-quickstart-ios/tree/master/AudioDeviceExample

Let me know if you have any questions.

**Comment by farzaa** [comment]
Thanks @piyushtank, will look into this now and come back with results within a few days 👍 :).

**Comment by piyushtank** [comment]
Closing an old ticket but feel free to reopen this or file another ticket if you run into any issues.
