### ISSUE TITLE
TVIRoom delegate property is readonly, but can be initialized with no delegate

### ISSUE THREAD

**Issue by andschdk** [twilio/twilio-video-ios#13]
I am currently trying to take a completely reactive approach to an implementation of a video chat. I am extending twilio with RX using the same approach as `RxCocoa` using [DelegateProxy](https://github.com/ReactiveX/RxSwift/blob/master/RxCocoa/Common/DelegateProxyType.swift). This means that the delegate is set whenever someone subscribes. If there are multiple subscribers the delegate is shared. Whenever there is no more subscribers the delegate is deinitialized. For this approach to work one is depending on a delegate that can be set (write) which is common in the standard way of implementing the delegate pattern on iOS.

My problem is that this is not possible in `TwilioVideo` because of the `delegate` property in `TVIRoom`.
```objc
@property (nonatomic, weak, readonly, nullable) id<TVIRoomDelegate> delegate;
```
What are the reason for keeping the `TVIRoomDelegate` property `readonly` while still being `nullable`/optional?

The factory method for creating a `TVIRoom` also accepts an optional delegate, but one is not able to set it later because of the `readonly` delegate prop.
```objc
+ (nonnull TVIRoom *)connectWithOptions:(nonnull TVIConnectOptions *)options  delegate:(nullable id<TVIRoomDelegate>)delegate;
```

I will be able to find workarounds for this, however I thought I would mention this as it might be due to a coincidence that the property ended up as `readonly` while still being able to initialize a room without a delegate.

**Comment by ceaglest** [comment]
Hey @andschdk,

> What are the reason for keeping the TVIRoomDelegate property readonly while still being nullable/optional?

This is a good question. Originally, the reason for keeping the delegate as readonly was to make our implementation simpler and reduce API surface area. However, since the delegate is weak it can be nil'd out at any time so that argument is not terribly convincing.

> The factory method for creating a TVIRoom also accepts an optional delegate, but one is not able to set it later because of the readonly delegate prop.

Honestly, I would prefer to to accept a nonnull delegate in the factory method to keep the API contract simpler. However, it sounds like this wouldn't help if your intention is to set the delegate only when its needed.

Making the delegate property read/write would be a non-breaking change. Let me learn a little more about your use case and chat with the rest of the iOS team members on this one.

Best,
Chris

**Comment by andschdk** [comment]
Hi @ceaglest,
Thank you for the quick reply.

Not taking my use case into consideration I still believe that the delegate should follow common practice. It might not seem as simple as enforcing/providing the delegate in the factory method, but considering that most iOS developers are used to how delegates work (set at any time after init) it should still be a simple API to understand. Additionally all other public delegates (as far as I know) work the same way in the rest of the TwilioVideo framework.

I guess there can be cases where one need to invoke some kind of callback during init. Let that be fail because of bad token syntax or any other input validation performed on the main thread. In this case I still believe that delegate injection (or forcing it as param in a factory) is not the perfect choice. Here a _failable_ initializer or closure/block might be at better fit. 

Anyway, thank you so much for considering this. If you need anything from me just ping me here and I'll check back.

Thanks.

**Comment by ceaglest** [comment]
Hey @andschdk,

You make some very good points. After discussing with the team we've decided to go ahead and make `Room.delegate` a read/write property.

Expect this to land in our 2.2.0 release.

Best,
Chris

**Comment by andschdk** [comment]
Thanks @ceaglest,
Looking forward for the release.

**Comment by paynerc** [comment]
As of the `2.2.0` release, which shipped last night, the `Room.delegate` property is now read/write.

Let us know if you have any further issues with this. Thanks!

Ryan

**Comment by andschdk** [comment]
Thanks, just updated the sdk and updated/removed my current work around. It seems like it works like it should 👍 
Again, thanks for changing this. Much appreciated.
