### ISSUE TITLE
The issue with sockets and "Method of dominant speaker"

### ISSUE THREAD

**Issue by igorperekhrest** [twilio/twilio-video-ios#131]
Hi, everyone! We would be grateful if anyone can help us solve the issues we are facing on the project using Twilio videos:

1. The user (video call participant) disconnects due to low internet connection/loss of internet connection/crashes:

1) The users connected to the video meeting.
2) Some of the participants lost the internet connection or the app was crashed.
3) Then, when this user reconnected to the video, Twilio sends two sockets for all users:
- connected
- disconnected
Based on the order of the sockets, the other users don't see the user on the meeting that previously was crashed or lost the internet connection.
But if the order of sockets will be reversed:
- disconnected
- connected
Everything should work correctly.

But, we didn't find any solution to affect this behavior.
__________________________________________________________________________

2. Also, we faced two issues with the "method of the dominant speaker":
1) Crashes
2) Video Flickering

Here we are setting a video track:
Private var mainVideoTrack: VideoTrack? {
    didSet {
      DispatchQueue.main.async { [weak self] in
        self?.delegate?.showVideoTrack(self?.mainVideoTrack, old: oldValue)
      }
    }
  }

Method of the dominant speaker:
func showVideoTrack(_ track: VideoTrack?, old: VideoTrack?) {
    lock.lock()
    if let speechView = self.speechView {
      speechView.removeFromSuperview()
    }
    if track != nil {
      if !(old?.renderers.isEmpty ?? true) {
        old?.removeRenderer(videoView)
      }
      track?.addRenderer(videoView)
    }
    self.videoView.isHidden = false
    self.videoView.contentMode = .scaleAspectFill
    lock.unlock()
  }

1. Crashes:
We often faced with the crashes of the "method of the dominant speaker"
Here is the info from the crashlytics:

Fatal Exception: NSInternalInconsistencyException
Invalid parameter not satisfying: adapter.videoRenderer != renderer
DiscussionStreamViewController.showVideoTrack(_:old:)
keyboard_arrow_down

Please help us to understand, why this issue happened and how we can fix it? 

2. During user switching when they speak, we always see black screen video flickering and it looks bad.
We tried to investigate this point and found that Twilio has a pause during switching one user to another. But we need to display for a few seconds one user after he finishes talking to another without any flickering so that users can only see the video.

So, please clarify, how can we affect this behavior, due to we didn't find any solution to solve this issue? We faced a lot of complaints from our user and we need to update this behavior asap.

Thank you to everyone who will try to help us to find solutions to this issue.

**Comment by ceaglest** [comment]
Hi @igorperekhrest,

Sorry for the late response. 

This assertion occurs when you add a TVIVideoRenderer to a VideoTrack twice. To solve the problem, you must balance calls to addRenderer and removeRenderer.

Best,
Chris
