### ISSUE TITLE
Duplicate symbols when linking static lib

### ISSUE THREAD

**Issue by julien-l** [twilio/twilio-video-ios#137]
### Description

Xcode complains about duplicate OpenSSL symbols when linking my executable:

```
ld: warning: duplicate symbol '_CONF_parse_list' in:
    /Users/julien/work/packages/.../openssl/1.1.1g/lib/libcrypto.a(conf_mod.o)
    /Users/julien/work/stage/.../twiliovideo/3.7.0/lib/libTwilioVideo.a(conf.o)
```

### Steps to Reproduce

Have a project depending on both OpenSSL and `libTwilioVideo.a`:

```
Project -------------> OpenSSL
    |                      ^
    |                      |
    +----> TwilioVideo ----+
```

Link command (simplified):

```
clang++ -target arm64-apple-ios11.0 -isysroot /path/to/iPhoneOS14.0.sdk
    /path/to/twiliovideo/3.7.0/lib/libTwilioVideo.a
    /path/to/openssl/1.1.1g/lib/libssl.a
    /path/to/openssl/1.1.1g/lib/libcrypto.a
    -o app
```

### Expected behaviour

Symbols that are not part of Twilio's API like openssl should be hidden to avoid naming collisions in end-user's project.

#### iOS SDK

Tried with `libTwilioVideo.a` version 3.7.0 downloaded from GitHub.

#### Xcode

Xcode 12.0.1
Build version 12A7300

**Comment by ceaglest** [comment]
Hey @julien-l,

Thanks for reaching out to file an issue.

> Symbols that are not part of Twilio's API like openssl should be hidden to avoid naming collisions in end-user's project.

I agree that this would be an improvement, but unfortunately our internal use of boringssl (via libWebRTC) is not prefixed at this time.

> Tried with libTwilioVideo.a version 3.7.0 downloaded from GitHub.

Would it be possible to consume our dynamic framework instead? This would eliminate the possibility for C symbol conflicts, and we've also renamed Objective-C classes from WebRTC to prevent runtime conflicts.

Best,
Chris

**Comment by julien-l** [comment]
Hi @ceaglest,

> Would it be possible to consume our dynamic framework instead?

Yes this is what I do for now and this is working. I wanted to switch to the static library to simplify my build process (because I don't use a dependency manager like Cocoapods).

I just wanted to show my interest. I hope it will make it in a future release.

Thanks for your quick answer!
