### ISSUE TITLE
Crash on trying create CameraSource(delegate: self)

### ISSUE THREAD

**Issue by DmytroK-iOS** [twilio/twilio-video-ios#139]
[Description of the issue]
Get crash on create camera = CameraSource(delegate: self)
using libTwilioVideo.a
Permissions for microphone & video granted

+[UIApplication tvi_statusBarOrientation]: unrecognized selector sent to class 0x1ecd260e0
2020-10-21 18:59:48.285193+0300 App[2445:1282112] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[UIApplication tvi_statusBarOrientation]: unrecognized selector sent to class 0x1ecd260e0'

### Steps to Reproduce

1. Copy code from Video quick start application ( in twilio demo )
2. One ViewController application
3. camera: CameraSource?
ViewDidLoad {
     camera = CameraSource(delegate: self)  <-  get crash
}

#### Code
func startPreview() {
        if PlatformUtils.isSimulator {
            return
        }

        let frontCamera = CameraSource.captureDevice(position: .front)

        if (frontCamera != nil) {
           //Crash there:
           camera = CameraSource(delegate: self)
        }
        ...

#### Expected Behavior
Init class TVIVideoSource 

#### Reproduces How Often
100% 

[What percentage of the time does it reproduce?]
100% 

#### Logs
Metal GPU Frame Capture Enabled
Metal API Validation Enabled
+[UIApplication tvi_statusBarOrientation]: unrecognized selector sent to class 0x1ecd260e0
2020-10-21 18:59:48.285193+0300 App[2445:1282112] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[UIApplication tvi_statusBarOrientation]: unrecognized selector sent to class 0x1ecd260e0'
*** First throw call stack:
(0x18f8825ac 0x1a38fc42c 0x18f791324 0x18f885130 0x18f887420 0x104dfb914 0x104dfbae4 0x104df3c58 0x104e10a64 0x104a86b70 0x104a86b38 0x104a86490 0x104a82e7c 0x104a8372c 0x191a9d678 0x191aa1e14 0x191aa21d8 0x1921dd424 0x1921dcbf8 0x1921ddac8 0x1921eed44 0x19240d2cc 0x19166bf84 0x19219e1f0 0x19219e578 0x191cb8274 0x19e8342dc 0x19e85ea00 0x19e842d24 0x19e85e6d0 0x1068095f0 0x10680ce70 0x19e8860e0 0x19e885d88 0x19e8862ac 0x18f7ff81c 0x18f7ff718 0x18f7fea94 0x18f7f8d20 0x18f7f84bc 0x1a627d820 0x19219c734 0x1921a1e10 0x1a2c346ec 0x104a58058 0x104a57fd4 0x104a5809c 0x18f4bfe60)

### Versions

All relevant version information for the issue.

#### Video iOS SDK
libTwilioVideo.a
MetalKit
Audio ToolBox
Video ToolBox
AVFoundation
CoreTelephony
GLKit
CoreMedia
SystemConfiguration
libc++.tbd
all Headers [TwilioVideo.h ... ]

installed manually

**Comment by paynerc** [comment]
@DmytroK-iOS,

My initial thought is that you don't have `-ObjC`  set in ` Other Linker Flags` therefore the categories we define in the SDK are not being linked into your application.

Ryan

**Comment by DmytroK-iOS** [comment]
Thx a lot! Worked for me.
