### ISSUE TITLE
Can not add 4.0.0 using Swift Package Manager 

### ISSUE THREAD

**Issue by jigar007** [twilio/twilio-video-ios#140]
I'm using Xcode Version 12.1 (12A7403), before the release of 4.0.0-beta2 it was working fine with 4.0.0-beta1, but now I can not add 4.0.0-beta2 using SPM.

<img width="775" alt="Screen Shot 2020-10-31 at 5 59 47 pm" src="https://user-images.githubusercontent.com/9298974/97773427-ba0d8700-1ba3-11eb-88a1-eafed0ec6fc6.png">
<img width="737" alt="Screen Shot 2020-10-31 at 6 00 42 pm" src="https://user-images.githubusercontent.com/9298974/97773431-c265c200-1ba3-11eb-89e7-0f03e87ff387.png">

**Comment by paynerc** [comment]
@jigar007,

I'm sorry to hear that you are having issues consuming `4.0.0-beta2`. When consuming a version that doesn't strictly adhere to SemVer (such as having the `-beta2` suffix), it's best to use an Exact version match rule:

![image](https://user-images.githubusercontent.com/25950/97879648-3ad89a00-1cee-11eb-9484-0b045ae7b1f0.png)

After that is set, you can update the dependency by selecting the `File` -> `Swift Packages >` -> `Update to Latest Package Versions` menu item. If you are still seeing the above error, you can first try the `File` -> `Swift Packages >` -> `Reset Package Caches` menu item and it should clear things up.

![image](https://user-images.githubusercontent.com/25950/97879999-9dca3100-1cee-11eb-8996-d048117a62b0.png)

Please let me know if you are still having issues after trying those steps.

Thank you, 

Ryan

**Comment by apersaud** [comment]
I had this issue when I first added the SPM. After I added it, I closed XCode, deleted DerivedData, opened XCode (workspace), selected "Swift -> Update to Latest Packages", waited until SPM was done, then did a build.

I was using 4.0.0 (not beta)

**Comment by paynerc** [comment]
@jigar007 @apersaud 

Have you successfully been able to consume TwilioVideo iOS via SPM?

Ryan

**Comment by paynerc** [comment]
I am going to close this ticket. Please feel free to reopen this issue if you are still experiencing issues.

Ryan

**Comment by apersaud** [comment]
I have not been able to use TwilioVideo SPM when archiving. I have reverted back to using Cocoapods. The issue above still persists.

**Comment by paynerc** [comment]
@apersaud,

What happens when you archive? Is it similar to this issue, #152?

Ryan

**Comment by apersaud** [comment]
Actually just adding the package through SPM provides this error:
![Screen Shot 2021-01-19 at 8 56 24 AM](https://user-images.githubusercontent.com/127068/105067348-756fea00-5a34-11eb-8c2c-be5d47807e82.png)

**Comment by paynerc** [comment]
@apersaud,

Have you tried resetting the package caches as described above and also doing a clean of the project in Xcode?

Ryan

**Comment by paynerc** [comment]
@apersaud,

Also, the 2 unhandled files sounds like an issue that was there with one of our beta versions. That has since been resolved before the `4.0.0` release. The latest release is `4.1.0` and it should no longer have that error.

Ryan

**Comment by apersaud** [comment]
Thanks, it works now - however archiving produces the previous error:
![Screen Shot 2021-01-19 at 9 51 11 AM](https://user-images.githubusercontent.com/127068/105073500-00a0ae00-5a3c-11eb-904d-8339e31fc338.png)

However, this issue can be closed if the Mach-O is being tracked as #152. Thanks.

**Comment by paynerc** [comment]
@apersaud,

That screen looks like it's related to #152, but the message is a little bit different. When you look at your project build phases, do you other copy file phases in there? There is an issue with Xcode that for every copy phase, it also copies any binary swift packages to that location in the project. In the case of the person reporting #152, they have a notification service extension along side their app and when they copy it to the Plugins folder, it brings an extra copy of TwilioVideo.framework into that folder as well. I have filed a bug report with  on this issue and the work around is to add a run script phase after the copy phase to remove the duplicate framework in the .app bundle. I am not sure if this is also affecting your case.

Ryan
