### ISSUE TITLE
H.264 - Corrupted image after network handoff

### ISSUE THREAD

**Issue by ceaglest** [twilio/twilio-video-ios#147]
Ahoy!

Twilio Video iOS 4.0 upgrades the version of libWebRTC to 83. While this release includes many improvements to modernize the Video SDK, there is a known issue that can cause image corruption when the H.264 video codec is used in Peer-to-Peer or WebRTC Go Rooms.

### Scenario

**Alice**: Safari, Safari Mobile, or the iOS Video SDK.
**Bob**: iOS Video SDK 4.x.
**Room**: Peer-to-Peer or WebRTC Go
**Reproducibility**: 40%

1. Alice connects with a video track, and prefers H.264.
2. Bob connects and subscribes to Alice’s video.
3. Later on Alice experiences a connectivity loss while switching networks.

#### Expected

1. Bob can see Alice’s video.

#### Actual

1. Bob might see corrupted video frames from Alice.
2. If image corruption occurs, the problem typically resolves within 30 - 40 seconds.

![artifacts-recording-crop-scale-16s](https://user-images.githubusercontent.com/1302577/101079948-0100ea80-355d-11eb-8fc2-9ac920bfcdf8.gif)

### Recommendations

1. Monitor this page for an updated SDK release that resolves the issue.
2. Publishers can prefer VP8 instead of H.264 until the bug is resolved.

```.swift
let connectOptions = ConnectOptions(token: accessToken) { (builder) in
    builder.preferredVideoCodecs = [ Vp8Codec() ]
}
room = TwilioVideoSDK.connect(options: connectOptions, delegate: self)
```

### Additional Resources

We are working with the community to resolve this issue in libWebRTC. Once available, the fix will be required for subscribers using downstream projects like the Twilio Video iOS SDK, Safari and Safari Mobile.

- WebRTC [Issue 12228](https://bugs.chromium.org/p/webrtc/issues/detail?id=12228)

**Comment by markmadlangbayan** [comment]
Hi @ceaglest, I see that this is tagged to 4.0 milestone.   Is there an approximate date?  We're still on 3.x as we rely on H.264.  Thanks!

**Comment by ceaglest** [comment]
Hi @markmadlangbayan,

Our upcoming release with Apple Silicon simulator support is based upon WebRTC m88. I will retest to see if this issue is resolved there. At this point it is likely that the root cause needs to be fixed in the libwebrtc, or the decoder implementation patched to disallow the bad bitstreams with gaps.

As the next step, I will let you know if the issue will be fixed in an upcoming 4.x release or not.

Thanks,
Chris
