### ISSUE TITLE
Difference between Publish methods returning BOOL an delegate callback methods

### ISSUE THREAD

**Issue by andschdk** [twilio/twilio-video-ios#15]
Hey, this is more a "help-wanted" issue.

`- (BOOL)publishVideoTrack:(nonnull TVILocalVideoTrack *)track` and similar methods (video/audio/data) on `TVILocalParticipant` all return _BOOL_ indicating success
> @return `YES` if the track was unpublished successfully, `NO` otherwise.

On the other hand we have the `TVILocalParticipantDelegate` methods for indicating success
`- (void)localParticipant:(nonnull TVILocalParticipant *)participant publishedVideoTrack:(nonnull TVILocalVideoTrackPublication *)publishedVideoTrack`
> @brief Delegate method called when the Local Participant successfully publishes a video track.

I would like to know the difference between the two. I assume that the returned _BOOL_ will only be *NO* if some precondition is not met (i.e. room not connected anymore or similar). While the delegate method is invoked if there is a problem contacting the server.

If my assumptions are correct I guess the returned _BOOL_ can be _YES_ and the delegate error callback could be invoked afterwards.

Also if the _BOOL_ returned is *NO* will the delegate error callback be invoked at all?

Looking forward for your comments on this.
Thanks.

**Comment by ceaglest** [comment]
Hi @andschdk,

Sorry for the delayed response.

> I would like to know the difference between the two. I assume that the returned BOOL will only be NO if some precondition is not met (i.e. room not connected anymore or similar). While the delegate method is invoked if there is a problem contacting the server.

That is correct, there are some preconditions which are checked synchronously. If the preconditions are met but negotiation with the signaling/media server fails then you will receive the failure delegate callback.

> If my assumptions are correct I guess the returned BOOL can be YES and the delegate error callback could be invoked afterwards.

Correct.

> Also if the BOOL returned is NO will the delegate error callback be invoked at all?

Yes, the delegate callback will not be invoked in this case.

Best,
Chris

**Comment by andschdk** [comment]
Hi @ceaglest,
Thank you for clarifying this. Much appreciated, thanks.
