### ISSUE TITLE
In Room some time the RemoteParticipants  return empty array and some time it return some value

### ISSUE THREAD

**Issue by AhmadDurrani579** [twilio/twilio-video-ios#150]
Hello Twilio Team From past few days i was stuck in this issue the remoteParticipants array return empty and some time it return some value can you please let me know why is this occuring 

Regards
Ahmad

**Comment by ceaglest** [comment]
Hi @AhmadDurrani579,

The `remoteParticpants` array does not include your own Participant, and is updated each time other Participants join or leave the Room. So, for example if you connect to an empty Room you should expect the array to be empty. 

Per the issue template - could you provide a Room SID where you had an empty `remoteParticipants` array but there were Participants in the Room?

Best,
Chris

**Comment by AhmadDurrani579** [comment]
Hello @ceaglest 
Thank you for your reply 

RM1164d26a4d9a35de5bf54aa447c45008
RMea6ff0d49dd8c6b0e70537bdeb0edcb5
RM025c7bf43ab36dd22fdcac4d885754e5 ---- 2 participants
RMd0df6642ef71675d8a2ad3d87c8c47c3
RMcea148085eaba97ffc887657912076bf
RMf68ef0b5fa8bfdb7ddec000af794a153
RM597f11395b6becde533422196ef0dcda

Please check the above Room  SID only 1 Room SID have 2 participants 

Regards
Ahmad

**Comment by AhmadDurrani579** [comment]
Let suppose i am joining the above room what will i get participant array have some value not the empty array sir

**Comment by AhmadDurrani579** [comment]
Recently i create the room  in here in one case the participant count is and in other 2 case its one 

RMf6254ee79b7ff2d9e4698080db8b6498
RMc452549e32960935aa40749182db6c0f -- 2 participants
RM348f95d61b91f1cb0571149c26966da3


Regards
Ahmad

**Comment by paynerc** [comment]
@AhmadDurrani579 

I've taken a look at these room sids:

- `RMf6254ee79b7ff2d9e4698080db8b6498` - There was only ever one participant in that room, `5fa6805cf2e8ca4c9cac3133`.
- `RMc452549e32960935aa40749182db6c0f` - Has two participants, `5fa681a3f2e8ca4c9cac3134` and `5fa6805cf2e8ca4c9cac3133`. When `5fa681a3f2e8ca4c9cac3134` connected to the room the remote participants collection would have been empty. When `5fa6805cf2e8ca4c9cac3133` joined the room, their remote participants collection should have had one entry for `5fa681a3f2e8ca4c9cac3134`.
- `RM348f95d61b91f1cb0571149c26966da3` - There was only ever one participant in that room, `5fa681a3f2e8ca4c9cac3134`.

One question that I have is when are you checking that remote participants collection? If you call it before the `TVIRoomDelegate didConnectToRoom:` delegate is invoked it will **always** be empty.

I hope that helps,

Ryan
