### ISSUE TITLE
Feature Request: Lite version of SDK to fit inside App Clips

### ISSUE THREAD

**Issue by marcato15** [twilio/twilio-video-ios#151]
With the release of App Clips in iOS 14 it’d be nice to offer a basic Video call feature in an App Clip. The uncompressed bundle size is required to be below 10 mb which means including just the current Twilio Video SDK is too big for an app clip. Is there a subset of functionality that could be provided in a lite version of the library to make a basic video call functionality available in an App Clip?

Either that or would it be possible to get access to the source code to build it ourselves?

**Comment by ceaglest** [comment]
Hi @marcato15,

App clip support would be a very nice feature to have. There is some discussion about the challenges, both for Twilio and the WebRTC community in [this thread](https://github.com/twilio/twilio-video-ios/issues/119#issuecomment-745542015).

Thank you for filing an issue to track interest in App Clips. Developers, if this is a use case you want please let us know.

Best,
Chris
