### ISSUE TITLE
ITMS-90680: Invalid Directory | Duplicate TwilioVideo.framework in PlugIns and Frameworks folders

### ISSUE THREAD

**Issue by SirWellington** [twilio/twilio-video-ios#152]
### Description

I am trying to upload a build to the App Store after adding TwilioVideo via spm. However, I am encoutering the following issue:

```
TwilioVideo.framework is not contained in a correctly named directory
```

It would appear that the Framework is getting added twice.

<img width="1112" alt="Screen Shot 2021-01-03 at 5 57 43 PM" src="https://user-images.githubusercontent.com/992646/103494798-2f3c4900-4ded-11eb-8de4-22648b75bf40.png">

Also when I open up the **.app** contents, I notice that the TwilioVideo.framework is contained in both the `Plugins/` and `Frameworks/` folders.

### Steps to Reproduce

1. Add TwilioVideo via SPM
2. Create an archive of your app
3. Attempt to upload the archive to the App Store

#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

I am able to export/upload to App Store Connect.

#### Actual Behavior

I see the error happening.

<img width="1112" alt="Screen Shot 2021-01-03 at 6 04 33 PM" src="https://user-images.githubusercontent.com/992646/103495032-25ffac00-4dee-11eb-83f9-aaef98067400.png">

#### Reproduces How Often

This happens all the time.

### Versions

All relevant version information for the issue.

#### Video iOS SDK

4.0.1 via SPM

<img width="592" alt="Screen Shot 2021-01-03 at 5 59 59 PM" src="https://user-images.githubusercontent.com/992646/103494887-817d6a00-4ded-11eb-8937-b91833d9cb60.png">

#### Xcode

<img width="642" alt="Screen Shot 2021-01-03 at 6 00 24 PM" src="https://user-images.githubusercontent.com/992646/103494895-8f32ef80-4ded-11eb-81ff-2bc2f1fd955f.png">

**Comment by paynerc** [comment]
@SirWellington,

I am attempting to reproduce this issue locally and am not seeing the issue. 

To test this I used the Twilio Video QuickStart application (https://github.com/twilio/video-quickstart-ios). I archived the application and then inspected the `.app` package in the Archive. I then prepared to distribute the application and only see one instance of the framework in the report.

![image](https://user-images.githubusercontent.com/25950/103566323-d376cc00-4e8f-11eb-8737-050dbf3b9566.png)

Are you new to using TwilioVideo as of the 4.x release or were you using a 3.x release in the past and switched to using the SPM distribution mechanism? I'm wondering if there are possibly some left over build settings in your project that could be causing this issue.

Would you be wiling to pull the QuickStart project listed above and try the process there to see if you are able to reproduce the issue with that?

Ryan

**Comment by SirWellington** [comment]
There was no previous 3.x release. We are just adding the 4.x release for the first time.

Let me give the sample project a try.

**Comment by SirWellington** [comment]
@paynerc 

I was able to reproduce the issue. It happens with Apps that have **NotificationServiceExtensions**.

**Steps to reproduce**
1. Taking the Video QuickStart application referenced above

2. Open the project file

<img width="1792" alt="Screen Shot 2021-01-04 at 8 45 01 PM" src="https://user-images.githubusercontent.com/992646/103607426-b95bde80-4ecd-11eb-93b9-21cd828f6866.png">

3. On the left-hand panel of the project (PROJECT + TARGET), click on the '+' sign to add a new target.

<img width="1792" alt="Screen Shot 2021-01-04 at 8 45 52 PM" src="https://user-images.githubusercontent.com/992646/103607472-d7294380-4ecd-11eb-85ad-2fcc265af75b.png">

4. Add a Notification Extension to the project with whatever name (i.e., `ServiceExtensionTest`)

<img width="1792" alt="Screen Shot 2021-01-04 at 8 49 07 PM" src="https://user-images.githubusercontent.com/992646/103607650-4c951400-4ece-11eb-9579-cd85f10ab2ff.png">

5. Click "Activate" if prompted.
<img width="435" alt="Screen Shot 2021-01-04 at 8 49 39 PM" src="https://user-images.githubusercontent.com/992646/103607692-60407a80-4ece-11eb-8392-62c74718e0e9.png">

6. Switch back to the QuickStart scheme.

<img width="289" alt="Screen Shot 2021-01-04 at 8 50 16 PM" src="https://user-images.githubusercontent.com/992646/103607728-751d0e00-4ece-11eb-868f-6a60fec1c380.png">

7. You will notice a new build phase was added: Embed App Extensions
<img width="1792" alt="Screen Shot 2021-01-04 at 8 50 30 PM" src="https://user-images.githubusercontent.com/992646/103607744-7e0ddf80-4ece-11eb-88b5-02c22b5cc323.png">

8. Now clean and build the project. Right click on the VideoQuickStart.app in the Products folder and click "Show in Finder"

<img width="1682" alt="Screen Shot 2021-01-04 at 8 51 35 PM" src="https://user-images.githubusercontent.com/992646/103607805-a4cc1600-4ece-11eb-89da-0d59c190ee7a.png">

If you analyze the structure of the generated app, you will now see that there is a TwilioVideo.framework in the PlugIns folder when there shouldn't be.

<img width="431" alt="Screen Shot 2021-01-04 at 8 52 59 PM" src="https://user-images.githubusercontent.com/992646/103607874-d5ac4b00-4ece-11eb-8161-2bb3597bcac9.png">

**Comment by paynerc** [comment]
Thanks for the reproduction steps. I will try this here shortly and see what we can do to mitigate this issue.

Ryan

**Comment by paynerc** [comment]
@SirWellington,

I have been able to reproduce this issue. This appears to be a bug with Xcode itself when consuming a SwiftPM binary distribution.

Looking at the `Embed App Extensions` build phase, it has no mention of `TwilioVideo.framework` in the files, yet it copies it anyways. Removing this build phase, obviously, eliminates the issue. I added a new copy file build phase and no matter what destination I select, it automatically copies `TwilioVideo.framework` to that location.

I will be filing a bug report with Apple with sample projects that show this issue. In the meantime I will do some more research to see if I can find a workaround. I have a couple ideas, nothing fantastic, but may be viable until Apple can fix this issue.

Ryan

**Comment by paynerc** [comment]
@SirWellington,

Well, it's not pretty, but I do have a workaround that should get you unblocked:

In the VideoQuickstart project's Build Phases, I did the following after I added the `ServiceExtensionTest`:

1. I moved the `Embed App Extensions` build phase to immediately follow the `Embed Frameworks` build phase.
2. I added a new `Run Script Phase` immediately following the `EmbedFrameworks` build phase. The contents of the script are as follows:

```
rm -rf "${CODESIGNING_FOLDER_PATH}/${BUNDLE_PLUGINS_FOLDER_PATH}/TwilioVideo.framework"
```

![image](https://user-images.githubusercontent.com/25950/103820486-73705900-503a-11eb-94e3-37f918a01ec0.png)

This will let Xcode do the wrong thing and copy the framework, then immediately removes it, and then signs the application.

I know it's ugly, but would you be willing to try this and let me know if that workaround does work for you?

Thank you,

Ryan

**Comment by SirWellington** [comment]
Thank you. This worked as a workaround 👍🏽

The manual integration option also worked.

**Comment by paynerc** [comment]
Just a followup on this one. I created Feedback FB8967517 with  this morning and included a test project that shows this issue, as well as provided a link to this issue for further information. When I hear anything, I will update this issue.

**Comment by mrkvans** [comment]
Solved -- with a workaround...

From the Xcode Archives screen, right-click on the file to be distributed and select 'show in finder' ... then, "show package contents" and navigate to the nested 'plugins' folder...

delete the "TwillioVIdeo.framework" folder inside the plugins folder.. it's identical to the one that is in the "Frameworks folder. 

this got me unstuck, should get you unstuck as well. 

Best of luck. 

(Stripe had this issue a few months ago -- the same workaround worked there as well)

**Comment by Armenm** [comment]
Thanks @paynerc for the workaround, it worked well.

I also had to add this line, as we have a Watch extension as well.
`rm -rf "${CODESIGNING_FOLDER_PATH}/Watch/TwilioVideo.framework"`

Couldn't find equivalent of `BUNDLE_PLUGINS_FOLDER_PATH` for Watch folder path.
