### ISSUE TITLE
Crash: EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000045596619c0c0

### ISSUE THREAD

**Issue by vdovichenko** [twilio/twilio-video-ios#154]
### Description

We constantly receive crashes on our live app. But I don't have steps to reproduce, only stack trace from Crashlytics

#### Stack trace

Crashed: Thread
0  TwilioVideo                    0x10812d8a0 boost::statechart::processor_container<connections::fsm::ConnectionScheduler, boost::function0<void>, std::__1::allocator<void> >::queue_event_impl(boost::weak_ptr<std::__1::auto_ptr<boost::statechart::event_processor<connections::fsm::ConnectionScheduler> > > const&, boost::intrusive_ptr<boost::statechart::event_base const> const&) + 104
1  TwilioVideo                    0x10812e66c boost::asio::detail::completion_handler<boost::function0<void> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) + 260
2  TwilioVideo                    0x108135d90 boost::asio::detail::strand_service::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) + 128
3  TwilioVideo                    0x108147f6c boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&) + 688
4  TwilioVideo                    0x108147afc boost::asio::detail::scheduler::run(boost::system::error_code&) + 204
5  TwilioVideo                    0x107f702e0 boost::asio::io_context::run() + 52
6  TwilioVideo                    0x107f71fa4 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, boost::_bi::bind_t<unsigned long, boost::_mfi::mf0<unsigned long, boost::asio::io_context>, boost::_bi::list1<boost::_bi::value<boost::asio::io_context*> > > > >(void*) + 64
7  libsystem_pthread.dylib        0x1d49b2b70 _pthread_start + 288
8  libsystem_pthread.dylib        0x1d49b7880 thread_start + 8

#### Video iOS SDK

3.7.1 via cocoapods

#### iOS Version

14.0.1
13.6.1
14.2.0

#### iOS Device

iPad Air 2
iPad (6th generation)
iPad Pro (10.5-inch)

**Comment by ceaglest** [comment]
Hi @vdovichenko,

That crash is with the WebSocket logic. It is very likely that it is the same crash that was already fixed in [3.7.2](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-3x#372-november-3-2020).

Can you please update from 3.7.1 to 3.7.2 or newer and let us know if it resolves the crash?

Thanks,
Chris

**Comment by vdovichenko** [comment]
Hi @ceaglest,
Thanks for the information. 
I'll let you know whether crash is resolved after we update Twilio lib in our app.

**Comment by piyushtank** [comment]
Closing the ticket as we think the crash is resolved. Feel free to reopen the ticket or open another ticket if you run into any issues.

Thanks,
Piyush
