### ISSUE TITLE
Can we get video frame data CVPixelBuffer?

### ISSUE THREAD

**Issue by tuando3i** [twilio/twilio-video-ios#156]
#### The Problem

I would like to access video frame data for some image processing but couldn't find the way

#### Solution You Would Like

Can you please let me know whether I can get video frame data in CVPixelBuffer format somehow?

**Comment by ceaglest** [comment]
Hey @tuando3i,

If you want to access the image data from a CVPixelBuffer then you must first call [CVPixelBufferLockBaseAddress()](https://developer.apple.com/documentation/corevideo/1457128-cvpixelbufferlockbaseaddress). This ensures that the image data is available to the CPU when calling  and that the base address will not change while you access it. When you are done accessing data call `CVPixelBufferUnlockBaseAddress()`. 

Some pseudo code to get the point across:

```
// Should check the return value
CVPixelBufferLockBaseAddress(buffer)

// Process image data. Need to access individual planes for NV12.
let address = CVPixelBufferGetBaseAddress(buffer)

// Should check the return value
CVPixelBufferUnlockBaseAddress(buffer)
```

Best,
Chris

**Comment by tuando3i** [comment]
Hi @ceaglest ,

Thank you for your answer.

I would like to know to get frame data from TwilioVideo framework.

As refer from this question [https://github.com/twilio/video-quickstart-ios/issues/496#issue-619624764](url)

It seems like I can write a custom Camera Source in case I want to own the Camera Session or custom VideoRenderer.

I will try those 2 methods.

By the way thank you.

**Comment by floriangbh** [comment]
Hello @tuando3i,

Did you successfully retrieved video frame from the Twilio SDK? 

I'm also looking at getting video frame (in CVPixelBuffer format) to make some rendering on it?

Thanks
