### ISSUE TITLE
Invalid parameter not satisfying videoRenderer != renderer

### ISSUE THREAD

**Issue by dsngeu** [twilio/twilio-video-ios#161]
**Invalid parameter not satisfying: adapter.videoRenderer != renderer**

   **localVideoTrack?.addRenderer(largeVideoView)**
  I got crash here with following crash line 
*Invalid parameter not satisfying: adapter.videoRenderer != renderer*

when I debug  localVideoTrack and largeVideoView(this is view where I want to preview the local video frames)
 po print(localVideoTrack)
**Optional(<TVILocalVideoTrack: 0x2837c5240>)**

**po largeVideoView**
▿ Optional<TVIVideoView>
  - some : <TVIMetalVideoView: 0x10d872920; frame = (1 0; 373 647); clipsToBounds = YES; autoresize = RM+BM; layer = <CALayer: 0x28223b700>>

what the mean of this error? and how to fix this?

**Comment by piyushtank** [comment]
@dsngeu The Video SDK throws this exception when the app tries to add the same VideoView twice to a VideoTrack. Please make sure your app doesn't add the same VideoView twice to the same VideoView.

We plan to make the exception message meaningful and more actionable in the future.

**Comment by dsngeu** [comment]
@piyushtank thanks for help.
