### ISSUE TITLE
SPM not able to resolve versioned dependency :

### ISSUE THREAD

**Issue by Arneoldenhave** [twilio/twilio-video-ios#162]
SPM not able to resolve dependency:

Error:
```
because no versions of twilio-video-app-ios match the requirement 4.0.0..<5.0.0 
and root depends on twilio-video-app-ios 4.0.0..<5.0.0, version solving failed.
```
My Package.swift
```
.package(url: "https://github.com/twilio/twilio-video-app-ios.git", from: "4.0.0")
```

_Originally posted by @Arneoldenhave in https://github.com/twilio/twilio-video-ios/issues/84#issuecomment-764455702_

**Comment by paynerc** [comment]
@Arneoldenhave

The package url is wrong. It should read `https://github.com/twilio/twilio-video-ios.git` for the `TwilioVideo.xcframework` dependency.

The URL you have listed is for the Twilio Video demonstration app.

Ryan

**Comment by Arneoldenhave** [comment]
Thanks!
