### ISSUE TITLE
How can I specify room type (P2P vs. Group) when connecting to / creating a room?

### ISSUE THREAD

**Issue by AttilaTheFun** [twilio/twilio-video-ios#163]
I see in the REST API that you can specify the room type (P2P vs. Group) when creating a room, but I don't see a way to specify this with the client SDK. 

Am I overlooking something? Or do I have to use the REST API to create the room in order to specify the room type, and then create an access token to this room from the server for the client? 

If it's not currently supported, I'd recommend adding this as a ConnectionOption in a future release of the SDK.
Thanks!

**Comment by ceaglest** [comment]
Hi @AttilaTheFun,

You haven't missed anything - it isn't possible to dynamically select the Room type from the SDK. Our recommendation at this time is to use the REST API to create Rooms if you need to select a type that is different than the default for your account.

We can keep this ticket to track the feature request.

Best,
Chris
