### ISSUE TITLE
 Undefined symbols for architecture arm64 while running pod lib lint using CocoaPods command

### ISSUE THREAD

**Issue by Sunilkumarr** [twilio/twilio-video-ios#164]
> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x)
> 
> If this is an issue with the SDK itself, file it here. If this is an issue with the QuickStart apps, please use [video-quickstart-ios](https://github.com/twilio/video-quickstart-ios/issues).
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

Undefined symbols for architecture arm64 is coming while creating CocoaPods lib project using Twilio video SDK 

added the video SDK as   `s.dependency 'TwilioVideo', '~> 4.2'` in podspec file  of MyLibrary 

### Steps to Reproduce

1. Create CocoaPods lib project using this link https://guides.cocoapods.org/making/using-pod-lib-create.html 
2. Create View controller class inside the Pods--> Development Pods--> MyLibrary and add the below code in 

* ViewController.h 
#import <TwilioVideo/TwilioVideo.h>

@property (strong, nonatomic) TVIDefaultAudioDevice *audioDevice;

* ViewController.m 
```

- (void)viewDidLoad {
    [super viewDidLoad];

    self.audioDevice = [TVIDefaultAudioDevice audioDevice];
    TwilioVideoSDK.audioDevice = self.audioDevice;

}
```
3.Go to the MyLibrary root folder where the `MyLibrary.podspec` and then use the below command in terminal 

```
pod lib lint MyLibrary.podspec --verbose  

```
#### Code

```swift
// Code that helps reproduce the issue
```

#### Expected Behavior

Should build successfully without errors 

#### Actual Behavior

Screenshot of the error 

![Screenshot 2021-01-29 at 1 38 18 PM](https://user-images.githubusercontent.com/11742961/106249063-db7c1e80-6237-11eb-987d-3c4cc7606622.png)

Error logs: 

```
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_TwilioVideoSDK", referenced from:
          objc-class-ref in ViewController.o
      "_OBJC_CLASS_$_TVIDefaultAudioDevice", referenced from:
          objc-class-ref in ViewController.o
    ld: symbol(s) not found for architecture arm64
```

#### Reproduces How Often

100%

#### Logs
Debug level logs are helpful when investigating issues. To enable debug level logging, add the following code to your application:

```.swift
TwilioVideoSDK.setLogLevel(.debug)
```

```
Not able to build the project it's failing in pod lib lint so no logs from Twilio  

```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

    s.dependency 'TwilioVideo', '~> 4.2'

#### Xcode

Version 12.3 (12C33)

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

[e.g. iPhone 8 Plus]

**Comment by paynerc** [comment]
@Sunilkumarr,

This is a duplicate of #144. At the present time we do not offer a arm64 simulator slice. We are working on resolving this, however it requires all of the dependencies of Twilio Video to also be updated. I don't have a timeframe for when this will be released, however this is currently under active development.

Ryan

**Comment by paynerc** [comment]
@Sunilkumarr,

After looking at this issue again, I believe that you are trying to build your own cocoapods library that has a dependency on Twilio Video. If that is the case, you will need to exclude the arm64 simulator in your pod spec definition. Take a look at TwilioVideo's [pod spec file from the 4.2.0 release](https://github.com/CocoaPods/Specs/blob/30143ab44666d568529bf8c4fe11b1c239de0e6e/Specs/1/d/9/TwilioVideo/4.2.0/TwilioVideo.podspec.json#L27-L29).

This shows how we are excluding the arm64 simulator for the time being.

I hope that helps.

Ryan

**Comment by Sunilkumarr** [comment]
@paynerc Thank you for your help will try it out.

**Comment by paynerc** [comment]
@Sunilkumarr,

Great! Let me know if that solves this issue. And keep an eye on #144. One we ship a release for that you can remove that exclusion from your Podspec file.

Ryan

**Comment by Sunilkumarr** [comment]
@paynerc It's working now Thanks. Sure will keep eye on #144
