### ISSUE TITLE
didDisconnect calls when connect to room

### ISSUE THREAD

**Issue by hudsonblack** [twilio/twilio-video-ios#172]
After connecting to room this delegate method calls immediately
`
 func participantDidConnect(room: Room, participant: RemoteParticipant)
`

**Comment by ceaglest** [comment]
Hi @hudsonblack,

Could you restate the question? 

`participantDidConnect` is called for each remote participant that connects to the Room after your local participant.

Best,
Chris

**Comment by hudsonblack** [comment]
@ceaglest Thanks for your quick response
I'm sorry. I meant `participantDidDisConnect` calls after room creation.

**Comment by ceaglest** [comment]
Hey @hudsonblack,

Could you provide a Room SID so we can have a look? One possibility is that your participants are not using identities that are unique within the scope of a Room.

Best,
Chris

**Comment by ceaglest** [comment]
Please reopen if you can provide a room or participant SID for analysis. 

The `participantDidDisconnect` is called when a participants connection to the room fails and can't be recovered, or if they disconnect from the room manually.
