### ISSUE TITLE
Question: Which WebRTC version is used for a given version of the SDK?

### ISSUE THREAD

**Issue by patrikwlund** [twilio/twilio-video-ios#173]
Hi, I'm wondering if there's a way to find out which WebRTC version is built in to a given version of the SDK. I've seen that you sometimes include such information in the release notes, but it seems like a rare occasion.

So for concrete questions:
1. Do you always post WebRTC upgrades in your release notes?
2. Can I find out from the SDK release package or in runtime which WebRTC version it is backed by?
3. If I can't find it out by myself from question 1 or 2, can you help me check which WebRTC version is used by the SDK version 3.7.2 specifically?

Best regards,
Patrik

**Comment by paynerc** [comment]
@patrikwlund 

We announce when we upgrade the version of WebRTC that Twilio Video iOS consumes in the Release Notes. With that said, Twilio Video iOS, `3.7.2` is built with WebRTC-67. Twilio Video iOS `4.0.0` was upgraded to WebRTC-83.

Ryan
