### ISSUE TITLE
How to show a synchronized call duration for two room participants?

### ISSUE THREAD

**Issue by dmd-pro** [twilio/twilio-video-ios#177]
Hello everyone! 

Thanks for developing this great Twilio SDK for video calls!

Currently, in our audio/video calling app, we need to show the duration of the call. There can be a maximum of two participants in the call. We've implemented it using a timer that updates call duration every second as shown bellow:

`callDurationTimer = Timer.scheduledTimer(timeInterval: 1, target: self, selector: (#selector(updateTimer)), userInfo: nil, repeats: true)`

`    @objc func updateTimer() {
        seconds += 1
        statusLabel.text = timeString(time: TimeInterval(seconds))
    }`

We start the timer in `func participantDidConnect(room: Room, participant: RemoteParticipant)` method of  RoomDelegate. However, in calls, there is a 1-6 seconds difference between the two devices like in the image below. 

Can you please suggest how to implement the call duration feature and synchronize the call duration in the best way? Does Twilio SDK provide this kind of functionality?

![IMG_9154](https://user-images.githubusercontent.com/4498720/111461102-fdc5ef00-8746-11eb-922c-a63e9fa3724b.JPG)

**Comment by ceaglest** [comment]
Hi @dmd-pro,

I apologize that we did not respond to your question. In case you are still interested:

> We start the timer in func participantDidConnect(room: Room, participant: RemoteParticipant) method of RoomDelegate. However, in calls, there is a 1-6 seconds difference between the two devices like in the image below.

I think the most reasonable and easy to implement timer would be based upon the condition that both Participants have entered the Room. However, it is not guaranteed that these events are delivered at the exact same time to all Participants. How do you handle the second Participant's timer? Do you use `roomDidConnect(room: Room)` for that?

> Can you please suggest how to implement the call duration feature and synchronize the call duration in the best way? Does Twilio SDK provide this kind of functionality?

It's all a matter of perspective. Today, Twilio doesn't provide a source of truth in the form of server timestamps for the events being delivered to Participants. You could elect one of your Participants to be a timekeeper and send a unix timestamp to the other Participant. We have a [DataTrackExample](https://github.com/twilio/video-quickstart-ios/tree/master/DataTrackExample) that demonstrates how to send simple data from one party to the other.

Another way to break the tie would be to deliver web hooks for the participants to your application server and then send a definitive timestamp from your server to the participants.

Best,
Chris
