### ISSUE TITLE
Dominant speaker not working properly

### ISSUE THREAD

**Issue by rpescador** [twilio/twilio-video-ios#178]
### Description

Cannot identify properly the dominant speaker in a Twilio Room

### Steps to Reproduce

1. Connect into Twilio room as Participant1 (wait for second participant to join)
2. Participant2 connects, Participant 1 (on its Twilio room delegate) receives a message on `dominantSpeakerDidChange` delegate method with Participant2 identity)
3. Regardless any audio update in any of sides (talking loud, mute the device, etc), `dominantSpeakerDidChange` update is never received in P1 or P2 anymore.
4. If `LocalAudioTrack` is disabled in P2, P1 receives a message in `dominantSpeakerDidChange` with the participant parameter set as nil, when P2 `LocalAudioTrack` is enabled again, `dominantSpeakerDidChange` is fired in P1 with P2 identity (but again, no more events are received regardless audio updates in any of the sides)

#### Code

```swift
        let connectOptions = ConnectOptions(token: twilioToken) { (builder) in
            builder.audioTracks = localAudioTracks
            builder.videoTracks =  localVideoTracks
                
                ...

             builder.isNetworkQualityEnabled = true
             builder.isDominantSpeakerEnabled = true
        }
        room = TwilioVideoSDK.connect(options: connectOptions, delegate: self)

       ... 
        func dominantSpeakerDidChange(room: Room, participant: RemoteParticipant?) {
             print("Participant: \(participant?.identity)")
       }
```

#### Expected Behavior

Delegate method message shall be received when the dominant speakers changes, including scenarios where there is no dominant speaker

#### Actual Behavior

Delegate method message is received always once for any of the other remote users, and is not changing regardless the audio changes in any of the participants

#### Reproduces How Often

Always happening

#### Logs
Debug level logs are helpful when investigating issues. To enable debug level logging, add the following code to your application:

[Twilio.log](https://github.com/twilio/twilio-video-ios/files/6167117/Twilio.log)

### Versions

Tested with Twilio Video 4.0.0 and 3.7.2 and the behavior is the same as described above

#### Video iOS SDK

4.3.0 via CocoaPods

#### Xcode

Version 12.4 (12D4e)

#### iOS Version

iPad OS 14.4

#### iOS Device

iPad Pro and iPad Air

**Comment by paynerc** [comment]
@rpescador,

Are both participants joining using the Swift code attached?

Can you provide a RoomSID for a room where this occurred so we can begin to troubleshoot the issue?

Thank you,

Ryan

**Comment by rpescador** [comment]
@ paynerc
Yes, that is the code used by both clients to connect.
This is the info for the room I performed the last testing:
`room: us.4fef86b4-c9b5-42ba-85e3-8762f669c725, roomSID: RM3e4c6a87b78b22d9e771d5bd30518841`

Rgds!

**Comment by paynerc** [comment]
@rpescador,

I took a look at the roomSid and one thing I noticed is that you have three clients that connected to the room:

```
P1: PAae8b69cee0a6a6435efef20c130ac9cc | CA33693b8dc1cf040ba96ecdb1688289ac | CONSOLE-DBeJA164DG6Y5GVZ-Raymundo’s MacBook Pro | unified | jsdk 2.10.0 | Electron 8.5.5 
P2: PAa9bc30ddd490274d8740ecddc38ce20a | CA65a6d1eed351cec342af3560e5df1fd8 | USER-rXBod7Y5EvY1kE3g-61FD8200_6AA9_40C3_87C6_43E7E156F042 | planb | ios 4.3.0 / 14.4 
P3: PA4f185916c14877869de481451be4f2ec | CA2eed3caaa815124cc01548353084203e | USER-ba0Dk4lEQ763QL58-01B67701_92B3_4A0F_BCF9_157C4C579DD5 | planb | ios 3.7.2 / 14.4 
```

The two iOS clients are connecting with Dominant Speaker enabled, however the web client is not. First step would be to enable it also on the Web user and see if that changes your results.

Second, debug level logging for both iOS clients would be very helpful in troubleshooting this. This will allow me to see what dominant speaker messages are being passed that I cannot necessarily see from the RoomSID itself.

Ryan

**Comment by paynerc** [comment]
@rpescador,

Also, the Dominant Speaker functionality is relative to the local participant. If there are only two people in the room, P1 will see P2 as the dominant speaker from their perspective and P2 will see P1 as the dominant speaker. Add a third participant with Dominant Speaker functionality enabled and you should see the delegate being invoked when the dominant speaker is changed.

Have a look here at the [Detecting the Dominant Speaker](https://www.twilio.com/docs/video/detecting-dominant-speaker#api-usage) documentation.

Let me know after adding a third participant if you are still not receiving dominant speaker delegate invocations.

Ryan

**Comment by rpescador** [comment]
@paynerc 
I collected the logs from both iPad clients connecting to:
room: us.c4ac878e-1b4e-4045-8747-f27f9326a8d0, roomSID: RMa0109ce6bd7c8ae8f62a64c72fe9509b
The third participant in the call is a JS client, with dominantSpeaker enabled
[TwilioHost.log](https://github.com/twilio/twilio-video-ios/files/6173489/TwilioHost.log) (P1)
[TwilioParticipant.log](https://github.com/twilio/twilio-video-ios/files/6173490/TwilioParticipant.log) (P2)

The issue Im facing is that I do not receive a message in the delegate method informing that there is no dominant speaker in the room:

`func dominantSpeakerDidChange(room: Room, participant: RemoteParticipant?) {
// participant is never nil!
 }`
 
 I tried this:
P1 (iPad client), P2 (iPad client) and P3 (JS Client)

P1 enters into the room

P2 enters into the room

At that moment P1 receives
 ` func dominantSpeakerDidChange(room: Room, participant: RemoteParticipant?) {
// participant == P2
 }`
 
 And P2 receives
 ` func dominantSpeakerDidChange(room: Room, participant: RemoteParticipant?) {
// participant == P1
 }`

note: none of the clients are really dominant speakers, when entering into the twilio room they are completely silent.
 
Finally P3 enters into the room

Nothing changes (Notice that none of the client are generating sound into the room to be considered dominant speakers)

 If I speak in the JS client (P3), both clients (P1 and P2) receive:
` func dominantSpeakerDidChange(room: Room, participant: RemoteParticipant?) {
// participant == P3
 }`
 However, once I stop speaking in P3, P1 receives immediately:
 ` func dominantSpeakerDidChange(room: Room, participant: RemoteParticipant?) {
// participant == P2
 }`
And P2
 ` func dominantSpeakerDidChange(room: Room, participant: RemoteParticipant?) {
// participant == P1
 }`

I never receive in neither P1 nor P2
  ` func dominantSpeakerDidChange(room: Room, participant: RemoteParticipant?) {
// participant == nil
 }`
 
 Because of this I cannot fire the logic I have in place to reset/clear the current dominant speaker when no one is speaking in the room.

I tried different scenarios (All clients in different rooms in the office, all clients with different rooms and headphones connected, all clients in different rooms with both mic and speaker volume at minimum) and Im not able to receive the `participant == nil` in any of the iPad clients.
 
Rgds!

**Comment by paynerc** [comment]
@rpescador,

Sorry for the delay in getting back to you. I wanted to make sure I had a chance to talk to our backend folks before responding to make sure I was correct in my response.

The Dominant Speaker functionality is implemented on the media server side. The media server performs the calculations to determine which remote audio track is the active speaker for each participant. Even when no participant is actively speaking, there is still residual volume on an enabled and unpaused audio track, therefore the track with the most "volume" is still considered the active speaker. The only time that `dominantSpeakerDidChange` will return a `nil` remote participant is when there are no shared audio tracks, or they are shared but muted.

I hope that helps explain the expected behavior of the Dominant Speaker functionality.

Ryan
