### ISSUE TITLE
Choose VideoFormat error

### ISSUE THREAD

**Issue by Goule** [twilio/twilio-video-ios#183]
Hello,

### Description

I'm trying to force quality for the camera. But I have an error when I'm trying to do it.
By default there is very low frame size of 640x360 is captured and sent to receivers, whereas I'm on iPhone XS back camera and really goog connexion. 

How to force a quality up to 720p or 1080p with good network quality? 

#### Code

Code modified from the sample. 

```swift
let format = VideoFormat()
format.dimensions = CMVideoDimensions(width: 1280, height: 720)
camera!.startCapture(device: backCamera!, format: format) { (captureDevice, videoFormat, error) in
    if let error = error {
        self.logMessage(messageText: "Capture failed with error.\ncode = \((error as NSError).code) error = \(error.localizedDescription)")
    } else {
        self.previewView.shouldMirror = (captureDevice.position == .front)
     }
 }
```

#### Expected Behavior

Camera and video of the participant in 720p or 1080p.

#### Actual Behavior

```
ERROR:Twilio:[Platform](0x16b8c3000): Fatal runtime capture error: Error Domain=com.twilio.video.capturer.camera Code=1004 "Could not find a valid device format." UserInfo={NSLocalizedFailureReason=Could not find a valid device format.}, code 1004
2021-04-27 11:48:21.365403+0200 VideoQuickStart[3638:287591] Capture failed with error.
code = 1004 error = The operation couldn’t be completed. Could not find a valid device format.
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

[e.g. 4.4.0 via SPM]

#### Xcode

[e.g. 12.5]

#### iOS Version

[e.g. 14.5]

#### iOS Device

[e.g. iPhone X with back camera]

Thanks

**Comment by paynerc** [comment]
@Goule

Take a look at the [`TVICameraSource supportedFormatsForDevice:`](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVICameraSource.html#//api/name/supportedFormatsForDevice:) method. This will return all the valid [`TVIVideoFormat`](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIVideoFormat.html)s support by the specified camera. Iterate through the formats returned and find the one that meets your criteria and then pass that into the `startCapture` method.

Ryan

**Comment by Goule** [comment]
Hello @paynerc ,

Thanks for you response, it work fine ! 

Here is an exemple to catch 1080p : 
```swift
let supportedFormats = CameraSource.supportedFormats(captureDevice: backCamera!)
            var formatFound: VideoFormat?
            for format in supportedFormats {
                if let formatCasted = format as? VideoFormat {
                    if formatCasted.dimensions.height == 1080 && formatCasted.dimensions.width == 1920 {
                        formatFound = formatCasted
                    }
                }
            }
```

Thanks
