### ISSUE TITLE
Get video frame from participant

### ISSUE THREAD

**Issue by Goule** [twilio/twilio-video-ios#184]
Hello,

I would like to retrieve the video frame received from a participant but I can't find how to do it.

It looks like TVIVideoFrame is what I need to get frame but how to get it from the participant?

Usecase: my user needs to select one of the participants to broadcast it to the RTMP destination.

Thanks

**Comment by paynerc** [comment]
@Goule

What you can do is implement a custom [`TVIVideoRenderer`](https://twilio.github.io/twilio-video-ios/docs/latest/Protocols/TVIVideoRenderer.html) and add it to the [`TVIVideoTrack`](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIVideoTrack.html) via the [`addRenderer`](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIVideoTrack.html#//api/name/addRenderer:) method. The [`TVIVideoRender renderFrame:`](https://twilio.github.io/twilio-video-ios/docs/latest/Protocols/TVIVideoRenderer.html#//api/name/renderFrame:) method will be invoked for each [`TVIVideoFrame`](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIVideoFrame.html) produced for the `TVIVideoTrack`.

Ryan

**Comment by Goule** [comment]
Thanks @paynerc, it's working !
