### ISSUE TITLE
[SPM] Artifact of binary target "TwilioVideo" failed extraction

### ISSUE THREAD

**Issue by SergejLogis** [twilio/twilio-video-ios#190]
### Description

We recently have updated our `TwilioVideo` integration from manual to SPM. It works fine (better than manual, definitely), however, we have adopted a new annoying and time-consuming issue - every time we switch a Git branch we need to do `Reset Package Cache` in SPM for project to compile. Needless to say, that it "eats" a significant amount of time and is annoying as hell! 😅 

### Steps to Reproduce

1. Add `TwilioVideo` via SPM.
2. Compile the project.
3. Switch to a branch without `TwilioVideo`.
4. Compile the project.
5. Switch back to the branch with `TwilioVideo` and compile project.

#### Expected Behavior

The project compiles without the need to `Reset Package Cache`.

#### Actual Behavior

After switching branches project compilation fails with the following error:
`artifact of binary target 'TwilioVideo' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)`

#### Reproduces How Often

100% whenever after switching branch Xcode updates SPM dependencies.

#### Video iOS SDK

4.4.0 via SPM

#### Xcode

12.5

**Comment by alfredomerino** [comment]
I have the same issue with the same setup except its happening with Twilio-chat-ios. We moved Chat from CocoaPods since it was causing some headaches with git lfs. I created a very similar issue on TwilioChat and linked your issue on mine in case we get some action. Best of luck in getting this resolved
[https://github.com/twilio/twilio-chat-ios/issues/28](url)

**Comment by SergejLogis** [comment]
Thanks! 🤜🤛

**Comment by paynerc** [comment]
@SergejLogis  && @alfredomerino,

Thanks for reporting this. I am thinking this is more of an Xcode bug with SPM packages that use Binary dependencies, however I will dig into this to see if I can come up with a solution.

Ryan

**Comment by SergejLogis** [comment]
@paynerc @alfredomerino I have found a workaround for this issue (kind of). If I close Xcode before switching branches - this issue doesn't appear (tested it few times). Knowing the fact, that Xcode is the kind of beast that LIKES to be restarted as often as possible, I'd say it's a pretty feasible solution for the time being (until Apple fixes it, hopefully 🤞). 😅

**Comment by paynerc** [comment]
> @paynerc @alfredomerino I have found a workaround for this issue (kind of). If I close Xcode before switching branches - this issue doesn't appear (tested it few times). Knowing the fact, that Xcode is the kind of beast that LIKES to be restarted as often as possible, I'd say it's a pretty feasible solution for the time being (until Apple fixes it, hopefully 🤞). 😅

Yeah, that's what I am seeing. It doesn't seem to be an issue specific to the Twilio packages, but in general with binary SPM packages. I still need to do a bit more searching on this issue and if it is not noted anywhere, I will file an  Feedback. Feel free to also file an  Feedback. The more people that report it, hopefully it will get looked at.

Ryan

**Comment by alfredomerino** [comment]
Looks like Xcode 13 beta is working for my similar issue with TwilioChat. @SergejLogis , I'm interested if it can work for you too?

**Comment by SergejLogis** [comment]
Thanks for note! I didn't have time to play with Xcode 13 yet, though 🤓
