### ISSUE TITLE
TwilioVideoSDK.connect Crash in release mode only

### ISSUE THREAD

**Issue by Mustafa-Ezzat** [twilio/twilio-video-ios#193]
Date/Time:        2021-06-16 00:19:55.249 +0200
End time:         2021-06-16 00:22:09.937 +0200
OS Version:       iPhone OS 14.6 (Build 18F72)
Architecture:     arm64
Report Version:   32
Incident Identifier: D6279959-EFAD-4490-B6D2-2CB301C4CCF4
Share With Devs:  Yes

Data Source:      Microstackshots
Shared Cache:     0A3898DD-1C5C-3B0D-8097-F887CCB9AD8A slid base address 0x18c554000, slide 0xc554000

Command:          Backstage Debug
Path:             /private/var/containers/Bundle/Application/582FA664-AF24-4A34-BC95-533BC68FBDBD/Backstage Debug.app/Backstage Debug
Identifier:       com.backstage.casting-internal
Version:          2.3.12 (1496)
Beta Identifier:  8AEF929B-5647-4A5E-92D5-C8C9AF055BF5
PID:              5341

Event:            wakeups
Action taken:     none
Wakeups:          45001 wakeups over the last 135 seconds (334 wakeups per second average), exceeding limit of 150 wakeups per second over 300 seconds
Wakeups limit:    45000
Limit duration:   300s
Wakeups caused:   45001
Wakeups duration: 135s
Duration:         134.69s
Duration Sampled: 108.51s
Steps:            17

Hardware model:   iPhone8,1
Active cpus:      2

Heaviest stack for the target process:
  12  ??? (libsystem_pthread.dylib + 40052) [0x1d4ee7c74]
  10  ??? (<9173FADF-C453-3FD3-A8DD-A743C5E5C4E9> + 4924116) [0x10e6ee2d4]
  10  ??? (<9173FADF-C453-3FD3-A8DD-A743C5E5C4E9> + 5648476) [0x10e79f05c]
  5   ??? (<9173FADF-C453-3FD3-A8DD-A743C5E5C4E9> + 5650120) [0x10e79f6c8]
  5   ??? (<9173FADF-C453-3FD3-A8DD-A743C5E5C4E9> + 4925400) [0x10e6ee7d8]
  5   ??? (<9173FADF-C453-3FD3-A8DD-A743C5E5C4E9> + 4925692) [0x10e6ee8fc]
  5   ??? (libsystem_kernel.dylib + 161152) [0x1b876d580]

Powerstats for:   Backstage Debug [5341]
UUID:             EE5343B9-F2F5-36EB-A108-58F9C141A94F
Beta Identifier:  8AEF929B-5647-4A5E-92D5-C8C9AF055BF5
App Version:      2.3.12
Build Version:    1496
Path:             /private/var/containers/Bundle/Application/582FA664-AF24-4A34-BC95-533BC68FBDBD/Backstage Debug.app/Backstage Debug
Architecture:     arm64
Footprint:        33.55 MB -> 65.78 MB (+32.23 MB) (max 70.59 MB )
Pageins:          2 pages
Start time:       2021-06-16 00:20:20.267 +0200
End time:         2021-06-16 00:22:08.780 +0200
Num samples:      17 (100%)
Primary state:    7 samples Non-Frontmost App, Non-Suppressed, User mode, Effective Thread QoS Unspecified, Requested Thread QoS Unspecified, Override Thread QoS Unspecified
User Activity:    15 samples Idle, 2 samples Active
Power Source:     0 samples on Battery, 17 samples on AC
  12  _pthread_start + 287 (libsystem_pthread.dylib + 40052) [0x1d4ee7c74]
    10  rtc::PlatformThread::StartThread + 11 (TwilioVideo + 4924116) [0x10e6ee2d4]
      10  webrtc::ProcessThreadImpl::Run + 35 (TwilioVideo + 5648476) [0x10e79f05c]
        5   webrtc::ProcessThreadImpl::Process + 671 (TwilioVideo + 5650120) [0x10e79f6c8]
          5   rtc::Event::Wait + 275 (TwilioVideo + 4925400) [0x10e6ee7d8]
            5   rtc::Event::Wait::$_0::operator()(absl::optional<timespec>) const + 75 (TwilioVideo + 4925692) [0x10e6ee8fc]
              5   __psynch_cvwait + 8 (libsystem_kernel.dylib + 161152) [0x1b876d580]
                3   <Kernel mode>
        4   webrtc::ProcessThreadImpl::Process + 431 (TwilioVideo + 5649880) [0x10e79f5d8]
          1   webrtc::PacedSender::Process + 31 (TwilioVideo + 6390372) [0x10e854264]
            1   webrtc::PacingController::ProcessPackets + 1008 (TwilioVideo + 6395284) [0x10e855594]
          1   webrtc::ModuleRtpRtcpImpl::Process + 695 (TwilioVideo + 6185392) [0x10e8221b0]
            1   webrtc::RTCPSender::TMMBR const + 39 (TwilioVideo + 6150432) [0x10e819920]
              1   rtc::CritScope::~CritScope + 23 (TwilioVideo + 4919436) [0x10e6ed08c]
                1   _pthread_mutex_fairshare_unlock_slow$VARIANT$mp + 212 (libsystem_pthread.dylib + 15580) [0x1d4ee1cdc]
          1   webrtc::ModuleRtpRtcpImpl::Process + 115 (TwilioVideo + 6184812) [0x10e821f6c]
            1   webrtc::RTCPSender::Sending const + 31 (TwilioVideo + 6148880) [0x10e819310]
              1   rtc::CritScope::~CritScope + 23 (TwilioVideo + 4919436) [0x10e6ed08c]
                1   _pthread_mutex_fairshare_unlock_slow$VARIANT$mp + 212 (libsystem_pthread.dylib + 15580) [0x1d4ee1cdc]
          1   webrtc::ModuleRtpRtcpImpl::Process + 83 (TwilioVideo + 6184780) [0x10e821f4c]
            1   webrtc::RateStatistics::Rate const + 0 (TwilioVideo + 4917556) [0x10e6ec934]
        1   webrtc::ProcessThreadImpl::Process + 440 (TwilioVideo + 5649888) [0x10e79f5e0]
    1   void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, AURemoteIO::IOThread::IOThread::'lambda'(), std::__1::tuple<> > >(void*) + 599 (libEmbeddedSystemAUs.dylib + 612188) [0x1bc75375c]
      1   MSHMIGDispatchMessage + 35 (libAudioToolboxUtility.dylib + 71088) [0x1a0e0b5b0]
        1   mshMIGPerform + 255 (libAudioToolboxUtility.dylib + 70048) [0x1a0e0b1a0]
          1   _XPerformIO + 315 (libEmbeddedSystemAUs.dylib + 925860) [0x1bc7a00a4]
            1   AURemoteIO::PerformIO + 843 (libEmbeddedSystemAUs.dylib + 643800) [0x1bc75b2d8]
              1   webrtc::ios_adm::AudioDeviceIOS::OnDeliverRecordedData + 279 (TwilioVideo + 5658924) [0x10e7a192c]
                1   webrtc::FineAudioBuffer::DeliverRecordedData + 115 (TwilioVideo + 5620192) [0x10e7981e0]
                  1   webrtc::AudioDeviceBuffer::DeliverRecordedData + 123 (TwilioVideo + 5616752) [0x10e797470]
                    1   webrtc::AudioTransportImpl::RecordedDataIsAvailable + 267 (TwilioVideo + 3784464) [0x10e5d7f10]
                      1   webrtc::ProcessAudioFrame + 143 (TwilioVideo + 5757232) [0x10e7b9930]
                        1   webrtc::AudioProcessingImpl::ProcessStream + 183 (TwilioVideo + 5724088) [0x10e7b17b8]
                          1   webrtc::AudioProcessingImpl::ProcessCaptureStreamLocked + 1035 (TwilioVideo + 5721380) [0x10e7b0d24]
                            1   webrtc::S16ToFloatS16 + 4 (TwilioVideo + 3841012) [0x10e5e5bf4]
                              1   <Frontmost App>
    1   rtc::Thread::PreRun + 79 (TwilioVideo + 4770864) [0x10e6c8c30]
      1   rtc::Thread::ProcessMessages + 123 (TwilioVideo + 4765844) [0x10e6c7894]
        1   rtc::Thread::Dispatch + 135 (TwilioVideo + 4769880) [0x10e6c8858]
          1   rtc::AsyncInvoker::OnMessage + 31 (TwilioVideo + 4669756) [0x10e6b013c]
            1   sigslot::signal_with_thread_policy<sigslot::single_threaded, rtc::SentPacket const&>::emit + 59 (TwilioVideo + 4000304) [0x10e60ca30]
              1   webrtc::RtpTransportControllerSend::OnSentPacket + 91 (TwilioVideo + 6326848) [0x10e844a40]
                1   rtc::TaskQueue::PostTask + 23 (TwilioVideo + 4925904) [0x10e6ee9d0]
                  1   _dispatch_event_loop_poke$VARIANT$mp + 339 (libdispatch.dylib + 131488) [0x18c5ba1a0]
                    1   kevent_id + 8 (libsystem_kernel.dylib + 168808) [0x1b876f368]
                      1   <Kernel mode, Effective Thread QoS Default, Requested Thread QoS Default>
  4   start + 3 (libdyld.dylib + 4416) [0x18c61a140]
    4   ??? (Backstage Debug + 3719100) [0x1047f7fbc]
      4   UIApplicationMain + 163 (UIKitCore + 11753060) [0x18f26c664]
        4   -[UIApplication _run] + 1051 (UIKitCore + 11731176) [0x18f2670e8]
          4   GSEventRunModal + 159 (GraphicsServices + 13680) [0x1a3041570]
            4   CFRunLoopRunSpecific + 571 (CoreFoundation + 604184) [0x18c93b818]
              4   __CFRunLoopRun + 1947 (CoreFoundation + 607484) [0x18c93c4fc]
                4   __CFRunLoopDoTimers + 323 (CoreFoundation + 631236) [0x18c9421c4]
                  4   __CFRunLoopDoTimer + 1015 (CoreFoundation + 634096) [0x18c942cf0]
                    4   __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 27 (CoreFoundation + 635120) [0x18c9430f0]
                      4   __NSFireDelayedPerform + 403 (Foundation + 1356068) [0x18dcdb124]
                        4   ??? (Backstage Debug + 8060752) [0x104c1bf50]
                          4   ??? (Backstage Debug + 8060660) [0x104c1bef4]
                            3   ??? (Backstage Debug + 8053964) [0x104c1a4cc]
                              3   ??? (Backstage Debug + 825900) [0x104535a2c]
                                2   +[UIColor colorNamed:inBundle:compatibleWithTraitCollection:] + 167 (UIKitCore + 7297176) [0x18ee2c898]
                                  2   -[_UIAssetManager colorNamed:withTraitCollection:] + 235 (UIKitCore + 15546440) [0x18f60a848]
                                    1   -[CUICatalog colorWithName:displayGamut:deviceIdiom:appearanceName:] + 475 (CoreUI + 514896) [0x198322b50]
                                      1   -[CUICatalog _resolvedRenditionKeyForName:scaleFactor:deviceIdiom:deviceSubtype:displayGamut:layoutDirection:sizeClassHorizontal:sizeClassVertical:memoryClass:graphicsClass:graphicsFallBackOrder:deviceSubtypeFallBackOrder:withBaseKeySelector:adjustRenditionKeyWithBlock:] + 239 (CoreUI + 519288) [0x198323c78]
                                        1   -[CUICatalog _baseColorKeyForName:] + 43 (CoreUI + 514316) [0x19832290c]
                                          1   -[CUIStructuredThemeStore renditionKeyForName:cursorHotSpot:] + 131 (CoreUI + 350220) [0x1982fa80c]
                                            1   -[NSCache objectForKey:] + 147 (CoreFoundation + 29788) [0x18c8af45c]
                                              1   os_unfair_lock_lock_with_options$VARIANT$mp + 20 (libsystem_platform.dylib + 18764) [0x1d4ed694c]
                                                1   <Effective Thread QoS Default, Requested Thread QoS User Interactive>
                                    1   -[CUICatalog colorWithName:displayGamut:deviceIdiom:appearanceName:] + 95 (CoreUI + 514516) [0x1983229d4]
                                      1   object_getIndexedIvars + 0 (libobjc.A.dylib + 34360) [0x1a06ff638]
                                        1   <Effective Thread QoS Default, Requested Thread QoS User Interactive>
                                1   +[UIColor colorNamed:inBundle:compatibleWithTraitCollection:] + 135 (UIKitCore + 7297144) [0x18ee2c878]
                                  1   +[_UIAssetManager assetManagerForBundle:] + 99 (UIKitCore + 15539496) [0x18f608d28]
                                    1   -[_UICache objectForKey:] + 19 (UIFoundation + 64068) [0x19545aa44]
                                      1   -[_UICache retainedObjectForKey:] + 127 (UIFoundation + 931052) [0x19552e4ec]
                                        1   _dispatch_lane_barrier_sync_invoke_and_complete + 55 (libdispatch.dylib + 67604) [0x18c5aa814]
                                          1   _dispatch_client_callout + 15 (libdispatch.dylib + 397976) [0x18c5fb298]
                                            1   __33-[_UICache retainedObjectForKey:]_block_invoke + 35 (UIFoundation + 931156) [0x19552e554]
                                              1   -[__NSDictionaryM objectForKey:] + 152 (CoreFoundation + 14504) [0x18c8ab8a8]
                                                1   <Effective Thread QoS Default, Requested Thread QoS User Interactive>
                            1   ??? (Backstage Debug + 8053896) [0x104c1a488]
                              1   ??? (Backstage Debug + 825900) [0x104535a2c]
                                1   +[_UIAssetManager assetManagerForBundle:] + 0 (UIKitCore + 15539396) [0x18f608cc4]
                                  1   <Effective Thread QoS Default, Requested Thread QoS User Interactive>
  1   _pthread_wqthread + 271 (libsystem_pthread.dylib + 46524) [0x1d4ee95bc]
    1   _dispatch_workloop_worker_thread + 711 (libdispatch.dylib + 81836) [0x18c5adfac]
      1   _dispatch_lane_invoke$VARIANT$mp + 419 (libdispatch.dylib + 42264) [0x18c5a4518]
        1   _dispatch_lane_serial_drain$VARIANT$mp + 611 (libdispatch.dylib + 39488) [0x18c5a3a40]
          1   _dispatch_client_callout + 15 (libdispatch.dylib + 397976) [0x18c5fb298]
            1   developerSubmittedBlockToNSManagedObjectContextPerform + 155 (CoreData + 1269648) [0x1927d0f90]
              1   __44-[IBGDALService writeASync:completionBlock:]_block_invoke + 39 (Instabug + 2736956) [0x106cd033c]
                1   __206-[IBGVisualUserStepsLogger addStepWithEventType:parentScreenIdentifier:screenshotIdentifeir:screenIdentifier:view:screenshot:reproStepsButtonIcon:reproStepsButtonName:date:oreintation:topViewName:isParent:]_block_invoke + 415 (Instabug + 2444752) [0x106c88dd0]
                  1   UIImagePNGRepresentation + 491 (UIKitCore + 7449808) [0x18ee51cd0]
                    1   CGImageDestinationFinalize + 127 (ImageIO + 1285432) [0x18df5fd38]
                      1   IIOImageDestination::finalizeDestination + 539 (ImageIO + 1278832) [0x18df5e370]
                        1   PNGWritePlugin::WriteProc + 87 (ImageIO + 1156020) [0x18df403b4]
                          1   PNGWritePlugin::writeAll + 911 (ImageIO + 1155640) [0x18df40238]
                            1   PNGWritePlugin::writePNG + 1095 (ImageIO + 1147816) [0x18df3e3a8]
                              1   _cg_png_write_row + 759 (ImageIO + 1068004) [0x18df2abe4]
                                1   png_write_find_filter + 395 (ImageIO + 1240796) [0x18df54edc]
                                  1   png_compress_IDAT + 223 (ImageIO + 1231596) [0x18df52aec]
                                    1   deflate + 3227 (libz.1.dylib + 11252) [0x1d4b2abf4]
                                      1   ??? (libz.1.dylib + 14232) [0x1d4b2b798]
                                        1   ??? (libz.1.dylib + 6592) [0x1d4b299c0]
                                          1   <Frontmost App, Effective Thread QoS User Initiated, Requested Thread QoS User Initiated>

  Binary Images:
           0x10446c000 -                ???  com.backstage.casting-internal 2.3.12 (1496) <EE5343B9-F2F5-36EB-A108-58F9C141A94F>  /private/var/containers/Bundle/Application/582FA664-AF24-4A34-BC95-533BC68FBDBD/Backstage Debug.app/Backstage Debug
           0x106a34000 -                ???  ???                                          <82A75C4A-6402-369F-B6DE-D5DE69C83366>  Instabug
           0x10e23c000 -                ???  ???                                          <9173FADF-C453-3FD3-A8DD-A743C5E5C4E9>  TwilioVideo
           0x18c59a000 -        0x18c618fff  libdispatch.dylib                            <3BBE17AC-597B-3B79-91AC-21A5523E7BD7>  /usr/lib/system/libdispatch.dylib
           0x18c619000 -        0x18c64ffff  libdyld.dylib                                <5FFFB964-39D6-3CCF-BD34-C6CA4A148D1A>  /usr/lib/system/libdyld.dylib
           0x18c8a8000 -        0x18cc53fff  CoreFoundation                               <4D6DD6DD-22E4-3858-9A0C-3CB77C2F13D6>  /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
           0x18db90000 -        0x18de25fff  Foundation                                   <777F51FC-EF37-388B-8985-228E98115207>  /System/Library/Frameworks/Foundation.framework/Foundation
           0x18de26000 -        0x18e18efff  ImageIO                                      <5D86BA0A-401B-38A3-B964-FBFAA074807C>  /System/Library/Frameworks/ImageIO.framework/ImageIO
           0x18e737000 -        0x18fa5ffff  UIKitCore                                    <186F3A78-108A-3057-A67E-800A88EBFF00>  /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
           0x19269b000 -        0x1929f9fff  CoreData                                     <554780D7-EC38-3CAE-98A9-7109F58E3272>  /System/Library/Frameworks/CoreData.framework/CoreData
           0x19544b000 -        0x19554dfff  UIFoundation                                 <0820D46E-358C-3428-A701-96792AFF1BBE>  /System/Library/PrivateFrameworks/UIFoundation.framework/UIFoundation
           0x1982a5000 -        0x198364fff  CoreUI                                       <370B46D0-A8AC-383C-BE59-79997EA5788C>  /System/Library/PrivateFrameworks/CoreUI.framework/CoreUI
           0x1a06f7000 -        0x1a072cfff  libobjc.A.dylib                              <F7BD04B8-DC49-38CC-B534-52D7A7E1A143>  /usr/lib/libobjc.A.dylib
           0x1a0dfa000 -        0x1a0e2cfff  libAudioToolboxUtility.dylib                 <B4CDA185-23A1-3BB2-925B-71E67EFAD250>  /usr/lib/libAudioToolboxUtility.dylib
           0x1a303e000 -        0x1a3046fff  GraphicsServices                             <0236B078-E787-3935-B59D-9B0BEA3FE2DD>  /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
           0x1b8746000 -        0x1b8776fff  libsystem_kernel.dylib                       <B9B71733-3791-3116-A5E2-6159FABF74A2>  /usr/lib/system/libsystem_kernel.dylib
           0x1bc6be000 -        0x1bc7cefff  libEmbeddedSystemAUs.dylib                   <5F781F98-4C83-3C7E-B6C9-A441F1F3400A>  /System/Library/Frameworks/AudioToolbox.framework/libEmbeddedSystemAUs.dylib
           0x1d4b28000 -        0x1d4b39fff  libz.1.dylib                                 <95ACF430-D6D1-3E97-BDF9-DE05F8FC9B9F>  /usr/lib/libz.1.dylib
           0x1d4ed2000 -        0x1d4edcfff  libsystem_platform.dylib                     <ABA70F95-77D9-37FD-B287-998CD4D565E1>  /usr/lib/system/libsystem_platform.dylib
           0x1d4ede000 -        0x1d4eeefff  libsystem_pthread.dylib                      <9CFEBF14-879B-3AAF-A29D-EC1CDBA54826>  /usr/lib/system/libsystem_pthread.dylib

**Comment by paynerc** [comment]
@Mustafa-Ezzat,

Can you comment on which version of TwilioVideo iOS you are using and on which device? Does this crash happen all the time or is it intermittent?

Thanks,

Ryan

**Comment by Mustafa-Ezzat** [comment]
> Can you comment on which version of TwilioVideo iOS?
4.4.0 
> which device?
iPhone 6s
> iOS?
14.6
> Does this crash happen all the time or is it intermittent?
yes all the time on the release mode

**Comment by paynerc** [comment]
Looking at attached report, this doesn't appear to be the crash report but the report that is generated when the OS kills an app in the background that is consuming too many resources.

Can you walk me through the scenario that is occurring when the crash happens? Is the app in the background? Etc?

I have dug out an iPhone 6s and am waiting for it to charge enough to start and I will do some testing in release mode on the iOS 6s device, but need a little more to go on to ensure I am replicating your experience.

Thank you,

Ryan

**Comment by ceaglest** [comment]
I just wanted to mention that there is a scenario where backgrounding while receiving multiple video tracks can exceed the CPU usage limits on an iOS device. In these logs the resource usage assertion is not about CPU time but rather CPU wakeups.
