### ISSUE TITLE
Cannot load v4.5 via Pods

### ISSUE THREAD

**Issue by gregschwartz** [twilio/twilio-video-ios#194]
### Description

Error when trying to load v4.5 via pods. However, if I downgrade the Podfile version to `pod 'TwilioVideo', '~> 4.4'` it works. 

### Steps to Reproduce

1. Add `pod 'TwilioVideo', '~> 4.5'` to `Podfile`
2. Add `source 'https://github.com/CocoaPods/Specs'` to `Podfile`
3. Run `pod install` in console

#### Code

Here's my Podfile:
```
source 'https://github.com/CocoaPods/Specs'

platform :ios, '13.0'

target 'Bubble Dating' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bubble Dating
  pod 'Alamofire', '~> 5.2' #networking
  pod "GaugeKit"  #timer in speed dates
  pod 'Cloudinary', '~> 2.0' #user photos
  pod 'ISHLogDNA' #logging aggregation
  pod 'TwilioVideo', '~> 4.5' #Video chat

  target 'Bubble DatingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bubble DatingUITests' do
    # Pods for testing
  end

end

```

#### Expected Behavior

Expected to see pod installed.

#### Actual Behavior
```
$ pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "TwilioVideo":
  In Podfile:
    TwilioVideo (~> 4.5)

There are only pre-release versions available satisfying the following requirements:

        'TwilioVideo', '~> 4.5'

You should explicitly specify the version in order to install a pre-release version
````

Tried changing it to `pod 'TwilioVideo', '4.5'`:
````
$ pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "TwilioVideo":
  In Podfile:
    TwilioVideo (= 4.5)

None of your spec sources contain a spec satisfying the dependency: `TwilioVideo (= 4.5)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
````

#### Reproduces How Often

Every time. 

### Versions

macOS Big Sur 11.4 20F71
pod v1.10.0

**Comment by paynerc** [comment]
@gregschwartz 

That is actually correct behavior at this time as `4.4.0` is the latest GA release of Twilio Video. The [releases page](https://github.com/twilio/twilio-video-ios/releases) shows that `4.4.0` is the latest release with `4.6.0-beta1` being available as a prerelease as it is the release which has support for the M1 Mac simulators.

The `4.5.0` release is still in progress with other features that we expect to be available soon.

Let me know if you have any further questions,

Ryan

**Comment by gregschwartz** [comment]
Thanks for the quick response Ryan! I'm a bit confused then. Why does the documentation have code to use 4.6, since that will always fail?

Docs:
<img width="854" alt="Screen Shot 2021-06-16 at 11 32 27 AM" src="https://user-images.githubusercontent.com/206568/122273721-9c710180-ce96-11eb-9b7f-a06ab84cb834.png">

**Comment by paynerc** [comment]
Good catch. Looks like some of the release automation didn't take into account the beta pre-release qualifier when we released the Beta.

I will revert that change right now as that should never have been updated and will create an internal ticket to check and correct the automation script.

**Comment by paynerc** [comment]
The `README.md` file has been updated with the correct version.

**Comment by gregschwartz** [comment]
Got it, thank you!
