### ISSUE TITLE
Question about SDK determining whether custom audio device supports capturing

### ISSUE THREAD

**Issue by eigenl** [twilio/twilio-video-ios#197]
### Description

Using a custom audio device. Occasionally we get the following exception thrown by instantiating a LocalAudioTrack:

`Cannot create a TVILocalAudioTrack because the supplied AudioDevice does not support audio capturing.`

My question is how does the SDK determine this so that we could handle this case before it reaches the LocalAudioTrack initializer, which isn't marked as throwing making it impossible to recover from. According to the documentation, it's supposed to return nil in case of an error, but this exception seems to be fatal.

I don't see anything in the TVIAudioDeviceCapturer protocol that would help determine if the device supports capturing or not.

#### Code

```swift
// What other checks could we perform here?
if AVAudioSession.sharedInstance().isInputAvailable == true {
  return LocalAudioTrack(options: .init(), enabled: false, name: nil)
}
```

#### Video iOS SDK

4.4.0

#### iOS Version

14.7

#### iOS Device

iPhone 11

**Comment by ceaglest** [comment]
Hi @eigenl,

> I don't see anything in the TVIAudioDeviceCapturer protocol that would help determine if the device supports capturing or not.

You can return `nil` for [captureFormat](https://twilio.github.io/twilio-video-ios/docs/latest/Protocols/TVIAudioDeviceCapturer.html#//api/name/captureFormat) to indicate that you do not support audio capturing. This is what the SDK is looking for to determine if your custom device supports creating LocalAudioTracks or not.

Best,
Chris

**Comment by eigenl** [comment]
Interesting. I will investigate how or why could capture format be nil. Thank you for your response.
