### ISSUE TITLE
End the video call before didActivate function is called

### ISSUE THREAD

**Issue by ShaheenHabash** [twilio/twilio-video-ios#20]
#### Description
I am working on a video call application so I using Twilio for that in the app every things work fine except one thing .. that when I start to connect two person with each other and before the  didActivate function is called I click the home button of the phone so this make the didActivate not called .. and then I do the following to close the connection in the code (swift 4) and call this function with notification from the AppDelegete
 
#### Code
if let room = room, let uuid = room.uuid {
        performEndCallAction(uuid: uuid)
}
self.audioDevice.isEnabled = false
self.localAudioTrack?.isEnabled = false
self.audioDevice.block()
self.localVideoTrack?.isEnabled = false
self.localVideoTrack = nil

#### Expected Behavior
the app should close the call without any problem or popup screen

#### Actual Behavior
 the app show me the 'failed call' screen ..

#### Versions
All relevant version information for the issue.

#### Video iOS SDK
pod 'TwilioVideo'

#### Xcode
9.4

#### iOS Version
11.4

#### iOS Device
IPad Air 2
Iphone 6 +

**Comment by ceaglest** [comment]
Hey @ShaheenHabash,

Can you reproduce the "call failed' state via our [CallKit QuickStart](https://github.com/twilio/video-quickstart-swift/tree/master/VideoCallKitQuickStart), or just in your application code?

> pod 'TwilioVideo'

I'm going to assume that you are using version 2.2.1 then, unless your spec repo/Podfile.lock is out of date. Is this correct?

Best,
Chris

**Comment by piyushtank** [comment]
Closing an old ticket. Feel free to reach out to us if you have any questions.
