### ISSUE TITLE
SwiftUI support ?

### ISSUE THREAD

**Issue by quentinhayot** [twilio/twilio-video-ios#201]
Hi !

Is there any official instructions on how to use this SDK with SwiftUI ?
The iOS 13 migration guide only says that "Twilio is evaluating SwiftUI"... and iOS15 is around the corner.

I'm currently building an app which includes video calls. And I'd like to know if I should delay the implementation of this SDK or if nothing new is coming short term and I should find a way to make it work as it is.

Cheers !

**Comment by timrozum** [comment]
Hi @quentinhayot, 

We now have an example that uses SwiftUI. This was how `VideoView` was bridged: https://github.com/twilio/twilio-live-interactive-video/blob/main/apps/ios/LiveVideo/LiveVideo/Views/Stream/SwiftUIVideoView.swift

The bridging was relatively simple and we didn't encounter any major problems.

**Comment by cecruzmo** [comment]
For reference, this repo is based on SwiftUI: https://github.com/twilio/twilio-video-app-ios

**Comment by timrozum** [comment]
I think since our main reference app is now mostly SwiftUI, as @cecruzmo nicely pointed out, we can close this ticket.

Glad to hear feedback that SwiftUI examples are useful!
