### ISSUE TITLE
Compile for IOS simulator produce linker error

### ISSUE THREAD

**Issue by ATrotsenko** [twilio/twilio-video-ios#203]
### Description
When I try to build for IOS Simulator I get fail compile from Xcode, for  a real device everything compile without any problems

### Log form xcode
ld: warning: ignoring file /Users/aleksey/Library/Developer/Xcode/DerivedData/Squirrel-gwhzxajsootpnugfmufhrhqufgrb/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/TwilioVideo/TwilioVideo.framework/TwilioVideo, missing required architecture arm64 in file /Users/aleksey/Library/Developer/Xcode/DerivedData/Squirrel-gwhzxajsootpnugfmufhrhqufgrb/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/TwilioVideo/TwilioVideo.framework/TwilioVideo (2 slices)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_TVIEncodingParameters", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIH264Codec", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIVp8Codec", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIUserInterfaceTracker", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIG722Codec", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIPcmuCodec", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIPcmaCodec", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIAudioCodec", referenced from:
      objc-class-ref in VideoConferenceManager.o
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVICameraSourceOptions", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIVp9Codec", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVICameraSource", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVILocalVideoTrack", referenced from:
      objc-class-ref in VideoConferenceManager.o
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIIsacCodec", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVILocalAudioTrack", referenced from:
      objc-class-ref in VideoConferenceManager.o
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIVideoCodec", referenced from:
      objc-class-ref in VideoConferenceManager.o
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIConnectOptions", referenced from:
      objc-class-ref in VideoConferenceManager.o
  "_OBJC_CLASS_$_TwilioVideoSDK", referenced from:
      objc-class-ref in VideoConferenceManager.o
  "_OBJC_CLASS_$_TVIOpusCodec", referenced from:
      objc-class-ref in VideoConferenceLocalSource.o
  "_OBJC_CLASS_$_TVIRemoteParticipant", referenced from:
      objc-class-ref in VideoConferenceManager.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Integration
using Cocoapods 1.10.2
TwilioVideo (4.4.0)

#### Xcode
Version 12.5.1 (12E507)

#### iOS Version
14.5

#### iOS Device
IOS Simulator

### Work station
MacBook Pro 2020 M1

**Comment by ceaglest** [comment]
Hi @ATrotsenko,

The linker error is due to lack of arm64 simulator support in our current SDKs. This is added in 4.6.0-beta1 - see https://github.com/twilio/twilio-video-ios/issues/144.

Best,
Chris
