### ISSUE TITLE
ITMS-90562: Invalid Bundle - When using Swift Package

### ISSUE THREAD

**Issue by petrpavlik** [twilio/twilio-video-ios#216]
### Description

Integrating twilio video swift package seem to work when added directly into the app project file, but throws en error when adding into another swift package that is added into the app. It almost certainly has something to do with the fact that it's distributed as a binary package.

### Steps to Reproduce

1. Create a new app
2. Create a swift package VideoChat and import it into app bundle
3. add twilio video package into VideoChat package
4. try to upload the app to TestFlight

#### Expected Behavior

App is successfully processed by App Store connect.

#### Actual Behavior

Appstore connect returns error:
ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

#### Reproduces How Often

always

### Versions

All relevant version information for the issue.

#### Video iOS SDK

4.6.1 as swift package

#### Xcode

13.1

#### iOS Version

15

#### iOS Device

any

**Comment by ceaglest** [comment]
Hi @petrpavlik,

Thank you for reaching out. We haven't started looking into this issue yet but we did hear your request and will post and update when we have information to share.

> Integrating twilio video swift package seem to work when added directly into the app project file, but throws en error when adding into another swift package that is added into the app. It almost certainly has something to do with the fact that it's distributed as a binary package.

> Appstore connect returns error:
ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.

I'm pretty sure that you are correct. From what I've seen so far the paths to `TwilioVideo.xcframework` are not being preserved in the two level integration.

Best,
Chris

**Comment by wolfspy** [comment]
@petrpavlik

We are not able to reproduce the issue following the steps to reproduce using the latest Xcode 13.2.1 and Video SDK 4.6.3. Using the following setup, uploading to the App Store succeeds and the build processes without errors.

<img width="1297" alt="Screen Shot 2022-02-07 at 12 22 00 PM" src="https://user-images.githubusercontent.com/1680433/153025366-7bd83ddf-12d8-42d9-b27a-c3d9aa990bed.png">
<img width="750" alt="Screen Shot 2022-02-08 at 8 47 36 AM" src="https://user-images.githubusercontent.com/1680433/153025424-1b2d82ac-3a98-44be-ba65-7a2f8e795e8e.png">

If you still have this issue, please either provide further details on what you're doing differently than the above setup or a sample project using the latest Xcode 13.2.1 and Video SDK 4.6.3 that exhibits the problem.

**Comment by petrpavlik** [comment]
Thanks, we'll try again when we have a chance and raise a new issue if it still doesn't work for us.
