### ISSUE TITLE
Cocoapod listing: domain suspended

### ISSUE THREAD

**Issue by gsbernstein** [twilio/twilio-video-ios#222]
> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x)
> 
> If this is an issue with the SDK itself, file it here. If this is an issue with the QuickStart apps, please use [video-quickstart-ios](https://github.com/twilio/video-quickstart-ios/issues).
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

When you visit the cocoapod listing for this pod it says "this domain has been suspended"
https://cocoapods.org/pods/TwilioVideo

<img width="1576" alt="Screen Shot 2022-01-11 at 10 16 01 AM" src="https://user-images.githubusercontent.com/6655924/148998767-fd1ec99f-ce77-4302-a8bc-1f981b673e0c.png">

This seems to be the case for about half of twilio's pods

### Steps to Reproduce

1. Go to https://cocoapods.org/pods/TwilioVideo

#### Code

n/a

#### Expected Behavior

can view details about pod

#### Actual Behavior

see message about suspended domain 

#### Reproduces How Often

100%

#### Logs

n/a

### Versions

n/a

**Comment by wolfspy** [comment]
We do not control the content on https://cocoapods.org/pods/TwilioVideo

Cocoapods has resolved their internal domain issues and the page is returned to normal.
