### ISSUE TITLE
App Crashes after turning Video on/off multiple tims

### ISSUE THREAD

**Issue by virbedi** [twilio/twilio-video-ios#223]
> Before filing an issue please check that the issue is not already addressed by the following:
>
>  * [Video Guides](https://www.twilio.com/docs/api/video)
>  * [Changelog](https://www.twilio.com/docs/api/video/changelog-twilio-video-ios-version-2x)
> 
> If this is an issue with the SDK itself, file it here. If this is an issue with the QuickStart apps, please use [video-quickstart-ios](https://github.com/twilio/video-quickstart-ios/issues).
>
> Please ensure that you are not sharing any
[Personally Identifiable Information(PII)](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii)
or sensitive account information (API keys, credentials, etc.) when reporting an issue.

### Description

After getting on a video call, toggling the Video on/off button 3 times causes the call to freeze and app crashes.
This crash was being experienced on 4.6.2
Reverting to 4.4.0 fixed the issue 

### Steps to Reproduce

1. Get on a Video Call
2. Toggle video off/on Multiple times

#### Expected Behavior

Client Video turns on and off as expected 

#### Actual Behavior

App crashes

#### Reproduces How Often

Always

#### Logs

```
Crashed: MediaFactoryImpl::signaling 0x0x28289bf70
0  libsystem_kernel.dylib         0x25d88 __pthread_kill + 8
1  libsystem_pthread.dylib        0x674c pthread_kill$VARIANT$armv81 + 216
2  libsystem_c.dylib              0x72934 abort + 100
3  libc++abi.dylib                0x12cc0 __cxxabiv1::__aligned_malloc_with_fallback(unsigned long) + 126
4  libc++abi.dylib                0x12834 __cxa_deleted_virtual + 18
5  TwilioVideo                    0x6fa12c webrtc::Notifierwebrtc::VideoTrackInterface::FireOnChanged() + 64
6  TwilioVideo                    0x6fa20c webrtc::MediaStreamTrackwebrtc::VideoTrackInterface::set_enabled(bool) + 36
7  TwilioVideo                    0x6fa1bc webrtc::VideoTrack::set_enabled(bool) + 112
8  TwilioVideo                    0x43c098 void webrtc::ReturnType<bool>::Invoke<webrtc::VideoTrackInterface, bool (webrtc::VideoTrackInterface::)(bool), bool>(webrtc::VideoTrackInterface, bool (webrtc::VideoTrackInterface::)(bool), bool&&) + 40
9  TwilioVideo                    0x43c040 webrtc::MethodCall<webrtc::VideoTrackInterface, bool, bool>::Run() + 20
10 TwilioVideo                    0x4b6290 rtc::Thread::QueuedTaskHandler::OnMessage(rtc::Message) + 48
11 TwilioVideo                    0x4b5af4 rtc::Thread::Dispatch(rtc::Message*) + 136
12 TwilioVideo                    0x4b4a94 rtc::Thread::ProcessMessages(int) + 168
13 TwilioVideo                    0x4b5ed4 rtc::Thread::PreRun(void*) + 60
14 libsystem_pthread.dylib        0xad98 _pthread_start + 156
15 libsystem_pthread.dylib        0xe74c thread_start + 8
```

### Versions

All relevant version information for the issue.

#### Video iOS SDK
Installed via CocoaPods
This crash was being experienced on 4.6.2
Reverting to 4.4.0 fixed the issue

#### Xcode

13.2.1

#### iOS Version

13.7
15.1

#### iOS Device

iPhone 8 Plus, iPhone 7 Plus

**Comment by naresh-kumar-ios** [comment]
@virbedi are you publishing & unpublishing the video on tap ?

**Comment by scssrs** [comment]
@virbedi Hi! Have you found a solution to this problem?

**Comment by virbedi** [comment]
This issue has not come up in following versions so it can be marked as resolved. Thanks
