### ISSUE TITLE
Video Effects (Portrait) on iPad does not appear in control centre

### ISSUE THREAD

**Issue by magneticrob** [twilio/twilio-video-ios#226]
### Description

I have an app that uses the Twilio Video SDK for video calls. On iPads that support Centre Stage and Portrait blur, in my app it appears that only Centre Stage is available, whereas on Facetime and other video apps, both Centre Stage and "Portrait" are available (see screenshots)

Facetime:
<img width="849" alt="Screenshot 2022-03-08 at 09 56 32" src="https://user-images.githubusercontent.com/1032538/157215742-c8d7c84a-2bff-4b16-a9ba-ae61f6a50784.png">

My app:
<img width="692" alt="Screenshot 2022-03-08 at 09 56 42" src="https://user-images.githubusercontent.com/1032538/157215793-727d5cf3-72a8-4098-9be7-563c589edcd3.png">

Does anyone know why Portrait wouldn't show under Video Effects during a Twilio Video call? Does this work for anyone else?

### Steps to Reproduce

1. Start a video call on an iPad that supports Portrait & Centre Stage
2. Observe that under video effects, portrait is not visible

#### Expected Behavior

Portrait mode should be an available option under video effects

#### Actual Behavior

Portrait mode is not an available option under video effects

#### Reproduces How Often

100%

#### Logs
N/A

### Versions

All relevant version information for the issue.

#### Video iOS SDK

3.7.2 vis CocoaPods (Aware that this is quite old now, but would appreciate confirmation that this _does_ work on a newer release)

#### Xcode

13.2.1

#### iOS Version

15

#### iOS Device

Supported iPads:
iPad Pro 12.9-inch (5th generation)
iPad Pro 11-inch (3rd generation)
iPad (9th generation)
iPad mini (6th generation)

**Comment by ceaglest** [comment]
Hi @magneticrob,

It could be that the 3.7.2 SDK being built against iOS 13 is preventing the Portrait effect from being offered in Control Center. The 5.0 releases are built against iOS 15 where the Portrait video effect is available. 

@wolfspy do you know if upgrading would resolve the issue?

Best,
Chris

**Comment by wolfspy** [comment]
Using the Video App https://github.com/twilio/twilio-video-app-ios consuming the iOS Video SDK v5.1 on an iPad Pro 11inch 3rd gen - portrait mode is available.

Update to v5.1 first to see if that solves the issue. If it does not then you'll need to compare how you're consuming the SDK with https://github.com/twilio/twilio-video-app-ios to find the differences preventing portrait mode from showing. I would guess just updating the SDK will solve the problem however.
