### ISSUE TITLE
Unable to share AVCaptureVideoPreviewLayer with screenshare

### ISSUE THREAD

**Issue by souvickcse** [twilio/twilio-video-ios#23]
Hi, I am trying to share one view with small camera feed in it, but it is not rendering the camera feed, I am using AVCaptureVideoPreviewLayer for the camera feed, is there any thing else I need to do, or it is not possible. If it is not possible is there any wayaround?
Here is my code:

    let capturer: TVIVideoCapturer = TVIScreenCapturer.init(view: sharedView)
        if localVideoTrack != nil {
            localVideoTrack = nil
        }
        
        localVideoTrack = TVILocalVideoTrack.init(capturer: capturer, enabled: true, constraints: nil, name: "Screen")
        
        if localAudioTrack != nil {
            localAudioTrack = nil
        }
        localAudioTrack = TVILocalAudioTrack.init()
        
        let connectOptions = TVIConnectOptions.init(token: accessToken) { (builder) in
            builder.roomName = roomName
            builder.videoTracks = [self.localVideoTrack!]
            builder.audioTracks = [self.localAudioTrack!]
        }

sharedView is AVCaptureVideoPreviewLayer

**Comment by ceaglest** [comment]
Hi @souvickcse,

Are you using ReplayKit to capture the screen?

I haven't tried this use case personally, but my guess would be that Apple doesn't allow capturing of an `AVCapturePreviewLayer` via ReplayKit. One thing you could do is render the camera's video with a `TVIVideoView` instead.

Best,
Chris

**Comment by souvickcse** [comment]
Hi @ceaglest,
Thank you for your quick reply.
I am using TVIScreenCapturer I am not sure it is using ReplayKit internally or not. And are you suggesting I should replace AVCapturePreviewLayer with TVIVideoView for my custom camera preview?

**Comment by ceaglest** [comment]
Hey @souvickcse,

TVIScreenCapturer does not use ReplayKit, but I'd imagine the technique used to snapshot the contents of a UIView is not compatible with AVCapturePreviewLayer. If you want to stick with your current solution of TVIScreenCapturer then you should use TVIVideoView to render the TVILocalVideoTrack while you are also recording the screen.

Best,
Chris

**Comment by souvickcse** [comment]
Hi @ceaglest ,
As per your suggestion I have tried to use TVIVideoView as a super view of my AVCapturePreviewLayer, but it is making the AVCapturePreviewLayer view nil, whenever I am trying to access the AVCapturePreviewLayer it is nil.

**Comment by souvickcse** [comment]
Can I use MTKView for the TVIScreenCapturer? I can change my AVCapturePreviewLayer with MTKView for the camera feed.

**Comment by souvickcse** [comment]
Hi, I have tried with MTKView with TVIScreenCapturer, it is working fine. Thank you for your help.

**Comment by souvickcse** [comment]
Hi @ceaglest 
Can you please look into this :  https://github.com/twilio/video-quickstart-swift/issues/303
