### ISSUE TITLE
Support for Picture in Picture (PiP) [iOS 15+] and Multitasking Camera Access [iOS 13.5+]

### ISSUE THREAD

**Issue by sherbondy** [twilio/twilio-video-ios#235]
### Description

Related to:
https://github.com/twilio/video-quickstart-ios/issues/237

I thought it'd be worthwhile to file a dedicated issue in the Twilio Video iOS SDK project to capture these gaps, since I do think the iOS SDK would have to surface new capabilities in order to implement this functionality.

Without direct access to the underlying `AVCaptureSession` (for camera access) and some setup with `AVSampleBufferDisplayLayer`/`AVCaptureVideoPreviewLayer` (for PiP of remote and local video previews respectively), I think it is not currently possible for developers to implement these two "table stakes" feature enhancements for modern video apps on iOS, unless Twilio exposes new dedicated functionality in the iOS SDK.

**Picture in Picture:**

iOS 15 introduced the ability to use `AVSampleBufferDisplayLayer` or `AVCaptureVideoPreviewLayer` as the basis for PiP video rendering:
https://developer.apple.com/documentation/avkit/avpictureinpicturevideocallviewcontroller?changes=_1

**Multitasking Camera Access:**

Technically since iOS 13.5 (if you request the entitlement from Apple), it has likewise been possible to enable multitasking camera access. iOS 16 will make this capability generally available via a public API, but it requires configuring the underlying `AVCaptureSession` which Twilio currently wraps and does not directly surface access to (AFAIK):
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_avfoundation_multitasking-camera-access?changes=_1

Please let me know if I am mistaken, and if it is possible to access either of these capabilities at the application-code level without upstream changes to the iOS SDK!

#### Video iOS SDK

(Latest `5.1.0`)

#### Xcode

(Any)

#### iOS Version

Picture in Picture for video calls has been supported since iOS 15.0:
https://developer.apple.com/documentation/avkit/avpictureinpicturevideocallviewcontroller?changes=_1

Multitasking Camera access has actually been supported since iOS 13.5 with the proper entitlement (which is request-able from Apple), and will be supported in general availability for all developers in iOS 16:

https://developer.apple.com/documentation/avfoundation/avcapturesession/4013227-ismultitaskingcameraaccessenable?changes=_1

#### iOS Device

(Any device supporting iOS 13.5+ or 15.0+)

**Comment by johnhaney-lextech** [comment]
We have successfully implemented Multitasking Camera access in our app. Note that you do have to request (and get approved by Apple) to include the `com.apple.developer.avfoundation.multitasking-camera-access` entitlement for your particular app's Bundle Identifier.

**Comment by pawansharmaAccolite** [comment]
Yes bro @sherbondy we are trying for this i think until Twilio introduce some feature for this we can't do anything.

**Comment by piyushtank** [comment]
@pawansharmaAccolite @sherbondy 

We have just shipped TwilioVideo 5.3 with Picture-in-picture support. Check [this](https://github.com/twilio/video-quickstart-ios/issues/237#issuecomment-1306468063) out.

Closing this ticket as we are using [this](https://github.com/twilio/video-quickstart-ios/issues/237) ticket for picture-in-picture discussions.
