### ISSUE TITLE
PIcture in Picture Support for ios

### ISSUE THREAD

**Issue by pawansharmaAccolite** [twilio/twilio-video-ios#236]
Related to:
https://github.com/twilio/video-quickstart-ios/issues/237

when will Twilio SDK start support for PIP mode in ios and google meet, zoom already have this feature.
@twilio-sdk-build

I thought it'd be worthwhile to file a dedicated issue in the Twilio Video iOS SDK project to capture these gaps, since I do think the iOS SDK would have to surface new capabilities in order to implement this functionality.

Without direct access to the underlying AVCaptureSession (for camera access) and some setup with AVSampleBufferDisplayLayer/AVCaptureVideoPreviewLayer (for PiP of remote and local video previews respectively), I think it is not currently possible for developers to implement these two "table stakes" feature enhancements for modern video apps on iOS, unless Twilio exposes new dedicated functionality in the iOS SDK.

**Comment by piyushtank** [comment]
@pawansharmaAccolite

We have just shipped TwilioVideo 5.3 with Picture-in-picture support. Check [this](https://github.com/twilio/video-quickstart-ios/issues/237#issuecomment-1306468063) out.

Closing this ticket as we are using [this](https://github.com/twilio/video-quickstart-ios/issues/237) ticket for picture-in-picture discussions.
