### ISSUE TITLE
Peer-to-Peer Rooms: Mic Capture in background gets disabled when Room is empty

### ISSUE THREAD

**Issue by andyboyd** [twilio/twilio-video-ios#25]
### Description

When capturing the mic in an app that supports background audio connected to a Twilio room, the mic will be deactivated as soon as the app goes to the background if no one else is currently in the room.

### Steps to Reproduce

1. Enable Background Audio modes in the app
2. Connect to a Twilio room on device A
3. Connect on another device (device B) and verify that device A's mic is being captured
4. Background the app on device A, verify that the mic is still being sent to device B
5. Leave the room on device B, note that the red mic indicator disappears on device A
6. Reconnect to the room with device B.

#### Code

This can be reproduced on the video-quickstart app with no code changes, just enable the background audio capability.

#### Expected Behavior

Device B should reconnect and the audio should still be transmitted in both directions

#### Actual Behavior

Device A's mic is no longer being captured, and device B's audio is no longer being played on device A.

#### Reproduces How Often

100%

#### Video iOS SDK

2.4.0 via cocoapods

#### Xcode

10

#### iOS Version

12.0

#### iOS Device

iPhone X, 6S+, 7. Pretty sure it's all devices.

**Comment by andyboyd** [comment]
Note: this only happens on P2P rooms. Group rooms work fine, but we want to use P2P rooms.

**Comment by ceaglest** [comment]
Hi @andyboyd,

You are correct about the behavior in P2P Rooms, at least when using `TVIDefaultAudioDevice`. The problem when you're in an empty Peer-to-Peer Room is that there is no underlying PeerConnection open, and thus no audio actually being played/recorded by the device. I could imagine a workaround where we always play silence, even in an empty Room where we aren't being asked to play and/or record audio.

I'll chat with the team about this one.

Best,
Chris

**Comment by piyushtank** [comment]
Feel free to reach out to us if you have any questions.
