### ISSUE TITLE
Crash: twilio::signaling::PublisherHintsSignaling::sendClientResetMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)

### ISSUE THREAD

**Issue by ghost** [twilio/twilio-video-ios#253]
### Description
The crash happens when connecting a call.

### Steps to Reproduce

No exact steps to reproduce. The crash is found in Crahslytics

#### Reproduces How Often

2 crashes in last 7 days

#### Video iOS SDK

pod 'TwilioVideo', '~> 5.2'

#### Xcode

14.2

#### iOS Version

iOS 15.2.0

#### iOS Device

iPhone 12 (version 15.2.0), iPhone 8 (version 16.2.0)

#### Stack trace

Crashed: room.worker
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000050

> Crashed: room.worker
> 0  TwilioVideo                    0xfbf74 twilio::signaling::PublisherHintsSignaling::sendClientResetMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 156
> 1  TwilioVideo                    0x135830 twilio::signaling::PeerConnectionSignaling::onLocalVideoTrackCaptureParametersChanged(std::__1::shared_ptr<twilio::media::LocalVideoTrack>) + 1880
> 2  TwilioVideo                    0x1101f4 twilio::signaling::PeerConnectionManager::onLocalVideoTrackCaptureParametersChanged(std::__1::shared_ptr<twilio::media::LocalVideoTrack>) + 288
> 3  TwilioVideo                    0x172dfc twilio::signaling::RoomSignalingImpl::doOnLocalVideoTrackCaptureParametersChanged(std::__1::shared_ptr<twilio::media::LocalVideoTrack>) + 304
> 4  TwilioVideo                    0x185364 void rtc::MethodFunctor<twilio::signaling::RoomSignalingImpl, void (twilio::signaling::RoomSignalingImpl::*)(std::__1::shared_ptr<twilio::media::LocalVideoTrack>), void, std::__1::shared_ptr<twilio::media::LocalVideoTrack> >::CallMethod<0ul>(std::__1::integer_sequence<unsigned long, 0ul>) const + 84
> 5  TwilioVideo                    0x185304 webrtc::webrtc_new_closure_impl::ClosureTask<rtc::MethodFunctor<twilio::signaling::RoomSignalingImpl, void (twilio::signaling::RoomSignalingImpl::*)(std::__1::shared_ptr<twilio::media::LocalVideoTrack>), void, std::__1::shared_ptr<twilio::media::LocalVideoTrack> > >::Run() + 16
> 6  TwilioVideo                    0x555b38 webrtc::(anonymous namespace)::TaskQueueGcd::RunTask(void*) + 64
> 7  libdispatch.dylib              0x647c8 _dispatch_client_callout + 16
> 8  libdispatch.dylib              0x3f854 _dispatch_lane_serial_drain$VARIANT$armv81 + 604
> 9  libdispatch.dylib              0x402e4 _dispatch_lane_invoke$VARIANT$armv81 + 380
> 10 libdispatch.dylib              0x4a000 _dispatch_workloop_worker_thread + 612
> 11 libsystem_pthread.dylib        0x1b50 _pthread_wqthread + 284
> 12 libsystem_pthread.dylib        0x167c start_wqthread + 8

CompilerConnectionSerialQueue

> 0  libsystem_kernel.dylib         0x1114 mach_msg2_trap + 8
> 1  libsystem_kernel.dylib         0x129e0 mach_msg2_internal + 76
> 2  libsystem_kernel.dylib         0x12c1c mach_msg_overwrite + 384
> 3  libsystem_kernel.dylib         0x1608 mach_msg + 20
> 4  libxpc.dylib                   0x22084 _xpc_pipe_mach_msg + 52
> 5  libxpc.dylib                   0x21600 _xpc_pipe_routine + 352
> 6  libxpc.dylib                   0x3e88 _xpc_interface_routine + 180
> 7  libxpc.dylib                   0x45c8 _xpc_look_up_endpoint + 264
> 8  libxpc.dylib                   0xc1f0 _xpc_connection_bootstrap_look_up_slow + 284
> 9  libxpc.dylib                   0xed40 _xpc_connection_init + 992
> 10 libxpc.dylib                   0xd7fc _xpc_connection_activate_if_needed + 320
> 11 libxpc.dylib                   0xd8cc xpc_connection_resume + 92
> 12 Metal                          0x2ce1c XPCCompilerConnection::setupConnection() + 136
> 13 Metal                          0x317f4 XPCCompilerConnection::XPCCompilerConnection(int) + 72
> 14 Metal                          0x34cf0 invocation function for block in MTLCompilerConnectionManagerPrivate::buildRequest(unsigned int, MTLCompilerRequest*, bool, void (MTLCompilerError, NSObject<OS_dispatch_data>*, char const*) block_pointer) + 280
> 15 libdispatch.dylib              0x647c8 _dispatch_client_callout + 16
> 16 libdispatch.dylib              0x46b54 _dispatch_lane_barrier_sync_invoke_and_complete + 52
> 17 Metal                          0x33450 MTLCompilerConnectionManagerPrivate::buildRequest(unsigned int, MTLCompilerRequest*, bool, void (MTLCompilerError, NSObject<OS_dispatch_data>*, char const*) block_pointer) + 200
> 18 Metal                          0x3c94 -[MTLCompiler compileFunctionRequestInternal:frameworkLinking:linkDataSize:reflectionOnly:completionHandler:] + 5684
> 19 AGXMetalA11                    0x50f3c (Missing UUID d9de0e88ba083305b1cf6ecc190b9658)
> 20 AGXMetalA11                    0x4e274 (Missing UUID d9de0e88ba083305b1cf6ecc190b9658)
> 21 AGXMetalA11                    0x184f4 (Missing UUID d9de0e88ba083305b1cf6ecc190b9658)
> 22 AGXMetalA11                    0x2a870 (Missing UUID d9de0e88ba083305b1cf6ecc190b9658)
> 23 TwilioVideo                    0x297fc -[TVIMetalRenderer preparePipelineState:pixelFormat:] + 656
> 24 TwilioVideo                    0x2a26c -[TVIMetalRenderer render:frame:] + 368
> 25 TwilioVideo                    0x2fa40 -[TVIVideoView drawInMTKView:] + 472
> 26 MetalKit                       0x1a90 -[MTKView draw] + 156
> 27 MetalKit                       0xdd60 -[MTKViewDisplayLinkTarget draw] + 28
> 28 QuartzCore                     0x27614 CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) + 832
> 29 QuartzCore                     0x38698 display_timer_callback(__CFMachPort*, void*, long, void*) + 368
> 30 CoreFoundation                 0x76c34 __CFMachPortPerform + 172
> 31 CoreFoundation                 0x91f04 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 56
> 32 CoreFoundation                 0x93a30 __CFRunLoopDoSource1 + 512
> 33 CoreFoundation                 0x7758c __CFRunLoopRun + 2324
> 34 CoreFoundation                 0x7bb58 CFRunLoopRunSpecific + 584
> 35 GraphicsServices               0x1984 GSEventRunModal + 160
> 36 UIKitCore                      0x375628 -[UIApplication _run] + 868
> 37 UIKitCore                      0x3752a0 UIApplicationMain + 312
> 38 libswiftUIKit.dylib            0x2c240 UIApplicationMain(_:_:_:_:) + 100
> 39 Spring                         0xd368 main + 4341748584 (Extensions.swift:4341748584)
> 40 ???                            0x1bda89df0 (Missing)

com.apple.uikit.eventfetch-thread

> com.apple.uikit.eventfetch-thread
> 0  libsystem_kernel.dylib         0x1114 mach_msg2_trap + 8
> 1  libsystem_kernel.dylib         0x129e0 mach_msg2_internal + 76
> 2  libsystem_kernel.dylib         0x12c1c mach_msg_overwrite + 384
> 3  libsystem_kernel.dylib         0x1608 mach_msg + 20
> 4  CoreFoundation                 0x75f98 __CFRunLoopServiceMachPort + 156
> 5  CoreFoundation                 0x77148 __CFRunLoopRun + 1232
> 6  CoreFoundation                 0x7bb58 CFRunLoopRunSpecific + 584
> 7  Foundation                     0x3e208 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 208
> 8  Foundation                     0x3e104 -[NSRunLoop(NSRunLoop) runUntilDate:] + 60
> 9  UIKitCore                      0x49a2a4 -[UIEventFetcher threadMain] + 424
> 10 Foundation                     0x55d54 __NSThread__start__ + 704
> 11 libsystem_pthread.dylib        0x3060 _pthread_start + 116
> 12 libsystem_pthread.dylib        0x1688 thread_start + 8

**Comment by giowar90** [comment]
I have de same problem, @PiyushSinrojaTH could you solve it?

**Comment by ghost** [comment]
> I have de same problem, @PiyushSinrojaTH could you solve it?

@giowar90 , Not found solution. just updated the latest sdk.

**Comment by piyushtank** [comment]
@PiyushSinrojaTH Thanks for reaching out. We will look at the stack trace to see anything we find. Do you have logs or reproduction steps for the crash? they will be super useful for our team to debug the crash. Thanks.

**Comment by ghost** [comment]
@piyushtank ,  No exact steps to reproduce. The crash was found in Crahslytics.

**Comment by ramapal** [comment]
@PiyushSinrojaTH I took a look at the stack trace and cannot root cause the issue. I would need debug level logs to proceed further.

**Comment by piyushtank** [comment]
This is an old ticket, closing as there is no response. Please feel free to reopen or report a new ticket if you run into the issue.
