### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by ppluskota** [twilio/twilio-video-ios#268]
From [Apple docs](https://developer.apple.com/support/third-party-SDK-requirements/):
> Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. Signatures are also required in these cases where the listed SDKs are used as binary dependencies.

Could you please add a privacy manifest for this library? See the following URLs for additional information:
- https://developer.apple.com/news/?id=r1henawx
- https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by itsyasirali** [comment]
Hello Twilio Team,

I wanted to bring to your attention the upcoming requirement from the App Store, which mandates a privacy manifest for all applications starting May 1, 2024. While I understand that the Twilio SDK is scheduled for discontinuation by the end of this year, incorporating this feature would greatly assist developers like myself in maintaining compliance and avoiding disruptions. We appreciate your consideration and any effort you can put towards this update.

Thank you

**Comment by Mukeshawal** [comment]
Hello Twilio Team,

I understand that Twilio Video SDKs are being discontinued by the end of this year. But with upcoming requirements from App store,  which mandates a privacy manifest for all applications starting May 1, 2024, We would appreciate if you could incorporate privacy manifest files on the SDK so that we can stay compliant till we migrate to other SDKs. We would greatly appreciate your efforts towards it.

Thank you.

**Comment by winston-riley-zocdoc** [comment]
Any update here? May 1 is quickly approaching.

**Comment by andschdk** [comment]
Humbly asking, is Twilio Video obliged to include a privacy manifest?

**Comment by andschdk** [comment]
When running `grep -RHn "systemUptime" ~/Library/Developer/Xcode/DerivedData`

I get matches related to TwilioVideo in their dSYM files:
```
Binary file /Users/<my user>/Library/Developer/Xcode/DerivedData/<app>/SourcePackages/artifacts/twilio-video-ios/TwilioVideo/TwilioVideo.xcframework/ios-arm64_x86_64-simulator/dSYMs/TwilioVideo.framework.dSYM/Contents/Resources/DWARF/TwilioVideo matches
Binary file /Users/<my user>/Library/Developer/Xcode/DerivedData/<app>/SourcePackages/artifacts/twilio-video-ios/TwilioVideo/TwilioVideo.xcframework/ios-arm64/dSYMs/TwilioVideo.framework.dSYM/Contents/Resources/DWARF/TwilioVideo matches
Binary file /Users/<my user>/Library/Developer/Xcode/DerivedData/<app>/Build/Products/DebugDev-iphoneos/TwilioVideo.framework.dSYM/Contents/Resources/DWARF/TwilioVideo matches
```

**Comment by andschdk** [comment]
I got this from Twilio Support:

> Our engineering team informed that the Privacy Manifest will be added in our next version : iOS 5.8.1-rc1.
> For staying up to date with the Twilio Video IOS SDK releases keep an eye on the following github releases document - https://github.com/twilio/twilio-video-ios/releases

**Comment by ppluskota** [comment]
Twilio 5.8.1 (with Privacy Manifest) has been released. I'm closing this issue
