### ISSUE TITLE
Upload Privacy Policy

### ISSUE THREAD

**Issue by sumit-vts** [twilio/twilio-video-ios#272]
Apple says "Starting May 1, 2024: You'll need to include approved reasons for the listed APIs used by your app's code to upload a new or updated app to App Store Connect."

Please add privacy policy

**Comment by asemivragovs** [comment]
Hey @sumit-vts 
The latest Video SDK version [5.8.2](https://github.com/twilio/twilio-video-ios/releases/tag/5.8.2) contains a privacy manifest file with the listed APIs.
