### ISSUE TITLE
Invalid Executable. The executable '**/Frameworks/TwilioVideo.framework/ TwilioVideo' contains bitcode

### ISSUE THREAD

**Issue by vatsal-bk** [twilio/twilio-video-ios#275]
I am not able to upload a new Version Due to this from XCode 16. "**ENABLE_BITCODE**" is already set to **NO**

<img width="1262" alt="Screenshot 2024-09-18 at 4 26 15 PM" src="https://github.com/user-attachments/assets/0515e3ea-db48-4c54-b06f-5c446e97c7a8">

**Comment by bobiechen-twilio** [comment]
Hi @Vatsal4GVM 

We apologize for the inconvenience during the packaging process. Could you tell us the version of the Video iOS SDK used in the app? Please note that we have disabled bitcode support in [Video iOS SDK 5.5.0](https://www.twilio.com/docs/video/changelog-twilio-video-ios-latest#550-january-5-2023).

**Comment by vatsal-bk** [comment]
Hello @bobiechen-twilio 

I was using v3.2 and as per your suggestion I have upgraded the version and now issue has been resolved. Hence, Closing this issue

Thanks
