### ISSUE TITLE
Exception on iOS 18 with Xcode 16

### ISSUE THREAD

**Issue by vikas-re** [twilio/twilio-video-ios#276]
### Description

I have integrated Twilio Video iOS SDK into my application and it works fine on all iOS versions including iOS 18 when running with Xcode 15. But when I build and run using Xcode 16 it breaks with following exception:

**Thread 1: "View was already initialized: <Kure_Dev.VideoTrackStoringVideoView: 0x10a31b540;**

I have attached the stack trace for the same issue. Any help would be really appreciated. I am using the latest SDK version using cocoa pods.

<img width="1201" alt="Screenshot 2024-09-19 at 4 32 11 PM" src="https://github.com/user-attachments/assets/78486f3d-10dc-4ef9-bd4a-3a1b95cde90b">

### Versions

All relevant version information for the issue.

Video iOS SDK -> 5.8 via CocoaPods

Xcode -> 16.0

iOS -> 18.0

iOS Device -> iPhone 14 Pro

**Comment by gregoryteach** [comment]
Same here

**Comment by chawda** [comment]
@vikas-re @gregoryteach I added preview view programatically. This solves for me. On Storyboard I just added a UIView as container view.

            previewView = VideoView()
            previewView.translatesAutoresizingMaskIntoConstraints = false
            previewContainerView.addSubview(previewView)

            previewView.leadingAnchor.constraint(equalTo: previewContainerView.leadingAnchor).isActive = true
            previewView.trailingAnchor.constraint(equalTo: previewContainerView.trailingAnchor).isActive = true
            previewView.topAnchor.constraint(equalTo: previewContainerView.topAnchor).isActive = true
            previewView.bottomAnchor.constraint(equalTo: previewContainerView.bottomAnchor).isActive = true

**Comment by vikas-re** [comment]
Thanks @chawda This worked for me also.
