### ISSUE TITLE
Video not rendering on caller side

### ISSUE THREAD

**Issue by SandeepKhore** [twilio/twilio-video-ios#30]
Description:

We have implemented Twilio ios SDK. After connecting to room video is not rendering at caller end. We are using call kit with VoIP notification to get the call from the caller. User A makes to User B. User B receives notification, on receiving notification we have a custom delegate from which User B makes an API call and that API return Twilio video token and User B connects to the room, same API send a notification to User A and using that token User A also connects to the same room. But in this User A is not able to see the video of User B. In India calling is working perfectly but in US (New York) video is breaking at Caller side.

Steps to Reproduce:
1) Kill the app try making the call.
2) Put the app in background meanwhile, use another app and try making the call.
3) Put the app in the background, lock the device and try making the call.

#### Code
[TwilioVideo.zip](https://github.com/twilio/twilio-video-ios/files/2629567/TwilioVideo.zip)

#### Expected Behavior

The video should be available on both the user's devices. Self and remote view both should be visible.

#### Actual Behavior

Remote video is not showing at Caller side.

#### Reproduces How Often

In US(New York) region 6/10 times.
In US(Atlanta) it's working fine.
In India, it's working fine.

All relevant version information for the issue.

#### Video iOS SDK

pod 'TwilioVideo', '~> 2.5'

#### Xcode

10.1

#### iOS Version

12.1

#### iOS Device

iPod touch, iPhone 6, iPhone 7

Thanks,
Sandeep Khore

**Comment by paynerc** [comment]
@SandeepKhore,

I apologize for the late response on this issue. A couple questions for you. I don't think this is the case, but you mentioned about making the API call to get tokens. You are not using the same token for both user A and user B, correct? Each token needs to have a unique identity. The fact that you stated that this is working in India and Atlanta, but only 60% of the time from New York makes me believe that the tokens are correct. But I just wanted to clarify that.

Second, are you at least having audio flowing between the callers in New York, just not video?

It would be useful to see debug level log messages from the device that is not displaying the remote video. It would be helpful if you could turn on debug logging and send the captured output to support@twilio.com. In that email, include the log, the link to this ticket and state that you are working with Ryan and it will find its way to me. Hopefully from there we can diagnose what is occurring.

To turn on debug logging, you will need to run the following:

```
TwilioVideo.setLogLevel(.debug)
```

I typically do this in the `application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?)` delegate call back.

Again, please accept my apologies for not responding sooner. 

Ryan

**Comment by paynerc** [comment]
@SandeepKhore,

Just checking in to see if you had a chance to review my last message and have sent the requested logs. I have not found a corresponding ticket in our support system, but I will look again.

Please advise,

Ryan

**Comment by SandeepKhore** [comment]
Hey Ryan,

Apologies for late response. The issue is resolved by updating pod to the latest version.

Thanks
