### ISSUE TITLE
CRITICAL - iPhone XS to 8 Video chat stretched top to bottom looks weird! 

### ISSUE THREAD

**Issue by reallifeaxelrod** [twilio/twilio-video-ios#32]
### Description

1. on ios video cahtting from a iphone XS max to iPhone 8 Plus the video is super stretched out top to bottom and looks whacky! Does not look like a clean video chat like facetime. Instead its stetched out and look elongated.
This happens from iPhone X or XS max to iPhone 8 and 8 Plus i tired on all the phones for testing.

#### Expected Behavior

[What you expect to happen]

#### for it to look normal like facetime

[What actually happens]

#### Reproduces How Often -EVERY TIME

[What percentage of the time does it reproduce?] 100%

#### Logs

```

### Versions

All relevant version information for the issue.

#### Video iOS SDK

[e.g. 1.3.12 via CocoaPods]

#### Xcode

[e.g. 9.2]

#### iOS Version

[e.g. 11.2.6] 12.0 most recent. happens on every version this is not ios version specific. 

#### iOS Device

[e.g. iPhone 8 Plus] iphone 8, 8 plus, XS, XS Max

**Comment by piyushtank** [comment]
@nickpeist Thanks for reaching out. What version of iOS TwilioVideo SDK are you using? Also the Video SDK supports content modes on `TVIVideoView`, can you check the content mode set on the renderer?

**Comment by reallifeaxelrod** [comment]
I am the CEO of FanTazTech and I will have my Lead developer take over from here @MuhammadIftikharAftab

**Comment by ceaglest** [comment]
Hi @nickpeist @MuhammadIftikharAftab,

You can use `UIView.contentMode` with our `TVIVideoView` class. If you don't want any stretching or cropping then use `UIViewContentModeScaleAspectFit`. If you want cropping you should consider doing it on the sender side, if at all possible. Cropping on the sender is enabled by `TVICameraSource ` in 2.6.0. Take a look at [Video Source APIs - Making a Format Request](
https://www.twilio.com/docs/video/video-source-apis#making-a-format-request) for more information.

I'm closing this, as I think I've answered your original question and the ticket is old. If you need any more clarification then please let us know.

Regards,
Chris

**Comment by NaiyerAghaz** [comment]
hi @ceaglest my remote view video is stretching, when I display into the view? it's not solving dude what should the reason? Please help me out.

**Comment by ceaglest** [comment]
Hi @NaiyerAghaz,

You probably have the wrong UIViewContentMode on your TVIVideoView. Quoting myself:

> If you don't want any stretching or cropping then use UIViewContentModeScaleAspectFit. 

Thanks,
Chris

**Comment by NaiyerAghaz** [comment]
Thanks for your response @ceaglest I want to display full screen video and I had tried all mode like aspect fit, fill, centre but still video is stretching. and one more issue is coming when I am in call and I am going another app and again back to the video call screen video is being freeze. why is this happening please help me out.

**Comment by ceaglest** [comment]
Hi @NaiyerAghaz,

Since this issue was resolved, please open a new issue and provide information requested in the issue template like Room SID(s), perhaps a screenshot of what it looks like, and any relevant code snippets.

Thank you,
Chris
