### ISSUE TITLE
Unpublishing and republishing a media track might not be seen by Participants

### ISSUE THREAD

**Issue by paynerc** [twilio/twilio-video-ios#34]
**Affected Versions**

All 1.x and 2.x SDK releases.

**Description**

Unpublishing and republishing a `TVILocalAudioTrack` or `TVILocalVideoTrack` might not be seen by Participants in the following cases:
  
 * Peer-to-Peer: If a Participant is reconnecting, or the unpublish / publish operations occur very quickly.
 * Group Room: If the unpublish / publish operations occur very quickly.

**Solution**

Future mobile SDKs will adopt unified plan, and will also clone Tracks so that this race condition does not occur. In a Group Room, subscribers always see a cloned version of the publisher's Track.

**Workaround**

* Peer-to-Peer: Destroy the `LocalAudioTrack`, or `LocalVideoTrack` and associated Capturer/Source after unpublishing. Create and publish a new Track.
* Group: Wait several seconds after unpublishing a Track to re-publish it.

**Comment by sandeep9607** [comment]
Currently using version 3.4. do we get any solution to fix this?

**Comment by layanavg** [comment]
### Currently using version 3.7. 
We are having the same problem. we are using the **peer to peer** connection and is clearing the tracks before publishing, even then this occurs.is there any way to fix this

**Comment by paynerc** [comment]
As mentioned previously, the solution to this will be with the adoption of unified plan. While I cannot give an exact release date for this, I can say that it is actively being developed now. Stay tuned.

Ryan

**Comment by rafaelnobrekz** [comment]
@kierandonaldson why has this been marked complete when it is still a known issue? Won't it ever be fixed?

**Comment by rafaelnobrekz** [comment]
Now it's clear it won't be fixed 😭
