### ISSUE TITLE
ARKit & Screen Sharing

### ISSUE THREAD

**Issue by PrashantKT** [twilio/twilio-video-ios#39]
I am looking for functionality to develop where two or more people can share one screen among them, which is ARKit Sceneview  

Now Everyone is able to draw things in the real world using ARKIT (adding 3D objects).  And also able to talk using a microphone. 

is it possible using twilo-video-demo ?

**Comment by piyushtank** [comment]
@PrashantKT Thanks for reaching out. If you are getting video frames from ARKit Sceneview, you can feed the video frames to the Video SDK by writing your own custom capturer when you are connected to a Room. The passed video frames will be shared with the participants connected to the Room. See [this](https://github.com/twilio/video-quickstart-swift/blob/master/ARKitExample/ViewController.swift#L111) example on how to write custom capturer. 

Also, if you want other participant to draw 3D objects using ARKit, you will need a to pass metadata from the participant who is drawing on the video frame.  You may want to use our `TVIDataTrack` APIs to achieve this.

Unfortunately, we do not have sample app to demonstrate this exact behavior, we plan to add more sample apps to demonstrate more complex features.

Let me know if you have any questions.

**Comment by PrashantKT** [comment]
@piyushtank  Thanks for answer. I have tried to run ARkit Demo.  I have generated Two Access Token.  But doesn't seems to be working for me like both app starting  Not  ARCamear   Could you please guide. I have seen `TVIVideoSink` but don't able to understand how to use this class

**Comment by PrashantKT** [comment]
I am able to do that with TVIVideoView and TVIRemoteParticipant but question is , is it correct way? and Yes than what is diff of using TVIVideoSink vs TVIVideoCaptureConsumer

**Comment by PrashantKT** [comment]
And another question is if one of the application is terminated so Is there a  way to receive calls? Or I need to use the Twilio Voice SDK  for that?

**Comment by piyushtank** [comment]
@PrashantKT  Can you elaborate what does not work on ARKit Example? 

>  I have seen TVIVideoSink but don't able to understand how to use this class

You can write custom Video Source and provide video frames to video sdk. See the guide: https://www.twilio.com/docs/video/video-source-apis

> what is diff of using TVIVideoSink vs TVIVideoCaptureConsumer

`TVIVideoCaptureConsumer` is deprected APIs. You should use TVIVideoSink APIs instead. 

> And another question is if one of the application is terminated so Is there a way to receive calls? Or I need to use the Twilio Voice SDK for that?

To receive an incoming call with Video SDK, you need to write your own push notification handler. The iOS wakes the phone up if your app is not running when the voip push is received.
