### ISSUE TITLE
No transportId in TVIIceCandidateStats

### ISSUE THREAD

**Issue by aastlind** [twilio/twilio-video-ios#4]
### Description

We're fetching stats reports and want to be able to get TVIIceCandidateStats from active TVIIceCandidatePairStats, but the TVIIceCandidateStats objects doesn't have any value set to the property transportId which is needed to be able to filter this list.

### Steps to Reproduce

1. Connect 2 participants to a peer-to-peer room
2. Call getStatsWithBlock:-method from the room object.
3. Inspect iceCandidateStats.

#### Expected Behavior

Value attached to the property transportId, as stated in the documentation.

#### Actual Behavior

No value set to the property transportId.

#### Reproduces How Often

100%

### Versions

All relevant version information for the issue.

#### Video iOS SDK

1.3.9 and 2.0.0-beta2

#### Xcode

9.2

#### iOS Version

11.2.5

#### iOS Device

iPhone 8 Plus, iPhone 6s

**Comment by ceaglest** [comment]
Hey @aastlind,

I'm sorry about this bug. Though it was addressed as a part of other work, I believe that the `transportId` property is set in version 1.3.10+ and 2.0.0-preview9+. Since you reported using 2.0.0-beta2 I will double check this and get back to you.

Best,
Chris

**Comment by aastlind** [comment]
I’m sorry!
Tested 2.0.0-beta2 again and transportId is set! I’ve tested plenty of versions lately so I most probably remembered wrong.

Thank you for your answer, this issue can be closed.
