### ISSUE TITLE
ReplayKit ending a streaming session leaves the last frame frozen.

### ISSUE THREAD

**Issue by claudiul** [twilio/twilio-video-ios#40]
### Description

I am trying to share the devices screen to a twilio chat room via a broadcast extension. The stream starts but when I stop it from the control centre UI the last frame of the stream is still being presented.

### Steps to Reproduce

1. Share screen via broadcast extension to other users (they are connected to the room via web)
2. Stop broadcast extension streaming

#### Expected Behavior

The video stream stops and the default UI is restored.

#### Actual Behavior

The video stream stops and the last frame in the stream is presented indefinitely. 

#### Reproduces How Often

Seem to reproduce 100%

### Versions
I have reproduced this issue with the code in the ReplayKit Example. 

#### Xcode

10.2

#### iOS Version

12.2

#### iOS Device

All iPhone

**Comment by ceaglest** [comment]
Hi @claudiul,

Thanks for writing in. We recently fixed this issue in our [ReplayKitExample](https://github.com/twilio/video-quickstart-swift/blob/master/ReplayKitExample/BroadcastExtension/SampleHandler.swift), have you tried the latest commit? In your extension you should wait for your Room to disconnect before ending the broadcast. If you disconnect without waiting it is quite common for the final message to not reach the Server resulting in hung video (until the Participant times out).

Best,
Chris

**Comment by claudiul** [comment]
Hello,

Thank you for the speedy reply. I am using the version from the beginning of the month but I will try the latest version also. I managed to fix this by adding inter process communication from the broadcast extension to the app, as the app has no way of knowing when screen sharing has ended in order to resume standard streaming. 
I am not sure if my handling of the token is correct as I use the existing token to initiate video screen sharing, this seems to kick the initial video connection to screen share, and when I stop screen sharing I need to reconnect to the room to resume normal (from camera) video.

Best,
Claudiu

**Comment by ceaglest** [comment]
Hi Claudiu,

> I am using the version from the beginning of the month but I will try the latest version also.

I was getting ahead of myself before, the fix is actually in my [open PR](https://github.com/twilio/video-quickstart-swift/pull/376) which should be merged today.

> I managed to fix this by adding inter process communication from the broadcast extension to the app, as the app has no way of knowing when screen sharing has ended in order to resume standard streaming.

If I recall correctly there is an event you can use when the ReplayKit broadcast ends. I can double check with our example, and how it updates the UI.

> I am not sure if my handling of the token is correct as I use the existing token to initiate video screen sharing, this seems to kick the initial video connection to screen share, and when I stop screen sharing I need to reconnect to the room to resume normal (from camera) video.

Participant identities must be unique within the scope of a Room. If you want both Participants in the Room at the same time, then you would need to issue two tokens with two identities.

Best,
Chris

**Comment by ceaglest** [comment]
Hi,

We merged the PR I mentioned earlier. If you try the latest code on master the broadcast extension should correctly disconnect from the Room when a broadcast ends.

I'm out of the office until Monday, but if you have any more questions one of my team mates would be happy to help.

Best,
Chris

**Comment by claudiul** [comment]
Thank you very much for your reply. I'll try the latest code.Have a nice weekend.

Best,
Claudiu

**Comment by claudiul** [comment]
> Participant identities must be unique within the scope of a Room. If you want both Participants in the Room at the same time, then you would need to issue two tokens with two identities.

I'm not sure I understand this: I have a user user@company.com(this is the identity?) , he has received a token when joining the call. This is used for video call from device camera. If I need to screenshare from this user I need to get another token? Or does this imply I need another login (user_screenshare@company.com) to have both video and screen sharing???

**Comment by ceaglest** [comment]
Hi,

Sorry, it looks like I did not answer your final question.

> I'm not sure I understand this: I have a user user@company.com(this is the identity?) , he has received a token when joining the call. This is used for video call from device camera. If I need to screenshare from this user I need to get another token? Or does this imply I need another login (user_screenshare@company.com) to have both video and screen sharing???

Yes, our current recommendation is using two unique participant identities and two access tokens (like user@company.com, user_screenshare@company.com). The identities can also be any GUID that you prefer instead of an email.

Closing this issue out as you should no longer be experiencing frozen frames at the end of your ReplayKit session.

Best,
Chris
