### ISSUE TITLE
How to connect multiple participants to a single room

### ISSUE THREAD

**Issue by arshadsk5** [twilio/twilio-video-ios#41]
I wanted to connect multiple participants to a single room, i didn't find any code in google. Please help me out, in swift programming language.

**Comment by ceaglest** [comment]
Hi @arshadsk5,

Have you tried our [MultiPartyExample](https://github.com/twilio/video-quickstart-swift/tree/master/MultiPartyExample) app (written in Swift 4.2)? Each Participant needs to have their own device, but the app displays video for up to 4 Participants in a Room.

Best,
Chris

**Comment by paynerc** [comment]
@arshadsk5,

Was @ceaglest's suggestion regarding the MultiPartyExample app useful for answering your question? I am going to close this issue out but please feel free to reopen it if you have further questions.

Thank you,

Ryan
