### ISSUE TITLE
How to share Video in screen share with participants.

### ISSUE THREAD

**Issue by rashidabbas** [twilio/twilio-video-ios#43]
Hi I am using your sdk into iOS to share screen with participants using video call with source ScreenCapturer everything is working fine screen is share with participants but when I play video then participants did not get video they get only blank screen but when I stop video and come back any other page it shows fine.

please help. Thanks.

**Comment by ceaglest** [comment]
Hi,

This seems like a sample code question. I'm closing it since you've already filed 

https://github.com/twilio/video-quickstart-swift/issues/382

Best,
Chris
