### ISSUE TITLE
Replay Kit Conference not working

### ISSUE THREAD

**Issue by rashidabbas** [twilio/twilio-video-ios#44]
Hi I am using replay kit example provided by you and I am facing issue during start conference when I hit start conference button I show an error like. "Recording interrupted by multitasking and content resizing".

please help thanks.

**Comment by ceaglest** [comment]
Hi @rashidabbas,

Can you please provide us more info in: https://github.com/twilio/video-quickstart-swift/issues/322? Thank you.

I'm closing this issue, since the question is regarding sample code and not sdk code.

Cheers,
Chris
