### ISSUE TITLE
[Question] Feasibility to pause/resume video recording?

### ISSUE THREAD

**Issue by AnnieNinaJoyceV** [twilio/twilio-video-ios#54]
I would like to know whether we have the feasibility to pause/resume video recording on iOS side. A practical example would be like, I invite 3 of my friends to join a call. We want to start recording the video only when all of us join in as well as ability to pause the recording in between and resume later. Is this possible to implement? Please guide.

#### Video iOS SDK - 3.0.0-beta3
via Carthage
#### iOS Device - iPhone family

**Comment by ceaglest** [comment]
Hi @AnnieNinaJoyceV,

Thanks for your question. We don't currently support starting and stopping recordings on demand in a Group Room. One way you could accomplish the same behavior today is by using two Rooms, one with recording and one without recording. When you want recording to be used you could signal your Participants to connect to the 2nd Room with recording enabled and leave the first. This is easy to say, but not very trivial to implement, but I mention it for the sake of discussion.

I will check with our team to see if/when it might be possible to have this level of control over recordings.

Best,
Chris

**Comment by AnnieNinaJoyceV** [comment]
Hi @ceaglest,

Thanks for your response and adding this to enhancement.
Yea, the suggested solution would be very trivial and would not work in our case.
I think it is best to wait for it possibly getting developed.

**Comment by ceaglest** [comment]
Hello,

Stopping and starting a recording can be accomplished with the recording rules [API](https://www.twilio.com/docs/video/api/recording-rules).

Best,
Chris

**Comment by realies** [comment]
@ceaglest, how to accomplish pausing? Stopping and starting the room recording creates new recordings instead of appending more data to the initially created recordings.
