### ISSUE TITLE
Prioritise Frame Detail over Frame Rate for Camera Source

### ISSUE THREAD

**Issue by DanBlackwell** [twilio/twilio-video-ios#59]
### Description

I want to be able to prioritise having high quality images over a high frame rate when using a TVICameraSource. I can see that Twilio has the isScreencast flag for TVIVideoSource, and the description of the variable sounds like what I would like to achieve:

```
/**
 * Indicates that the content from this source is a screenshare. When a source produces screen content, encoders downstream
 * from the source optimize for detail (spatial resolution) over frame rate (temporal resolution).
 */
var isScreencast: Bool { get }
```

However as a get-only property, I can't figure out how to set this.

As an aside, inside the webRTC library, there is a an enum and corresponding instance var `contentHint` on the `VideoTrackInterface` (visible here: https://webrtc.googlesource.com/src/+/master/api/media_stream_interface.h), which also appears to give control over fluidity / detail priority. I'm unsure of whether it is possible, but perhaps exposing a method to set this might also be useful in my use case.

### Versions

N/A

**Comment by ceaglest** [comment]
Hey @DanBlackwell,

Thanks for your feedback, and sorry for the slow response from our team.

> I want to be able to prioritise having high quality images over a high frame rate when using a TVICameraSource. I can see that Twilio has the isScreencast flag for TVIVideoSource, and the description of the variable sounds like what I would like to achieve:

That makes sense to me. There are a few ways that you could accomplish this today:

1. Reduce the capture frame rate from 30 fps to ~15-20 fps. This has a natural effect of reducing the amount of downscaling that occurs when the network is constrained.
2. (Hacky) Re-define -[TVICameraSource isScreencast] in a category. This will get you the rate allocation and quality scaling behavior that you are looking for.
3. (Hacky) Subclass TVICameraSource. We wouldn't normally recommend this, but same outcome as 2.

> I'm unsure of whether it is possible, but perhaps exposing a method to set this might also be useful in my use case.

Yes, this is the what we would like to expose as an API in the future. The older screencast property is actually mapped to one of the contentHint values internally. I'm sorry that I don't have an ETA on when, but we can keep this ticket open to capture the feature request.

Best,
Chris

**Comment by morninng** [comment]
@ceaglest 

> (Hacky) Re-define -[TVICameraSource isScreencast] in a category. This will get you the rate allocation and quality scaling behavior that you are looking for.
> (Hacky) Subclass TVICameraSource. We wouldn't normally recommend this, but same outcome as 2.

Is this still valid way to control the quality of video?
or using network badwidth pofile can do the same effect?

I want to know the best way to achieve `high quality images over a high frame rate`
