### ISSUE TITLE
Crash on EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by perlasivakrishna** [twilio/twilio-video-ios#62]
I'm using TwilioVideo 2.10.2, Crash is happened in production Build. After pod update no crashes happened. here is the crash logs.
[crashlog copy.txt](https://github.com/twilio/twilio-video-ios/files/3812613/crashlog.copy.txt)

**Comment by paynerc** [comment]
@perlasivakrishna,

Can you provide some context surrounding the crash? Also, it doesn't appear that this crash is happening with the `2.10.2` version of TwilioVideo.

Looking at the crash report, I notice the `Beta Identifier:` entry. This tells me that the report was generated from a user via TestFlight. I am assuming that when you are building and distributing to TestFlight, you are recompiling BitCode. This causes a new version of TwilioVideo to be compiled as well, and changed the UUID of the framework. Do you have access to the updated `TwilioVideo.framework.dSYM` file that should have been created? I believe I am going to need to to symbolicate the crash report and determine what this call inside TwilioVideo is doing:

```
0   TwilioVideo                   	0x00000001048b3888 0x104404000 + 4913288
```

Thank you,

Ryan

**Comment by paynerc** [comment]
@perlasivakrishna,

It's been awhile since I requested further information. I am going to close this issue, but please feel free to reopen it if you are still experiencing this crash and are able to provide further information.

Thank you,

Ryan

**Comment by neuralxmasaki** [comment]
I am experiencing the same issue. Could you guys tell me how to solve it? 
We use Testflight distribution on IOS as well.
