### ISSUE TITLE
RoomDelegate cannot invoked when set delegate after connecting room

### ISSUE THREAD

**Issue by tomosaaan** [twilio/twilio-video-ios#63]
### Description

Hi. I migrated sdk version `2.10.0` to `3.0.1`.
Then, I cannot invoked RoomDelegate methods suddenly.
I know that the way isn't recommended.

But why can't I set delegate in version `3.0.1` ?

```
 * @discussion It is recommended that this property is only accessed on the `delegateQueue` specified in the `TVIConnectOptions`
 *  when connecting to the room. If no explicit `delegateQueue` was provided, the main dispatch queue should be used.
```

### Steps to Reproduce

1. connect without delegate object
2. break point check on `RoomDelegate`  methods.

#### Code

```swift
let options = ConnectOptions(token: tokenContext.accessToken) { builder in
    builder.roomName = roomName
    builder.audioTracks = [audioTrack]
    builder.dataTracks = [dataTrack]
}
let room = TwilioVideoSDK.connect(options: options, delegate: nil)

room.delegate = self // Cannot set delegate object ?
```

#### Reproduces How Often

every time

### Versions

All relevant version information for the issue.

#### Video iOS SDK
3.0.1 via Cocoapods

#### Xcode
11.0

#### iOS Version
13.x
11.x

#### iOS Device
iPhone 6
iPhone X

**Comment by paynerc** [comment]
Hey @tomokitakahashi,

I just altered the Video QuickStart code to set the delegate after calling `.connect()` and placed breakpoints into the various delegate methods and they are being invoked.

```
        ...
        // Preparing the connect options with the access token that we fetched (or hardcoded).
        let connectOptions = ConnectOptions(token: accessToken) { (builder) in
            
            // Use the local media that we prepared earlier.
            builder.audioTracks = self.localAudioTrack != nil ? [self.localAudioTrack!] : [LocalAudioTrack]()
            builder.videoTracks = self.localVideoTrack != nil ? [self.localVideoTrack!] : [LocalVideoTrack]()
            
            // Use the preferred audio codec
            if let preferredAudioCodec = Settings.shared.audioCodec {
                builder.preferredAudioCodecs = [preferredAudioCodec]
            }
            
            // Use the preferred video codec
            if let preferredVideoCodec = Settings.shared.videoCodec {
                builder.preferredVideoCodecs = [preferredVideoCodec]
            }
            
            // Use the preferred encoding parameters
            if let encodingParameters = Settings.shared.getEncodingParameters() {
                builder.encodingParameters = encodingParameters
            }

            // Use the preferred signaling region
            if let signalingRegion = Settings.shared.signalingRegion {
                builder.region = signalingRegion
            }
            
            // The name of the Room where the Client will attempt to connect to. Please note that if you pass an empty
            // Room `name`, the Client will create one for you. You can get the name or sid from any connected Room.
            builder.roomName = self.roomTextField.text
        }
        
        // Connect to the Room using the options we provided.
        room = TwilioVideoSDK.connect(options: connectOptions, delegate: nil)

        if let room = room {
            room.delegate = self
        }

        ...
```

I am wondering here what is the lifecycle of `self` in this code?  The `delegate` property on `TVIRoom` is weak, therefore if `self` is released, the Room's delegate will then be `nil`.

What I don't understand is why this would have changed between `2.10.0` and `3.0.1`. The `delegate` property on `TVIRoom` has **always** been weak.

Was there any other changes in your code surrounding the ownership of `self` in the example you provided?

Ryan

**Comment by paynerc** [comment]
@tomokitakahashi,

It's been a while since this ticket was open and I requested more information. I am going to assume that you have worked out the issue. If you are still having issues, please feel free to reopen this issue and provide further information.

Thank you,

Ryan
