### ISSUE TITLE
Media connection failed or Media activity ceased

### ISSUE THREAD

**Issue by yaalisri** [twilio/twilio-video-ios#64]
### Description

I am getting the below issue sometimes on using programmable video with ARKit

### Steps to Reproduce

1. Connect to a room in one device. First device shares video screen with ARKit
2. Connect to the same room in second device. No AR view here. Normal video.
3. Second device is black and doesn't load the remote view of 1st device

#### Code

```swift
// Code that helps reproduce the issue

if (accessToken == "TWILIO_ACCESS_TOKEN") {
            do {
                accessToken = try TokenUtils.fetchToken(url: tokenUrl)
            } catch {
                let message = "Failed to fetch access token"
                logMessage(messageText: message)
                return
            }
        }
        
        // Prepare local media which we will share with Room Participants.
        self.prepareLocalMedia()
        
        let dataTrackOptions = DataTrackOptions.init { (builder) in
            builder.isOrdered = true
            //            builder.name = "Technician"
            builder.name = "Supervisor"
        }
        
        self.localDataTrack = LocalDataTrack(options: dataTrackOptions)
        
        // Preparing the connect options with the access token that we fetched (or hardcoded).
        let connectOptions = ConnectOptions(token: accessToken) { (builder) in
            
            // Use the local media that we prepared earlier.
            builder.audioTracks = self.localAudioTrack != nil ? [self.localAudioTrack!] : [LocalAudioTrack]()
            builder.videoTracks = self.localVideoTrack != nil ? [self.localVideoTrack!] : [LocalVideoTrack]()
            builder.dataTracks = [self.localDataTrack]

            // Use the preferred audio codec
            if let preferredAudioCodec = Settings.shared.audioCodec {
                builder.preferredAudioCodecs = [preferredAudioCodec]
            }
            
            // Use the preferred video codec
            if let preferredVideoCodec = Settings.shared.videoCodec {
                builder.preferredVideoCodecs = [preferredVideoCodec]
            }
            
            // Use the preferred encoding parameters
            if let encodingParameters = Settings.shared.getEncodingParameters() {
                builder.encodingParameters = encodingParameters
            }
            
            // Use the preferred signaling region
            if let signalingRegion = Settings.shared.signalingRegion {
                builder.region = signalingRegion
            }
            
            builder.roomName = "RemoteAssistance"

            // The name of the Room where the Client will attempt to connect to. Please note that if you pass an empty
            // Room `name`, the Client will create one for you. You can get the name or sid from any connected Room.
        }
        
        // Connect to the Room using the options we provided.
        room = TwilioVideoSDK.connect(options: connectOptions, delegate: self)
        
        self.showRoomUI(inRoom: true)
```

#### Expected Behavior

Screen share should not cease. 

#### Actual Behavior

Screen share is not starting at all

#### Reproduces How Often

Sometimes

#### Logs

```
// Log output when the issue occurs
2019-11-08 18:01:22.490001+0530 PhillipsRemote[2142:513285] Connected to room RemoteAssistance as Optional("identity")
2019-11-08 18:01:22.579931+0530 PhillipsRemote[2142:513285] Subscribed to 4b11eA95e4dCd7f360DfBA5a40bc3aCA audio track for Participant Technician
2019-11-08 18:01:22.580070+0530 PhillipsRemote[2142:513285] Subscribed to e8F3aC15cdCDbDFB56930fAFaaE1211c video track for Participant Technician
2019-11-08 18:01:22.607058+0530 PhillipsRemote[2142:513285] provider:didActivateAudioSession:
2019-11-08 18:01:22.808327+0530 PhillipsRemote[2142:513285] Reconnecting to room RemoteAssistance, error = Error Domain=com.twilio.video Code=53405 "Media connection failed or Media activity ceased" UserInfo={NSLocalizedDescription=Media connection failed or Media activity ceased, NSLocalizedFailureReason=ICE connection failed}
```

#### Video iOS SDK

'TwilioVideo', '3.0.0-beta4' via cocoapods

#### Xcode

Xcode 10.3

#### iOS Version

iOS 12.3.1

#### iOS Device

iPhone 10

**Comment by paynerc** [comment]
@yaalisri,

Sorry for the late response. Are you still experiencing this issue? I see you are using `3.0.0-beta4`. `3.0.1` was released on November 5. Can you try with the most recent version f the SDK and let me know if you are still seeing this issue?

Ryan

**Comment by paynerc** [comment]
@yaalisri,

It's been a while since I suggested trying a newer version of the SDK to see if you were still experiencing the issue.

I am going to close this issue at this time, but feel free to reopen it if you have new information.

Thank you,

Ryan

**Comment by ChiragGajjar** [comment]
Hello, 
I am getting the below issue using programmable video. Please have a look 

**pod 'TwilioVideo', '~> 3.0.1'**


Attempting to connect to room Ronak Parmar09:30 am-09:45 am
Connected to room Ronak Parmar09:30 am-09:45 am as ap5ScQzW
Room Conected

Participant test123 connected with 1 audio and 1 video tracks
Participant RoomRonak Parmar09:30 am-09:45 am connected 
Subscribed to audio track for Participant test123
Subscribed to Camera video track for Participant test123


Reconnecting to room Ronak Parmar09:30 am-09:45 am, error = Error Domain=com.twilio.video Code=53405 "Media connection failed or Media activity ceased" UserInfo={NSLocalizedDescription=Media connection failed or Media activity ceased, NSLocalizedFailureReason=ICE connection failed}

Thanks

**Comment by Adilsheikh1** [comment]
I am getting an error messsage on video call

UserID: 3823  UserType:1  AppVersion: 3.13.44  Time Stamp: 1606289444417 | Date: 25/11/2020 08:30:44  [Call connected view-  Log Type: Error]:  Room disconnected with error:  Optional(Error Domain=com.twilio.video Code=53405 "Media connection failed" UserInfo={NSLocalizedDescription=Media connection failed})

room_sid: RM51c00d99f2887a88a43c414c85257d49
