### ISSUE TITLE
SDK version with bitcode disabled

### ISSUE THREAD

**Issue by salmojunior** [twilio/twilio-video-ios#67]
### Description

Due to some other third party dependence which broke bitcode compatibility we had to disable it for now in our project but TwilioVideo sdk is the only Vendor sdk we use in which we cannot change bitcode property during build time. Is it possible to provide one version with bitcode disabled?

Thank you!

#### Video iOS SDK

3.0.1 via CocoaPods

#### Xcode

11.1

#### iOS Device

All devices

**Comment by ceaglest** [comment]
Hi,

I think you already discovered this, but you can always strip the bitcode segments from Twilio Video if you don't want them.

Have a good day,
Chris
