### ISSUE TITLE
Recording Audio when twilio video is On

### ISSUE THREAD

**Issue by perlasivakrishna** [twilio/twilio-video-ios#68]
I have an audio recording feature in my app.  I'm recoding audio during some process using AVAudioRecorder, Once Video call comes recording is muted until video call ends after that it continues as normally. 

When i get normal phone call and face time call i can't record due to privacy, 
I want to know is it possible to record when doing twilio call or it is kind of same restriction. 

Thank you.

**Comment by ceaglest** [comment]
Hi @perlasivakrishna,

Twilio Video operates a VPIO Audio Unit configured for playback, recording, and echo cancellation. This is probably interfering with AVAudioRecorder. We have [an example](https://github.com/twilio/video-quickstart-ios/tree/master/AudioSinkExample) that uses TVIAudioSink to record with AVAssetWriter, which could be an alternative for audio recording.

Best,
Chris

**Comment by piyushtank** [comment]
Closing an old ticket. Feel free to reach out to us if you have any questions.
