### ISSUE TITLE
Crashed: IncomingVideoStream EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by aksthelion** [twilio/twilio-video-ios#71]
Twilio video 2.6
Random crash, can't reproduce, don't have any more log

Crashed: IncomingVideoStream EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000094981dbe1ea0

Crashed: IncomingVideoStream
0 TwilioVideo 0x101178414 hidden#23214 + 944896
1 TwilioVideo 0x10117839c hidden#23214 + 944776
2 TwilioVideo 0x1011b9744 hidden#25871 + 1211952
3 TwilioVideo 0x100edf5ac hidden#5835 + 308084
4 TwilioVideo 0x100ec873c hidden#4694 + 214276
5 TwilioVideo 0x100ec88d0 hidden#4702 + 214680
6 TwilioVideo 0x100ef0230 hidden#6621 + 376824
7 libdispatch.dylib 0x1a01cb184 _dispatch_client_callout + 16
8 libdispatch.dylib 0x1a01a8710 _dispatch_lane_serial_drain$VARIANT$armv81 + 564
9 libdispatch.dylib 0x1a01a9128 _dispatch_lane_invoke$VARIANT$armv81 + 400
10 libdispatch.dylib 0x1a01b243c _dispatch_workloop_worker_thread + 576
11 libsystem_pthread.dylib 0x1a021af88 _pthread_wqthread + 276
12 libsystem_pthread.dylib 0x1a021dad4 start_wqthread + 8

**Comment by paynerc** [comment]
@aksthelion,

Do you happen to have the entire crash report for this? It would be helpful to be able to attempt to symbolicate the report to know exactly where it is crashing. Without further information there is not much I can do with this information presently.

Ryan

**Comment by ceaglest** [comment]
Seconding Ryan's request for more info. It's possible the crash you are experiencing was fixed in [3.0.1](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-3x#301-november-5-2019), but its tough to tell with only the one thread.

**Comment by aksthelion** [comment]
> Seconding Ryan's request for more info. It's possible the crash you are experiencing was fixed in [3.0.1](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-3x#301-november-5-2019), but its tough to tell with only the one thread.

I'll try with latest release. 

I'm unable to provide detailed log as it is random error in live app and the log is already symbolicate as it is Crashlytics log.

**Comment by paynerc** [comment]
@aksthelion,

OK. Try out the latest release and if the crash still occurs, please let us know. I am going to close this issue as there is nothing actionable that we can do at this point.

Thank you,

Ryan

**Comment by aksthelion** [comment]
I can't update to 3.0.1 as it doesn't support iOS 10.3. So I'm stuck.
