### ISSUE TITLE
Crash EXC_BAD_ACCESS when participant joins 

### ISSUE THREAD

**Issue by Davtyanag** [twilio/twilio-video-ios#73]
### Description

Twilio causes an app crash randomly. 

### Steps to Reproduce

Tester told me that happens when participant joins to call.

#### Reproduces How Often

This issue is very rare.

#### Logs

Attached.
[bugsnag_error_stacktrace_EXC_BAD_ACCESS_event_5e3030310055f78c3c3a0000.txt](https://github.com/twilio/twilio-video-ios/files/4122720/bugsnag_error_stacktrace_EXC_BAD_ACCESS_event_5e3030310055f78c3c3a0000.txt)

#### Video iOS SDK

3.0.0

#### Xcode

11.2.1

#### iOS Version

iOS 12.4.2

#### iOS Device

[iPhone7,2]

**Comment by paynerc** [comment]
@Davtyanag ,

Do you happen to have access to any of the log files surrounding this issue when it occurred?

Thank you,

Ryan

**Comment by Davtyanag** [comment]
@paynerc Hi Ryan, unfortunately I don't, but If happens while debugging I will share.
Thank you!

**Comment by paynerc** [comment]
OK. If you do happen to receive this again and have logs, please reopen this issue. I am going to close it for the time being as I don't have enough information to go on to attempt to resolve the crash.

Thank you,

Ryan
