### ISSUE TITLE
No audio when answer from background in iOS13

### ISSUE THREAD

**Issue by azizimarouan** [twilio/twilio-video-ios#74]

**Comment by ceaglest** [comment]
Hey @azizimarouan,

Could give us more information on how you are reproducing the no audio scenario? The [issue template](https://github.com/twilio/twilio-video-ios/blob/Releases/.github/ISSUE_TEMPLATE.md) gives a summary of what we usually ask for.

In this case it would help to know which version of iOS 13 is being used, on what device and how your app calls the Video APIs. Can the issue be reproduced in the [CallKit QuickStart](https://github.com/twilio/video-quickstart-ios/tree/master/VideoCallKitQuickStart) as well?

Best,
Chris

**Comment by varun-gadre** [comment]
Do this, it worked on my application when we made the call without the UICallKit. 

https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio

**Comment by ceaglest** [comment]
@varun-kernellabs Yes, you will need the background audio entitlement in order for audio to work with Twilio Video while your app is backgrounded. Our example apps all ask for this entitlement. 

@azizimarouan can you tell us more about your app setup?

**Comment by azizimarouan** [comment]
Hi @ceaglest and @varun-kernellabs ,

Thank you for your answers but enabling audio in Background Modes does not solve the problem.
I am using CallKit to report new incoming calls after a voip push notification, when the screen is unlocked and the app is in foreground , everything is ok, but when the screen is locked, no sound at all, and also when it is unlocked but the app is in background or closed.
Many people have the same issue but they didn't find a solution, like this <a href="https://forums.developer.apple.com/thread/119764">link</a> and <a href="https://forums.developer.apple.com/message/370303#370303">link</a>.
I found the same <a href="https://github.com/twilio/twilio-video-ios/issues/8#issuecomment-528970678"> issue </a> closed in your repository and also no solution.
I also tested that on VideoCallKitQuickStart, you do not display the CallKit UI when the screen is locked, you just display a notification and the user has to tap it and unlock the screen, and this is not what I want.
Can you fix the problem or you think that it is the problem of the iOS13 and apple has to fix that ?

Thank you.
