### ISSUE TITLE
Video stream freezes after user enter background

### ISSUE THREAD

**Issue by iosdmd** [twilio/twilio-video-ios#80]
### Description

Once user enter background and back to app while video connection established between 2 users - it freezes.

### Important! 

Issue reproduces not every time, 2-3 times out of 10 attempts

### Steps to Reproduce

1. Connect the room with 2 users, start streaming video
2. User1 enters background
3. User1 return to the application
4. Local video track stop streaming, preview view shows last recorded frame

#### Code
I tried unpublishVideoTrack when enter background and again publishVideoTrack when app become active again, but it doesn't help - issue reproduces randomly

#### Expected Behavior

When user1 back to app - user2 should be able to see user1's video stream

#### Actual Behavior

When user1 back to app - user2 doesn't see user1's video stream

#### Reproduces How Often

2-3 times out of 10 attempts

#### Video iOS SDK

3.2.1 via CocoaPods

#### Xcode

11.2.1

#### iOS Version

tested on iOS 12.1.2 and iOS 13.3.1

#### iOS Device

iPhone SE, iPhone 7, iPhone X, iPhone Xr

**Comment by iosdmd** [comment]
@ceaglest can you take a look at this?

**Comment by paynerc** [comment]
@iosdmd,

What you are describing above sounds very similar to the issue reported in the Quickstart repo, [#455](https://github.com/twilio/video-quickstart-ios/issues/445). Please take a look and see if that will solve the issue you are seeing.

If it doesn't, the next thing I would ask is to see some debug level logs for the both participants when this issue occurs so we can try and track it down that way.

Thank you,

Ryan

**Comment by paynerc** [comment]
@iosdmd ,

Just checking in to see if you are still experiencing this issue or if you it resolved.

Thank you,

Ryan

**Comment by paynerc** [comment]
@iosdmd ,

As I mentioned previously, the issue you are describing sounds very familiar to [#455](https://github.com/twilio/video-quickstart-ios/issues/445). `3.2.5` was released last week which addresses this issue, see [this comment](https://github.com/twilio/video-quickstart-ios/issues/445#issuecomment-618689296) for further information.

I am going to close this issue now, but feel free to reopen it if you are still experiencing this issue after upgrading to `3.2.5`.

Thank you,

Ryan
