### ISSUE TITLE
App crashing on Specific Device only

### ISSUE THREAD

**Issue by ankitappstreet** [twilio/twilio-video-ios#83]
I am getting a crash every time on only one device with the given description and Crash Reports: >
>  * [Device Description](https://ibb.co/sC2mH0X)
>  * [Crash Report 1](https://drive.google.com/file/d/1dt2e5S8j42fTOXRpx68QGv2HUrWBfAOx/view?usp=sharing)
>
### Description
The crash is only happening on 1 device and its working fine on others and thats a device for a user and i am unable to debug on the given device. But from crashlytics i could see that crash is happening somewhere inside the Twilio Video SDK.

1. [On viewDidLoad i am initilizingLocalTracks()]
2. [then doing enterRoom() code is given below]

#### Code
```swift
// Code that helps reproduce the issue
```
    private func initilizeLocalTracks() {
        // Create a video track with the capturer.
        
        localAudioTrack?.isEnabled = true
        let cameraSourceOptions = CameraSourceOptions.init { (block) in
            block.enablePreview = true
            
        }
       
        cameraSource = CameraSource.init(options: cameraSourceOptions, delegate: self)
        guard let _cameraSource = cameraSource else {
            print("Unable to create Camera Source")
            return
        }
        localVideoTrack = LocalVideoTrack(source: _cameraSource, enabled: true, name: "MyCamera")
        if let _frontCamera = frontCamera {
            _cameraSource.startCapture(device: _frontCamera)
        } else if let _backCamera = backCamera {
            _cameraSource.startCapture(device: _backCamera)
        } else {
            self.showErrorPopup(error: UNError.customError(message: "Camera not available."))
        }
    }    
    private func enterRoom() {
        UNLoader.addLoaderToWindow()
        NetworkManager.shared.videoTokenService(completion: { [weak self] result, error in
            UNLoader.hideLoader()
            guard let _result = result, let _token = _result["token"] as? String else {
                self?.showErrorPopup(error: error)
                return
            }
            print("_token= \(_token)")
            let connectOptions = ConnectOptions.init(token: _token) { (builder) in
                builder.roomName = self?.roomIdentity
                if let audioTrack = self?.localAudioTrack {
                    builder.audioTracks = [ audioTrack ]
                }
                if let videoTrack = self?.localVideoTrack {
                    builder.videoTracks = [ videoTrack ]
                }
            }
            self?.room = TwilioVideoSDK.connect(options: connectOptions, delegate: self)
            if self?.room == nil {
                self?.showErrorPopup(error: UNError.unableToCreateRoomError())
            }
            print("self?.room?.name= \(self?.room?.name ?? "No Room Name")")
        })
    }

#### Expected Behavior

[The app should not crash]

#### Actual Behavior

[App is Crashing]

#### Reproduces How Often

[It happens only on a given device]

**Comment by paynerc** [comment]
@ankitappstreet,

After reviewing this crash report, it has a signature that is very similar to a crash that I am currently troubleshooting. I will keep you posted.

One question, when/where are you calling `initilizeLocalTracks()`?

Thank you,

Ryan

**Comment by paynerc** [comment]
@ankitappstreet,

Also another question. I see that you are calling `startCapture` on the `CameraSource`. Are you ever calling `stopCapture` after you are finished with a call?

Ryan

**Comment by piyushtank** [comment]
@ankitappstreet 

We have just released TwilioVoideo SDK 3.2.3 [[changelogs](https://www.twilio.com/docs/video/changelog-twilio-video-ios-version-3x#323-april-1-2020)], which fixes the crash in TVICameraSource teardown code path.

Try it out and let us know if you still running into the crash.

Best,
Piyush

**Comment by paynerc** [comment]
@ankitappstreet,

As @piyushtank mentioned we have made the `3.2.3` release which fixes a crash that sounds similar to what you were reporting. Please upgrade to the latest version and let us know if you are still experiencing the crash. I am going to close this ticket in the meantime but feel free to reopen it if you are still having issues.

Thank you,

Ryan
