### ISSUE TITLE
Support as Swift Package Dependancy

### ISSUE THREAD

**Issue by ghost** [twilio/twilio-video-ios#84]
### Description

At the moment the video sdk is not a Swift Package

### Versions

All relevant version information for the issue.

#### Video iOS SDK

Twilio Video SDK iOS 3.2.2

#### Xcode

Version 11.4

**Comment by paynerc** [comment]
@henrydennis-sonin,

At the present time, the Swift Package Manager doesn't support Binary Distributions as documented [here](https://forums.swift.org/t/distributing-binary-closed-source-libraries/23737/3). 

If they implement support for Binary Distributions in the future, we could investigate distributing the Twilio SDKs in that fashion.

Thank you,

Ryan

**Comment by daigok** [comment]
Swift 5.3 will support binary dependencies. Could you reopen this issue if you have any plan to support it? Because it's handy to keep track of the progress and also someone interested in this topic can easily find the status.

**Comment by paynerc** [comment]
We are again investigating supporting Swift Package Manager and I will reopen this ticket to track the progress.

Ryan

**Comment by 4brunu** [comment]
Hi,
Xcode 12 was released today, and now SPM supports binary dependencies.
Any news adding support for SPM for Twilio Video?
Thanks 😊

**Comment by paynerc** [comment]
@4brunu,

I cannot provide a firm date yet, but 4.0.0 of Twilio Video is being configured for SPM distribution.

Stay tuned,

Ryan

**Comment by 4brunu** [comment]
Thanks 👍

**Comment by paynerc** [comment]
Twilio Video iOS 4.0 was released on December 4th and supports distribution via Swift Package Manager.

Ryan

**Comment by Arneoldenhave** [comment]
SPM not able to resolve dependency:

Error:
```
because no versions of twilio-video-app-ios match the requirement 4.0.0..<5.0.0 
and root depends on twilio-video-app-ios 4.0.0..<5.0.0, version solving failed.
```
My Package.swift
```
.package(url: "https://github.com/twilio/twilio-video-app-ios.git", from: "4.0.0")
```

**Comment by paynerc** [comment]
@Arneoldenhave

The package url is wrong. It should read `https://github.com/twilio/twilio-video-ios.git` for the `TwilioVideo.xcframework` dependency.

The URL you have listed is for the Twilio Video demonstration app.

Ryan
