### ISSUE TITLE
Remote Audio Overall Volume Control

### ISSUE THREAD

**Issue by cjcomputers** [twilio/twilio-video-ios#86]
Does have any ideas on how to get remote participant volume control working? My app is an enterprise distributed app that runs on a kiosk so that the hardware buttons on the iPad are not accessible to the end user. As such, a volume slider on screen is really my only option. To note, our use case only ever involves one remote participant so we only ever have to deal with one remote audio track. Unlike some other requests I've seen recently, I don't need to adjust the volume of individual remote participants.

My first attempt was to us an MPVolumeView to control the system volume, but that only adjusts the audio category or "Video/Audio" used for the likes of AVAudioPlayer instances. It will not adjust the volume of the "PhoneCall" category as used by the Twilio SDK.

My latest attempts have been to try and use an AudioSink to take the resultant CMBufferSample and play it through an AVAudioPlayer or using AudioQueue, but that is turning out to be a hassle to setup and also I believe I just recently read that audio has to be playing through the audio session for the AudioSink to get the samples. So even if I could get the captured buffers to immediately play, it sounds like it would be on top of the already playing audio so there would for sure be an echo I'm guessing.

Does anyone have an idea on how to make this work? Again, my use case doesn't really need to adjust the audio of an individual recipient, but of the overall remote audio streams.

**Comment by piyushtank** [comment]
@cjcomputers I haven't tried myself changing volume level of the remote participants using MPVolumeView but it doesn't work for category video or voice chat, an alternative is to get complete control over the AudioDevice. At present, our DefaultAudioDevice API doesn't allow changing audio output level. But you can write your own custom audio device based on your need.

Here is a sample app which demonstrates how to implement custom audio device - https://github.com/twilio/video-quickstart-ios/tree/master/AudioDeviceExample

Let me know if you have any questions.

**Comment by cjcomputers** [comment]
Thanks @piyushtank! I think we're on the right track. When using the ExampleCoreAudioDevice, the MPVolumeView works out of box to adjust the remote audio track! BUT... As noted in the example, "ExampleCoreAudioDevice is a playback only device. Because of this, any attempts to create a LocalAudioTrack will result in an exception being thrown. In this example we will only share video (where available) and not audio." So no audio gets sent back to the other end of the call. Changing the audio device to the ExampleAVAudioEngineDevice just gets us back to square one.

So... Any easy way to also use the microphone and pass audio back across when using the ExampleCoreAudioDevice?

Thanks for your help so far!

**Comment by piyushtank** [comment]
@cjcomputers The `ExampleCoreAudioDevice` demonstrates the playback used case only, and `ExampleAVAudioEngineDevice` demonstrates record+playback both with AVAudioEngine mixing file audio feature. Since `ExampleAVAudioEngineDevice ` uses `video chat` category,  so you should hit the same problem as DefaultAudioDevice upon use of MPVolumeView. For voip calls, `video chat` category is must for echo cancellation. So I wouldn't make any change there, but you can change volume by -
 
1. With custom audio device (ExampleAVAudioEngineDevice), you have access to AudioUnit, you may want to change volume using `AudioUnitSetParameter` on AudioUnit. Since the ExampleAVAudioEngineDevice always uses AudioUnit on worker thread, make sure you execute changing audio level code using `TVIAudioDeviceExecuteWorkerBlock`. Personally haven't tried using `AudioUnitSetParameter` yet but it looks very promising.

2. And if your app doesn't use the audio mixing feature you can remove AVAudioEngine specific code from audio device. It's up to you - keeping audio engine code in audio device is fine too.

**Comment by cjcomputers** [comment]
@piyushtank Unfortunately, using AudioUnitSetParameter may be a no-go. Every time I try to set or even  just read any Volume related parameters or properties (such as kMatrixMixerParam_Volume or kMultiChannelMixerParam_Volume, etc.), I keep getting back either kAudioUnitErr_InvalidParameter or kAudioUnitErr_InvalidProperty.

Looping back to the ExampleCoreAudioDevice, our solution actually uses a telephone handset connected to the iPad kiosk. With that in mind, echo cancellation might not be a must have. If that is the case, is it possible to enable the input on the ExampleCoreAudioDevice while keeping the output as is? I found this post https://gitmemory.com/issue/twilio/video-quickstart-ios/444/565231384 from @ceaglest which implies it might be. I had started implementing the steps he states are required yesterday, but so far haven't been able to get the input audio to come across. If we think that might work, I'll keep at it.

Thanks!

**Comment by piyushtank** [comment]
@cjcomputers If your app does not require echo-cancellation, and RemoteIO gives you the intended behavior, as a workaround, in ExampleAVAudioEngineDevice, you can change [this line](https://github.com/twilio/video-quickstart-ios/blob/b74e1c1c4f49ae23f326bd3e53ec750f126d5b2d/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m#L750) to 
```objc
    audioUnitDescription.componentSubType = kAudioUnitSubType_RemoteIO;
``` 

Let me know if you have any questions.

**Comment by cjcomputers** [comment]
That did the trick!  I can now adjust the volume using the MPVolumeView and the microphone audio is passed back as expected. And I don't experience any issues with echoes. I sincerely appreciate the help and I owe you a drink. Thanks!

**Comment by piyushtank** [comment]
Glad to hear that `RemoteIO` did the trick. Cheers!!

**Comment by cjcomputers** [comment]
Just wanted to drop one more quick note so the record is complete in case anyone else comes looking. I also had to comment out the setMode code below in the setupAVAudioSession function in order for it to work as intended.

if (![session setMode:AVAudioSessionModeVideoChat error:&error]) {
     NSLog(@"Error setting session category: %@", error);
}

Thanks again!

**Comment by vani2** [comment]
I try do the same thing. But I've got crashes or don't hear another side.

What was changed from example code:

```swift
audioUnitDescription.componentSubType = kAudioUnitSubType_RemoteIO; 
```
and

```swift
if (![session setCategory:AVAudioSessionCategoryPlayAndRecord withOptions: AVAudioSessionCategoryOptionDefaultToSpeaker| AVAudioSessionCategoryOptionAllowBluetooth | AVAudioSessionCategoryOptionAllowBluetoothA2DP error:&error]) {
    NSLog(@"Error setting category: %@", error);
}
```

Do you have some ideas why does it happened? @cjcomputers @piyushtank

**Comment by cjcomputers** [comment]
Hey @vani2 . The first part looks right, but I think you may have commented out the incorrect piece for the second part. Should be the piece regarding AVAudioSessionModeVideoChat that gets commented out. Here is a copy of my setupAVAudioSession function.

`- (void)setupAVAudioSession {
    AVAudioSession *session = [AVAudioSession sharedInstance];
    NSError *error = nil;

    if (![session setPreferredSampleRate:kPreferredSampleRate error:&error]) {
        NSLog(@"Error setting sample rate: %@", error);
    }

    if (![session setPreferredOutputNumberOfChannels:kPreferredNumberOfChannels error:&error]) {
        NSLog(@"Error setting number of output channels: %@", error);
    }

    /*
     * We want to be as close as possible to the 10 millisecond buffer size that the media engine needs. If there is
     * a mismatch then TwilioVideo will ensure that appropriately sized audio buffers are delivered.
     */
    if (![session setPreferredIOBufferDuration:kPreferredIOBufferDuration error:&error]) {
        NSLog(@"Error setting IOBuffer duration: %@", error);
    }

    if (![session setCategory:AVAudioSessionCategoryPlayAndRecord error:&error]) {
        NSLog(@"Error setting session category: %@", error);
    }
    
    /*
    if (![session setMode:AVAudioSessionModeVideoChat error:&error]) {
        NSLog(@"Error setting session category: %@", error);
    }
    */

    [self registerAVAudioSessionObservers];

    if (![session setActive:YES error:&error]) {
        NSLog(@"Error activating AVAudioSession: %@", error);
    }

    if (session.maximumInputNumberOfChannels > 0) {
        if (![session setPreferredInputNumberOfChannels:TVIAudioChannelsMono error:&error]) {
            NSLog(@"Error setting number of input channels: %@", error);
        }
    }
}`

**Comment by vani2** [comment]
Interesting, I deleted this chunk too

```swift
/*
if (![session setMode:AVAudioSessionModeVideoChat error:&error]) {
    NSLog(@"Error setting session category: %@", error);
}
*/
```

but must use `[session setCategory:AVAudioSessionCategoryPlayAndRecord withOptions: AVAudioSessionCategoryOptionDefaultToSpeaker| AVAudioSessionCategoryOptionAllowBluetooth | AVAudioSessionCategoryOptionAllowBluetoothA2DP error:&error]`

instead of `[session setCategory:AVAudioSessionCategoryPlayAndRecord error:&error]` to control volume of bluetooth speakers.

**Comment by vani2** [comment]
I noticed a crash `AURemoteIO::IOThread (49): EXC_BAD_ACCESS (code=1, address=0x68)` at this call `TVIAudioDeviceWriteCaptureData(context->deviceContext, audioBuffer, audioBufferSizeInBytes);`.
If I wrap up by `TVIAudioDeviceExecuteWorkerBlock` it doesn't crash but I don't hear any sound.

<img width="1221" alt="Screenshot 2021-08-18 at 11 38 16" src="https://user-images.githubusercontent.com/4734983/129866515-8fea50a0-4ccb-4d40-b700-884d53f8057a.png">

```
Thread 29 name:  AURemoteIO::IOThread
Thread 29 Crashed:
0   My App    	                        0x0000000104545d58 0x10453c000 + 40280
1   My App    	                        0x0000000104545d58 0x10453c000 + 40280
2   libEmbeddedSystemAUs.dylib    	0x00000001d1dc4698 0x1d1d24000 + 657048
3   libEmbeddedSystemAUs.dylib    	0x00000001d1e0c234 0x1d1d24000 + 950836
4   libAudioToolboxUtility.dylib  	0x00000001b4b5afd0 0x1b4b49000 + 73680
5   libAudioToolboxUtility.dylib  	0x00000001b4b5b3f0 0x1b4b49000 + 74736
6   libEmbeddedSystemAUs.dylib    	0x00000001d1dba4ec 0x1d1d24000 + 615660
7   libsystem_pthread.dylib       	0x00000001eb568bfc 0x1eb567000 + 7164
8   libsystem_pthread.dylib       	0x00000001eb571758 0x1eb567000 + 42840

Thread 29 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000001   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x00000000000036c8
    x4: 0x00000000000062dc   x5: 0x000000016bf528b0   x6: 0x0000000000000039   x7: 0x0000000000001100
    x8: 0x187e5fba142f00c2   x9: 0x187e5fba142f00c2  x10: 0x00000000000007fd  x11: 0x000000000000001e
   x12: 0x0000000000000001  x13: 0x00000000c768a81f  x14: 0x00000000c788b000  x15: 0x000000000008b000
   x16: 0x00000001b4403348  x17: 0x0000000202711a70  x18: 0x0000000000000000  x19: 0x0000000283f34bd0
   x20: 0x0000000000000200  x21: 0x0000000000000000  x22: 0x0000000283f35e60  x23: 0x0000000000000003
   x24: 0x0000000283f34d68  x25: 0x0000000000000200  x26: 0x000000016bf52bd0  x27: 0x00000001c2a253ea
   x28: 0x0000000000000000   fp: 0x000000016bf52ba0   lr: 0x081c678104545d58
    sp: 0x000000016bf52b30   pc: 0x0000000104545d58 cpsr: 0x60000000
   esr: 0x92000006 (Data Abort) byte read Translation fault
```
