### ISSUE TITLE
How To Subscribe To Video Tracks Of Already Present Participants ?

### ISSUE THREAD

**Issue by iUsmanN** [twilio/twilio-video-ios#89]
Hi,

I was having trouble figuring out how to subscribe to the remote video tracks of the already present participants in a room when I join.

Currently, if a new user joins the room after I have joined it, the `didSubscribeToVideoTrack` delegate is called and I get the RemoteVideoTrack to display.

However, I cannot seem to Subscribe to the VideoTracks of the already present participants when I connect to a room in the `roomDidConnect` delegate.

Kindly help me out on this. How do I subscribe to the RemoteVideoTracks of already present participants in a Room ?

Thank you very much
Usman

**Comment by ceaglest** [comment]
Hi Usman,

Our Quickstart Example can offer some guidance here. You will want to make sure that you handle existing connected Participants by assigning a TVIRemoteParticipant delegate before `roomDidConnect` returns. Take a look at the QS [roomDidConnect](https://github.com/twilio/video-quickstart-ios/blob/master/VideoQuickStart/ViewController.swift#L365) implementation.

```.swift
    func roomDidConnect(room: Room) {
        logMessage(messageText: "Connected to room \(room.name) as \(room.localParticipant?.identity ?? "")")

        // This example only renders 1 RemoteVideoTrack at a time. Listen for all events to decide which track to render.
        for remoteParticipant in room.remoteParticipants {
            remoteParticipant.delegate = self
        }
    }
```

I hope that helps, let me know if you have any more questions.

Thanks,
Chris

**Comment by iUsmanN** [comment]
Wonderful!
Thank you very much, Chris :)
