### ISSUE TITLE
roomDidFailToConnect delegate

### ISSUE THREAD

**Issue by dsngeu** [twilio/twilio-video-ios#91]
Error Domain=com.twilio.video Code=53005 "DNS resolution for signaling failed" UserInfo={NSLocalizedDescription=DNS resolution for signaling failed}

**Comment by ceaglest** [comment]
Hi @dsngeu,

This error occurs when you cannot resolve the hostname for the signaling server (usually `global.vss.twilio.com` unless you selected a region manually). Is DNS configured correctly on your network, for example can you try:

```
dig global.vss.twilio.com A
dig global.vss.twilio.com AAAA
```

There is more information in the requirements for [Signaling Communication](https://www.twilio.com/docs/video/ip-address-whitelisting#signaling-communication).

Thanks,
Chris

**Comment by ceaglest** [comment]
Closing since I didn't hear back from you. Hopefully you were able to resolve the DNS issue!

**Comment by EricGustin** [comment]
For anyone that is running into this issue only on a physical device:

Make sure your device is either connected to WiFi or through your carrier.
