### ISSUE TITLE
"Empty Credentials" while initating a call from iOS

### ISSUE THREAD

**Issue by yatindma** [twilio/twilio-video-ios#92]
While starting the call from iOS sometimes call is going and getting disconnected in 2-3 sec and the error log we are getting on twilio is "Empty Credentials" for android it's working perfectly fine

Please help to fix this bug

**Comment by ceaglest** [comment]
Hey @yatindma,

If I understand your question then I think the best place to discuss is in: https://github.com/twilio/voice-quickstart-ios/issues/342
