### ISSUE TITLE
How to show status at top bar status during ongoing call when app goes in background.

### ISSUE THREAD

**Issue by dsngeu** [twilio/twilio-video-ios#93]
- When I put the app in background during Twilio video call, iPhone do not show any indication at status bar that "Touch to return to call" like Skype or zoom video call. 

I am using pod 'TwilioVideo', '~> 3.2'
and video call feature.

expected: during video call if I put the app in background, then status bar must shows "Touch to return to call".

Question:
how can I achieve this?

**Comment by piyushtank** [comment]
@dsngeu In order to access audio in background, and show call on status bar, you should set background modes in your app's info.plist file  - see [this](https://github.com/twilio/video-quickstart-ios/blob/master/VideoQuickStart/Info.plist#L9-L12) 
```xml
	<key>UIBackgroundModes</key>
	<array>
		<string>audio</string>
	</array>
```

**Comment by dsngeu** [comment]
@piyushtank 
yes its work but.
**if audio is on during video call and app in background, then status bar shows audio is on. - its fine**
but when local and remote participant audio is off during the video call and app in background then then status bar shows nothing. 
I expect the status bar shows or indicate me that video call is going on. just like when we share screen and app in background then status bar indicate video recording is running. 

how can I achieve this?

**Comment by dsngeu** [comment]
@piyushtank 
can you please help me out.
