### ISSUE TITLE
Is it possible to give "spacial" effect on remote audio?

### ISSUE THREAD

**Issue by matiasalvarezaw** [twilio/twilio-video-ios#94]
I need to transform remote audio in a room with only 2 participants so that it gives the perception that voice is at the rear, right, left, or front (configurable by a button).

Is this possible? 

Please, can you guide how this configuration should be?

Thanks in advance! 

PS: Sorry if this is not the appropriate site to ask this. Where should I ask it?

**Comment by piyushtank** [comment]
@matiasalvarezaw apologies for not following up on this earlier. 

Yes, it is possible by writing your own custom audio device. Take a look at our [ExampleAVAudioEngine](https://github.com/twilio/video-quickstart-ios/blob/master/AudioDeviceExample/AudioDevices/ExampleAVAudioEngineDevice.m) audio device for more information.
