### ISSUE TITLE
Room disconnected if app in  background during video call

### ISSUE THREAD

**Issue by dsngeu** [twilio/twilio-video-ios#95]
if I put my app in background (audio is off) during video call, for next 3-4 minute later I got disconnected from the room.

expected: if I put my app in background during video call it should not be disconnected from room.

**Comment by paynerc** [comment]
@dsngeu,

Are you using Peer-To-Peer or Group Rooms? What versions of iOS are you seeing this behavior?

Do you have debug logging and/or RoomSids that you could share? If you don't feel comfortable sharing those on this public Github issue you can create a support ticket by emailing support@twilio.com with that information, reference this issue and that I asked you to submit it. If you do create a support issue, respond here with the support issue number and I can go and find the issue and we can take a look at what is going on.

Thank you,

Ryan

**Comment by dsngeu** [comment]
@paynerc 

 func roomDidDisconnect(room: Room, error: Error?) {

//Logs -- 
//po print(error)
1- Optional(Error Domain=com.twilio.video Code=53204 "Participant not found" UserInfo={NSLocalizedDescription=Participant not found})
2 - po print(room.remoteParticipants)
[<TVIRemoteParticipant: 0x281b0b2f0>]
}

- version:- iOS 13.3.1
- 'TwilioVideo', '~> 3.2'
 --------------------------------

Scenario:- 

there are two 2 participant connected in room,
one from android device and one from ios device and both the the device successfully conneccted.


ios device case1 - if audio is on and user put the app in background then red color status bar indicate about audio on,
in this case user did not disconnected from the room, it works fine.
ios device case1 - if audio is off/ and video is also get off (in this case status bar do not indicate anything) if user put the app in background so in this case after 1-3 minutes later user get disconnected from room. [this is case]

**Comment by paynerc** [comment]
@dsngeu,

The situation you are describing sounds similar to [this issue](https://github.com/twilio/twilio-video-ios/issues/25#issuecomment-423262380) when using P2P rooms. Can you verify whether you are using Peer-to-peer or group rooms?

Ryan

**Comment by dsngeu** [comment]
@paynerc 
yes this is same issue.

**Comment by dsngeu** [comment]
@paynerc its peer to peer rooms. 
so how to solve this problem ?

**Comment by piyushtank** [comment]
@dsngeu did you get a chance to look at the @ceaglest 's suggestion [here](https://github.com/twilio/twilio-video-ios/issues/25#issuecomment-423262380).

**Comment by designzoo-adrian** [comment]
I too have this same issue. In my case I have the following:

**Participant 1 - Broadcast Extension** 
- sharing their screen (publish only participant)

**Participant 2 - Host App**
- sharing front camera and mic audio
- receiving audio and camera from another web based participant

If Participant 2 does not share audio to the room and host app is moved to the background. After 1-3 minutes Participant 2 is disconnected from the room. The only solution I have found is to keep mic on for participant 2.
