### ISSUE TITLE
Default Video Bitrate is very low

### ISSUE THREAD

**Issue by sleman** [twilio/twilio-video-ios#97]
### Description

Sending videotrack without explicitly setting max bitrate leads to ~ 600 kbps video which is very low and not documented anywhere.

### Steps to Reproduce

Use latest ios sdk.

Set codec to: h264
Set videoFormat to one with 1280x720

#### Expected Behavior

Reasonable bitrate is sent to receivers.
#### Actual Behavior

Low bitrate of 600 kbps is sent to receivers unless max bitrate is set in the code. Even when it's set the actual bitrate sent is much less than the max.

#### Reproduces How Often

100%

#### Video iOS SDK

3.2

#### Xcode

11.4

#### iOS Version

[e.g. 11.2.6]

#### iOS Device

Apple 11-Inch iPad Pro

**Comment by piyushtank** [comment]
@sleman Thanks for reaching out. Using the `EncodingParameters` APIs on Video SDK you can set the max and min bitrates. We have [examples](https://github.com/twilio/video-quickstart-ios/blob/master/Utils/Settings.swift#L61) in our quickstart to do so. [Here](https://twilio.github.io/twilio-video-ios/docs/latest/Classes/TVIEncodingParameters.html#//api/name/maxVideoBitrate) is the documentation.

Let me know if you have any questions.
